### PR TITLE
Add pytorch checkpoint variable dumping script

### LINKED ISSUE #243: Add a script that dumps weights from non-TensorFlow framework models.
We currently have a script that dumps weights from a TensorFlow model:
https://github.com/PAIR-code/deeplearnjs/blob/master/scripts/dump_checkpoint_vars.py

It generates a binary file for each of the weights as simply packed floats, and a manifest.json file:
https://github.com/PAIR-code/deeplearnjs/tree/master/demos/mnist

It would be great to have versions of this script for Caffe / PyTorch / etc.

### PR DESCRIPTION
**Pull request by ManrajGrover**
This pull request adds PyTorch checkpoint variable dumping script. This partially fixes #243. We still need to add scripts for Caffe.

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/274)

### CODE REVIEW

**Comment by nsthorat** [comment]
Awesome! one comment

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[scripts/dump_pytorch_checkpoint_vars.py, line 44 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/274#-Kxn26dOkttrBGZtb7YY:-Kxn26dOkttrBGZtb7YZ:b-la1idr) ([raw file](https://github.com/pair-code/deeplearnjs/blob/93be1ce642c0e864b4da6de8a2c50ee6d9616f17/scripts/dump_pytorch_checkpoint_vars.py#L44)):*
> ```Python
> 
> 
> def main():
> ```

we're going to be writing quite a few of these, what do you think about the following:

1) make a new directory for checkpoint dumping scripts
2) have a common base class for checkpoint dumping. This will make sure that the format of the JSON file is shared / regex is shared / some flags are shared.
3) each of the subclasses (TF / pytorch / caffe) will just override var_name_to_filename and other customizations.

This way we can ensure we don't get drift between them as they're a little hard to unit test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/274#-:-Kxn2UQIgu0qApwWffH6:b7sbako)*

**Comment by ManrajGrover** [comment]
Yes, it makes sense to move them to separate directory. And yes, DRY code over everything. :) Will make the required changes. I believe we can test them using a small model. We can also integrate tox. Should I add tests for the same?

**Comment by nsthorat** [comment]
I don't think unit tests are necessary here, it may be complicated to make meaningful tests. Let's just move them over and shared code :)

**Comment by nsthorat** [comment]
Hi @ManrajGrover, is this ready for me to look at again?

**Comment by ManrajGrover** [comment]
@nsthorat Yes. :) I'm also working on Caffe script for which I'll send a separate PR.

**Comment by nsthorat** [comment]
@ManrajGrover can you sync with @chaosmail on this thread

https://github.com/PAIR-code/deeplearnjs/issues/267

**Comment by nsthorat** [comment]
This is excellent. Thank you for making these changes.

Couple comments then I will merge it :)

---

Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[scripts/dump_checkpoints/pytorch_checkpoint_dumper.py, line 102 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/274#-KyC4HhV3AxsFmyYmgGJ:-KyC4HhV3AxsFmyYmgGK:bnuf375) ([raw file](https://github.com/pair-code/deeplearnjs/blob/a3bd8a8446abf7b039e98c8a6f3c9c5104e276f6/scripts/dump_checkpoints/pytorch_checkpoint_dumper.py#L102)):*
> ```Python
>       self.manifest[var_name] = {'filename': var_filename, 'shape': var_shape}
> 
>       print('Writing variable ' + var_name + '...')
> ```

put this in the base class under dump_weights

---

*[scripts/dump_checkpoints/tensorflow_checkpoint_dumper.py, line 91 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/274#-KyC48PP9Bt-y87lCgqk:-KyC48PP9Bt-y87lCgql:b-tv5kgy) ([raw file](https://github.com/pair-code/deeplearnjs/blob/a3bd8a8446abf7b039e98c8a6f3c9c5104e276f6/scripts/dump_checkpoints/tensorflow_checkpoint_dumper.py#L91)):*
> ```Python
> 
>     for var_name, var_shape in var_to_shape_map.iteritems():
>       if self.should_ignore(var_name) or var_name == 'global_step':
> ```

can this for loop be in a base class? And TensorFlow's should_ignore would call the super and then also check var_name === 'global_step'?

---

*[scripts/dump_checkpoints/tensorflow_checkpoint_dumper.py, line 98 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/274#-KyC3uI4esPpCUmiQMxk:-KyC3uI4esPpCUmiQMxl:b1h6i8w) ([raw file](https://github.com/pair-code/deeplearnjs/blob/a3bd8a8446abf7b039e98c8a6f3c9c5104e276f6/scripts/dump_checkpoints/tensorflow_checkpoint_dumper.py#L98)):*
> ```Python
>       self.manifest[var_name] = {'filename': var_filename, 'shape': var_shape}
> 
>       print('Writing variable ' + var_name + '...')
> ```

print this in the base class so we don't have to do it everywhere.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/274#-:-KyC4KcBFP_M8_paFAEz:bsvky1o)*

**Comment by nsthorat** [comment]
BTW, can you just make sure the TF checkpoint dumping works? Run it on an MNIST checkpoint and make sure the manifest / files are reasonable.

---

Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/274#-:-KyC4PUh2SFvlmli3SFP:b-nrnqgn)*

**Comment by ManrajGrover** [comment]
> @ManrajGrover can you sync with @chaosmail on this thread

Sure, I'll go through the thread.

> can this for loop be in a base class? And TensorFlow's should_ignore would call the super and then also check var_name === 'global_step'?

Tensorflow and Pytorch have different business logics. I'm not sure if it would be possible to do that.

> BTW, can you just make sure the TF checkpoint dumping works? Run it on an MNIST checkpoint and make sure the manifest / files are reasonable.

I tried it on `Inception` checkpoint and it seems to be working.

Made other changes. :)

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Reviewed 3 of 8 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/274#-:-KyCRrV98_DLb81NHwgL:b-jbsf8z)*

**Pull request merged**
