### PR TITLE
Fixes #506: Adds greater equal operator

### LINKED ISSUE #506: Request for greater_equal
Akin to TF's greater_equal(): https://www.tensorflow.org/api_docs/python/tf/greater_equal

Other comparison operators may be useful: https://www.tensorflow.org/api_guides/python/control_flow_ops#Comparison_Operators

### PR DESCRIPTION
**Pull request by ManrajGrover**
This PR adds greater equal operator for NDArrays which can be used as `math.greaterEqual(a, b)`. 

Reference:
#506

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/541)

### CODE REVIEW

**Comment by dsmilkov** [comment]
Looks great. Just a small request for one more test. See comment below.

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/math/logical_ops_test.ts, line 30 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/541#-L2mCm7v8_24yYGoYYdg:-L2mBw7KJUdY9z_iYn1y:b-i6bjn6) ([raw file](https://github.com/pair-code/deeplearnjs/blob/38708bd914317f8dfcfc9ec854cebb1b756f862a/src/math/logical_ops_test.ts#L30)):*
> ```XML
>   const tests: MathTests = it => {
>     // Array1D:
>     it('Array1D - int32', math => {
> ```

add at least one test that asserts that the dtype of the output is bool, even though the inputs are float32/int32.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/541#-:-L2mCtofhO3I8-aIKoa2:b-dmth8m)*

**Comment by ManrajGrover** [comment]
@dsmilkov Made the required changes :)

**Comment by dsmilkov** [comment]
:lgtm_strong: Ups, sorry I merged #542 (rename of test files) and you'll have a conflict. Ping me when resolved and I'll merge!

---

Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/541#-:-L2pUGGpndMk7xfZXsQJ:bhmery2)*

**Comment by ManrajGrover** [comment]
@dsmilkov Fixed the conflicts. Merging this will cause another conflict in my new PR #547. Once this is merged, I'll fix that again. :)

**Pull request merged**
