### PR TITLE
Add ELU ops

### PR DESCRIPTION
**Pull request by Lewuathe**
Though ELU activation function was added in #231, there is no corresponding ops function.

see: #223

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/300)

### CODE REVIEW

**Comment by nsthorat** [comment]
Great contribution! See my comments on the other PR about adding the top level graph method, as well as the stuff about "math.scope()"

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/300#-:-KyBzStD2e19ISNgKC4r:b-qtdyza)*

**Comment by nsthorat** [comment]
Merged the other PR, just FYI

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/300#-:-Kz-6znc493JBsdHiNye:b-fo5t5m)*

**Comment by Lewuathe** [comment]
Thanks, I'll update as well. 

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/300#-:-Kz-7UDXpVf27mQ-w4bP:b-e2pn8p)*

**Comment by nsthorat** [comment]
Thanks for this PR! Let's hold off on more ops on the graph from here, as we have to migrate these all to eager and that will be harder if we have more ops.

Two small things then will merge

:lgtm_strong: 

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/math/activation_functions.ts, line 118 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/300#-KzOroTiubY18UfJFfBU:-KzOroTiubY18UfJFfBV:blf59n1) ([raw file](https://github.com/pair-code/deeplearnjs/blob/c44cc5d7269c06d5cf6f28ba40266885a9f854b9/src/math/activation_functions.ts#L118)):*
> ```XML
>   output<T extends NDArray>(math: NDArrayMath, x: T) {
>     return math.scope(() => {
>       return math.elu(x);
> ```

no need for scope

---

*[src/math/activation_functions.ts, line 124 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/300#-KzOrpKMDqbRazPrnACr:-KzOrpKMDqbRazPrnACs:blf59n1) ([raw file](https://github.com/pair-code/deeplearnjs/blob/c44cc5d7269c06d5cf6f28ba40266885a9f854b9/src/math/activation_functions.ts#L124)):*
> ```XML
>   der<T extends NDArray>(math: NDArrayMath, x: T, y: T) {
>     return math.scope(() => {
>       return math.eluDer(x);
> ```

no need for scope

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/300#-:-KzOrYeQCovtLpYeEFAu:bex6be8)*

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/300#-:-KzU1hQRjPg7dgQ_bC5n:b-jbsf8z)*

**Pull request merged**
