### PR TITLE
Decouple NDArray storage from NDArray and make math global

### PR DESCRIPTION
**Pull request by dsmilkov**
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/404)

### CODE REVIEW

**Comment by nsthorat** [comment]
:lgtm_strong:

I am so excited for auto-tracking and the simplicity of default math!

Left some comments inline, but nothing serious. Before you commit this could you add a description to the PR / commit before you merge?

---

Reviewed 9 of 18 files at r1, 25 of 25 files at r2.
Review status: all files reviewed at latest revision, 20 unresolved discussions, some commit checks failed.

---

*[src/environment.ts, line 161 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L01TUqaX9EOlHgcF5LR:-L01TUqaX9EOlHgcF5LS:bs7kc5j) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/environment.ts#L161)):*
> ```XML
> 
> function getBestBackend(): string {
>   const backendIds = ['webgl', 'cpu'];
> ```

How about "orderedBackendIds" or "backendPriorities"

Let's also add an enum for these

---

*[src/environment.ts, line 221 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L01UUwPyS0LgIegsZGB:-L01UUwPyS0LgIegsZGC:bj2y9bn) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/environment.ts#L221)):*
> ```XML
> 
>   setGlobalMath(math: NDArrayMath) {
>     this.currentMath = math;
> ```

let's call "currentMath" "globalMath" just so it's clear they're the same thing

---

*[src/environment.ts, line 227 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L01UKMvZow42zECl5Di:-L01UKMvZow42zECl5Dj:b-80q0io) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/environment.ts#L227)):*
> ```XML
>     if (this.currentMath == null) {
>       const bestBackend = getBestBackend();
>       this.currentMath = new NDArrayMath(bestBackend, false);
> ```

`const safeMode = false;
... NDArrayMath(bestBackend, safeMode);`

---

*[src/index.ts, line 56 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L01Uec1bPT3GUoi8m6X:-L01Uec1bPT3GUoi8m6Y:b-a7o4om) ([raw file](https://github.com/pair-code/deeplearnjs/blob/4a2a350ff2480a4fbf271b04fbc8ab5151142c34/src/index.ts#L56)):*
> ```XML
> export {LSTMCell, NDArrayMath} from './math/math';
> // TODO(nsthorat): Remove this once we decouple NDArray from storage mechanism.
> export {initializeGPU} from './math/ndarray';
> ```

can you add a TODO in our models to move away from initializeGPU since this is going to break them if we update?

---

*[src/test_util.ts, line 208 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L01UlrHZ7AgQDrR3n_n:-L01UlrHZ7AgQDrR3n_o:b-ccm91n) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/test_util.ts#L208)):*
> ```XML
>       testNameBase, tests as Tests[],
>       (testName, tests, features) => executeMathTests(testName, tests, () => {
>         return new NDArrayMath(new MathBackendCPU(), true);
> ```

name "true"

Here and in describeMathGPU

---

*[src/graph/ops/reduce_sum.ts, line 35 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L01VDnSalxXf26YjxxQ:-L01VDnSalxXf26YjxxR:bmqqlzc) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/graph/ops/reduce_sum.ts#L35)):*
> ```XML
>     super();
>     util.assertShapesMatch(outTensor.shape, []);
>     this.ones = NDArray.zeros(x.shape);
> ```

use ones:
https://github.com/PAIR-code/deeplearnjs/blob/master/src/math/ndarray.ts#L132

---

*[src/math/math.ts, line 68 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L02nuw1vk5_hi_YiVRG:-L02nuw1vk5_hi_YiVRH:b-em4fzx) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/math/math.ts#L68)):*
> ```XML
>     this.backend.write(id, values, dtype, shape);
>   }
>   disposeData(id: number): void {
> ```

nit: move disposeData to the end of class (this is going to be a commonly read file and we wont )

---

*[src/math/math.ts, line 96 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L01VlRJtIXMxA5wW8L-:-L01VlRJtIXMxA5wW8L0:b-hhfi3h) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/math/math.ts#L96)):*
> ```XML
>    *     a math.scope() which will automatically clean up intermediate NDArrays.
>    */
>   constructor(backend: string|MathBackend, private safeMode: boolean) {
> ```

once the backend string is an enum, change the type here

---

*[src/math/math.ts, line 271 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L01W0sLqYlemJ7oETOD:-L01W0sLqYlemJ7oETOE:b-s3svle) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/math/math.ts#L271)):*
> ```XML
>             'leaks.');
>       }
>       this.startScope();
> ```

Why are you starting a new scope here?

---

*[src/math/math_test.ts, line 49 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L02r3a5AxuRizYZxvy8:-L02r3a5AxuRizYZxvy9:bz55glm) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/math/math_test.ts#L49)):*
> ```XML
>       a.dispose();
>       b.dispose();
>       expect(math.getNumArrays()).toBe(0);
> ```

Instead of disposing these NDArrays manually, you now have auto-tracking functionality. I think a better test here would be instead to wrap everything before this line in a scope to make sure global tracking is working.

Alternatively you could move a unit test with that functionality to its own test.

---

*[src/math/matmul_test.ts, line 298 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L01WWm63GvwPcuSAmb7:-L01WWm63GvwPcuSAmb8:b-23esy0) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/math/matmul_test.ts#L298)):*
> ```XML
> 
> const gpuTests: MathTests = it => {
>   it('Matrix times vector, larger than max texture size', math => {
> ```

this test is a little misleading now, maybe just say large matrix

---

*[src/math/ndarray.ts, line 222 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L01YRbCSmoBSOj8CZM5:-L01YRbCSmoBSOj8CZM6:b-mpymr6) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/math/ndarray.ts#L222)):*
> ```XML
> 
>   asType<G extends keyof DataTypes>(dtype: G): NDArray<G> {
>     const vals = this.dataSync();
> ```

add a TODO here (we migrated fromPixels properly to both backends but we didn't migrate asType)

---

*[src/math/ndarray.ts, line 243 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L02pvYbm-dgMGI3Dl-e:-L02pvYbm-dgMGI3Dl-f:b44d424) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/math/ndarray.ts#L243)):*
> ```XML
>   }
> 
>   set(value: number, ...locs: number[]) {
> ```

can you check locs.length === this.rank

---

*[src/math/ndarray.ts, line 308 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L01ZGT2Gk9meOouYpMx:-L01ZGT2Gk9meOouYpMy:b-6l3lw8) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/math/ndarray.ts#L308)):*
> ```XML
> 
>   dispose(): void {
>     ENV.math.disposeData(this.id);
> ```

Small regression: now if you try to use a disposed NDArray we don't get a nice error (which was the point of `throwIfDisposed`).

You should bring that back (just save a bit here since you want it to be backend agnostic).

---

*[src/math/reduction_ops_test.ts, line 442 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L02qcEeSXFdlv4QQGWn:-L02qcEeSXFdlv4QQGWo:b4ai4h6) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/math/reduction_ops_test.ts#L442)):*
> ```XML
>       test_util.expectNumbersClose(result.get(), 7);
> 
>       a.dispose();
> ```

optional: these disposes are now not needed since all NDArrays are tracked!

---

*[src/math/types.ts, line 32 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L01ZbEgVuS5raTJHc1e:-L01ZbEgVuS5raTJHc1f:b45tc6m) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/math/types.ts#L32)):*
> ```XML
> }
> 
> export interface Int32And {
> ```

how about `Int32UpcastWith` here and below

---

*[src/math/backends/backend.ts, line 28 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L01TsyUTpBN0xMdIhcq:-L01TsyUTpBN0xMdIhcr:boobvih) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/math/backends/backend.ts#L28)):*
> ```XML
> }
> 
> export const BACKEND_REGISTRY: {[id: string]: MathBackend} = {};
> ```

let's make the id an enum (you can use the keyword 'in' to use non-string keys)

---

*[src/math/backends/backend_webgl.ts, line 61 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L01_MVqAQ5u4KgqQGQK:-L01_MVsBYsl5F5GMiwz:bf7sha4) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/math/backends/backend_webgl.ts#L61)):*
> ```XML
> import * as webgl_util from './webgl/webgl_util';
> 
> function float32ToTypedArray<T extends keyof DataTypes>(
> ```

nit: these utilities seem less important than the backend itself, can you move it to the bottom of the file?

---

*[src/math/backends/backend_webgl.ts, line 128 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L02naPJLCB6ibIoRPw6:-L02naPJLCB6ibIoRPw7:b-d6840f) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/math/backends/backend_webgl.ts#L128)):*
> ```XML
>     }
>   }
>   disposeData(id: number): void {
> ```

nit: move this after the read functions

---

*[src/math/backends/webgl/gpgpu_math.ts, line 52 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L02mrnTF1V6Zn4ZrJWa:-L02mrnTF1V6Zn4ZrJWb:b4b7syp) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/math/backends/webgl/gpgpu_math.ts#L52)):*
> ```XML
> }
> 
> export interface ArrayData<T> {
> ```

can you restrict T here so it's clear what ArrayData is for?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-:-L02rkSu5K97zh-UkEXr:bmeidsu)*

**Comment by dsmilkov** [comment]
Thank you for the great thorough review!

---

Reviewed 1 of 25 files at r2.
Review status: all files reviewed at latest revision, 20 unresolved discussions, some commit checks failed.

---

*[src/environment.ts, line 161 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L01TUqaX9EOlHgcF5LR:-L03KoYlye65ACYPglgF:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/environment.ts#L161)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

How about "orderedBackendIds" or "backendPriorities"

Let's also add an enum for these
</blockquote></details>

Done.

---

*[src/environment.ts, line 221 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L01UUwPyS0LgIegsZGB:-L03KwLeWbdollrcFg8c:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/environment.ts#L221)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

let's call "currentMath" "globalMath" just so it's clear they're the same thing
</blockquote></details>

Done.

---

*[src/environment.ts, line 227 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L01UKMvZow42zECl5Di:-L03L1nr0qHkYOmGnrkL:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/environment.ts#L227)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

`const safeMode = false;
... NDArrayMath(bestBackend, safeMode);`
</blockquote></details>

Done.

---

*[src/index.ts, line 56 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L01Uec1bPT3GUoi8m6X:-L03L4widZgtk5quHzKk:bnqadli) ([raw file](https://github.com/pair-code/deeplearnjs/blob/4a2a350ff2480a4fbf271b04fbc8ab5151142c34/src/index.ts#L56)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

can you add a TODO in our models to move away from initializeGPU since this is going to break them if we update?
</blockquote></details>

It turns out all usages of `initializeGPU` in our codebase have a TODO already :)

We almost don't really need a TODO. It's really nice that models depend on older version of dljs and nothing breaks. And when we update demos/package.json and reinstall dljs, the compiler will start complaining.

---

*[src/test_util.ts, line 208 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L01UlrHZ7AgQDrR3n_n:-L03M7UX7mQgJA_3621l:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/test_util.ts#L208)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

name "true"

Here and in describeMathGPU
</blockquote></details>

Done.

---

*[src/graph/ops/reduce_sum.ts, line 35 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L01VDnSalxXf26YjxxQ:-L03MHLxxwfIY5hvStJh:b-ku9hw1) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/graph/ops/reduce_sum.ts#L35)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

use ones:
https://github.com/PAIR-code/deeplearnjs/blob/master/src/math/ndarray.ts#L132
</blockquote></details>

Done. This was before I synced!

---

*[src/math/math.ts, line 68 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L02nuw1vk5_hi_YiVRG:-L03M_vANUhwKrckKSae:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/math/math.ts#L68)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

nit: move disposeData to the end of class (this is going to be a commonly read file and we wont )
</blockquote></details>

Done.

---

*[src/math/math.ts, line 96 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L01VlRJtIXMxA5wW8L-:-L03XPI-vE_XhFH4CmXh:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/math/math.ts#L96)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

once the backend string is an enum, change the type here
</blockquote></details>

Done.

---

*[src/math/math.ts, line 271 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L01W0sLqYlemJ7oETOD:-L03ODjm3uykUjtpb-Jz:by3qkdy) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/math/math.ts#L271)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

Why are you starting a new scope here?
</blockquote></details>

I didn't add it for a particularly strong reason. The reasoning was: when safeMode is off, and the user didn't use explicit scope, an implicit scope is nice, since that allows us to add `math.cleanup()` later, which will clean up things in the implicit scope. Implicit scope is also useful when we visualize allocated arrays in a hierarchical way, useful for debugging.

I can remove it if you feel otherwise.

---

*[src/math/math_test.ts, line 49 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L02r3a5AxuRizYZxvy8:-L03QEHgo5gPToQ_qYEP:b1vydhr) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/math/math_test.ts#L49)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

Instead of disposing these NDArrays manually, you now have auto-tracking functionality. I think a better test here would be instead to wrap everything before this line in a scope to make sure global tracking is working.

Alternatively you could move a unit test with that functionality to its own test.
</blockquote></details>

great idea. added.

---

*[src/math/matmul_test.ts, line 298 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L01WWm63GvwPcuSAmb7:-L03N7yELRjfAF5XtA8x:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/math/matmul_test.ts#L298)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

this test is a little misleading now, maybe just say large matrix
</blockquote></details>

Done.

---

*[src/math/ndarray.ts, line 222 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L01YRbCSmoBSOj8CZM5:-L03XYnPO17zPfmNEVSc:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/math/ndarray.ts#L222)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

add a TODO here (we migrated fromPixels properly to both backends but we didn't migrate asType)
</blockquote></details>

Done.

---

*[src/math/ndarray.ts, line 243 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L02pvYbm-dgMGI3Dl-e:-L03Xq8WtbsTxKkY98Fk:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/math/ndarray.ts#L243)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

can you check locs.length === this.rank
</blockquote></details>

Done.

---

*[src/math/ndarray.ts, line 308 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L01ZGT2Gk9meOouYpMx:-L03ZhrkahcoyoYcnn8I:bdg2shj) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/math/ndarray.ts#L308)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

Small regression: now if you try to use a disposed NDArray we don't get a nice error (which was the point of `throwIfDisposed`).

You should bring that back (just save a bit here since you want it to be backend agnostic).
</blockquote></details>

Done. Brough back isDisposed and throwIfDisposed

---

*[src/math/reduction_ops_test.ts, line 442 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L02qcEeSXFdlv4QQGWn:-L03Y7xNQ-81JivfCM0R:b-nlonwd) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/math/reduction_ops_test.ts#L442)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

optional: these disposes are now not needed since all NDArrays are tracked!
</blockquote></details>

great point, especially since we do startScope endScope internally in test_util. Won't clean up all tests in this PR, but it's great to see the benefit of global tracking in providing much cleaner tests!

---

*[src/math/types.ts, line 32 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L01ZbEgVuS5raTJHc1e:-L03Yjjd6sYdlPl2Jjy7:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/math/types.ts#L32)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

how about `Int32UpcastWith` here and below
</blockquote></details>

Done.

---

*[src/math/backends/backend.ts, line 28 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L01TsyUTpBN0xMdIhcq:-L03Wc4hU5YE3UwFziFF:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/math/backends/backend.ts#L28)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

let's make the id an enum (you can use the keyword 'in' to use non-string keys)
</blockquote></details>

Done.

---

*[src/math/backends/backend_webgl.ts, line 61 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L01_MVqAQ5u4KgqQGQK:-L03WjmxfkKyYs4xRVHb:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/math/backends/backend_webgl.ts#L61)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

nit: these utilities seem less important than the backend itself, can you move it to the bottom of the file?
</blockquote></details>

Done.

---

*[src/math/backends/backend_webgl.ts, line 128 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L02naPJLCB6ibIoRPw6:-L03XIo0ipSn36pKyq3M:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/math/backends/backend_webgl.ts#L128)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

nit: move this after the read functions
</blockquote></details>

Done.

---

*[src/math/backends/webgl/gpgpu_math.ts, line 52 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L02mrnTF1V6Zn4ZrJWa:-L03Ysv8jCeLkdM797PT:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/math/backends/webgl/gpgpu_math.ts#L52)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

can you restrict T here so it's clear what ArrayData is for?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-:-L03Zmp54t8bbXQiyir4:bgy9z0c)*

**Comment by nsthorat** [comment]
Review status: 21 of 34 files reviewed at latest revision, 20 unresolved discussions, some commit checks failed.

---

*[src/math/math.ts, line 271 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L01W0sLqYlemJ7oETOD:-L05LCC-cnDDvOFiiTZn:b-d4or5p) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/math/math.ts#L271)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

I didn't add it for a particularly strong reason. The reasoning was: when safeMode is off, and the user didn't use explicit scope, an implicit scope is nice, since that allows us to add `math.cleanup()` later, which will clean up things in the implicit scope. Implicit scope is also useful when we visualize allocated arrays in a hierarchical way, useful for debugging.

I can remove it if you feel otherwise.
</blockquote></details>

How about let's start a global scope when math is created. I think this will have a problem where if you create too many inner scopes and there isn't a corresponding endScope, you will not clean everything up.

`math.cleanup()` will then simply end the global scope, and start a new global scope.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404)*

**Comment by nsthorat** [comment]
FYI you will have to merge with:
  https://github.com/PAIR-code/deeplearnjs/pull/425

**Comment by dsmilkov** [comment]
Review status: 19 of 36 files reviewed at latest revision, 20 unresolved discussions, some commit checks pending.

---

*[src/math/math.ts, line 271 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404#-L01W0sLqYlemJ7oETOD:-L0A5BqYXP6FdAEmO6ER:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/59b90006db5ce5ca09e77dd33c4fe3e84ae3dc59/src/math/math.ts#L271)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

How about let's start a global scope when math is created. I think this will have a problem where if you create too many inner scopes and there isn't a corresponding endScope, you will not clean everything up.

`math.cleanup()` will then simply end the global scope, and start a new global scope.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/404)*

**Pull request merged**
