### PR TITLE
Added YOLO demo with MobileNet backend

### PR DESCRIPTION
**Pull request by experiencor**
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/361)

### CODE REVIEW

**Comment by experiencor** [comment]
I signed it!

**Comment by experiencor** [comment]
I made a small demo here: https://experiencor.github.io/yolo_demo/demo.html.

**Comment by nsthorat** [comment]
This is so wonderful, thank you for doing this. Your demo is so cool :)

A few comments, then I will merge this in.

High level stuff:

* Make sure you remove bundle.js.
* I will upload these weights to GCP for you, before I do, which version of mobilenet is this? There are multiple versions.

---

Reviewed 4 of 149 files at r1.
Review status: 4 of 149 files reviewed at latest revision, 17 unresolved discussions.

---

*[models/mobilenet/demo.html, line 36 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-KzOu2ho7NBm2_wKW7Ya:-KzOu2ho7NBm2_wKW7Yb:b-2gsnxt) ([raw file](https://github.com/pair-code/deeplearnjs/blob/65c3ea7380d58b1beee9d973646d84775d2d369d/models/mobilenet/demo.html#L36)):*
> ```HTML
>     resultElement.innerText = 'Loading mobilenet...';
> 
>     // If dl isn't loaded, wait 1 second.
> ```

this is fixed, no need for this

---

*[models/mobilenet/demo.html, line 73 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-KzOuSJ_2Kn8umEHKdXU:-KzOuSJ_2Kn8umEHKdXV:bwy497v) ([raw file](https://github.com/pair-code/deeplearnjs/blob/65c3ea7380d58b1beee9d973646d84775d2d369d/models/mobilenet/demo.html#L73)):*
> ```HTML
>       context.textBaseline = 'top';
>       context.fillStyle = box.getColor();
>       
> ```

remove empty lnies

---

*[models/mobilenet/mobilenet.ts, line 62 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-KzOx0ZE5NG_zSxd9-R1:-KzOx0ZE5NG_zSxd9-R2:b-m6ydak) ([raw file](https://github.com/pair-code/deeplearnjs/blob/65c3ea7380d58b1beee9d973646d84775d2d369d/models/mobilenet/mobilenet.ts#L62)):*
> ```XML
>    */
>   async predict(input: Array3D): Promise<{
>     netout: Array4D
> ```

No need to make an object, just return Promise<Array4D>

By the way, I thought mobilenet also makes a prediction over the 1000 classes, or is it only doing bounding boxes?

---

*[models/mobilenet/mobilenet.ts, line 100 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-KzOuh8Jcq48fR4BEHI3:-KzOuh8Jcq48fR4BEHI4:b-hpwdx) ([raw file](https://github.com/pair-code/deeplearnjs/blob/65c3ea7380d58b1beee9d973646d84775d2d369d/models/mobilenet/mobilenet.ts#L100)):*
> ```XML
>     } 
> 
>   private _conv_block(inputs: Array3D, strides: [number, number]) { 
> ```

_conv_block is python style guide, can you call this `convBlock`

Can you also type the return? `Array3D` most likely

This comment refers to all the other functions in this file too.

---

*[models/mobilenet/mobilenet.ts, line 102 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-KzOupc3KgSvzbJjzi-U:-KzOupc3KgSvzbJjzi-V:b-yrdp7y) ([raw file](https://github.com/pair-code/deeplearnjs/blob/65c3ea7380d58b1beee9d973646d84775d2d369d/models/mobilenet/mobilenet.ts#L102)):*
> ```XML
>   private _conv_block(inputs: Array3D, strides: [number, number]) { 
> 
>     const x1 = this.math.conv2d(inputs, // input
> ```

only put comments where it's not obvious (bias)

---

*[models/mobilenet/mobilenet.ts, line 109 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-KzOv0pSpTNpUWnNVD2z:-KzOv0pSpTNpUWnNVD3-:b-gcv9yj) ([raw file](https://github.com/pair-code/deeplearnjs/blob/65c3ea7380d58b1beee9d973646d84775d2d369d/models/mobilenet/mobilenet.ts#L109)):*
> ```XML
> 
>     const x2 = this.math.batchNormalization3D(x1,
>                                               this.variables['conv1_bn/moving_mean'] as Array1D, // mean
> ```

no need for comments next to variables, it's obvious what it's doing - same in the rest of the file

---

*[models/mobilenet/mobilenet.ts, line 152 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-KzOvVOs_0cSTrM-hdjP:-KzOvFtCAerKxrylqRID:bit3rgr) ([raw file](https://github.com/pair-code/deeplearnjs/blob/65c3ea7380d58b1beee9d973646d84775d2d369d/models/mobilenet/mobilenet.ts#L152)):*
> ```XML
>   }
> 
>   interpret_netout(netout: Array4D){ 
> ```

type the return, it should be a promise

---

*[models/mobilenet/mobilenet.ts, line 155 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-KzOvcr8IQuTny8k0v_j:-KzOvcr8IQuTny8k0v_k:b1cnd3o) ([raw file](https://github.com/pair-code/deeplearnjs/blob/65c3ea7380d58b1beee9d973646d84775d2d369d/models/mobilenet/mobilenet.ts#L155)):*
> ```XML
>     // interpret the output by the network
>     var [GRID_H, GRID_W, BOX, CLASS] = netout.shape;
>     const values = netout.getValues() as Float32Array;
> ```

High level comment:

You're operating on the Float32Array, which will happen on the CPU. Let's try to keep this on the GPU. I left some comments below about how to do that.

---

*[models/mobilenet/mobilenet.ts, line 156 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-KzOviR9o_bab2pA3Vn2:-KzOviR9o_bab2pA3Vn3:bg48iiq) ([raw file](https://github.com/pair-code/deeplearnjs/blob/65c3ea7380d58b1beee9d973646d84775d2d369d/models/mobilenet/mobilenet.ts#L156)):*
> ```XML
>     var [GRID_H, GRID_W, BOX, CLASS] = netout.shape;
>     const values = netout.getValues() as Float32Array;
>     const boxes: BoundingBox[] = new Array<BoundingBox>();
> ```

const boxes: BoundingBox[] = [];

---

*[models/mobilenet/mobilenet.ts, line 164 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-KzOvlJb2giqYwUHCTry:-KzOvlJb2giqYwUHCTrz:bqx6ynr) ([raw file](https://github.com/pair-code/deeplearnjs/blob/65c3ea7380d58b1beee9d973646d84775d2d369d/models/mobilenet/mobilenet.ts#L164)):*
> ```XML
>         for (var box = 0; box < BOX; box++) {
>           const l_bound = netout.locToIndex([row, col, box, 0]);
>          
> ```

remove blank line

---

*[models/mobilenet/mobilenet.ts, line 169 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-KzOw5GmQTP_NvwE54Ir:-KzOw5GmQTP_NvwE54Is:brtcj3v) ([raw file](https://github.com/pair-code/deeplearnjs/blob/65c3ea7380d58b1beee9d973646d84775d2d369d/models/mobilenet/mobilenet.ts#L169)):*
> ```XML
> 
>           // get and adjust class likelihoods
>           var classes = values.slice(l_bound+5, l_bound+5+CLASS);
> ```

values is the Float32Array, we can use math.slice1D|2D|3D|4D to get the NDArray from netout

---

*[models/mobilenet/mobilenet.ts, line 170 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-KzOwFR__QLGKAXdO6UA:-KzOwFR__QLGKAXdO6UB:b-1bpd00) ([raw file](https://github.com/pair-code/deeplearnjs/blob/65c3ea7380d58b1beee9d973646d84775d2d369d/models/mobilenet/mobilenet.ts#L170)):*
> ```XML
>           // get and adjust class likelihoods
>           var classes = values.slice(l_bound+5, l_bound+5+CLASS);
>           classes = this.sofmax(classes).map((x) => (x * confidence)).map((x) => x > this.THRESHOLD ? x : 0);
> ```

once you have classes as an NDArray, you can call our math.softmax.

If you want to clip values over THRESHOLD, what you can do is subtract THRESHOLD (math.subtract with a broadcast scalar) and then call math.relu

---

*[models/mobilenet/mobilenet.ts, line 172 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-KzOwXhpMI9XcGjqG1gY:-KzOwXhpMI9XcGjqG1gZ:b-pmz8vg) ([raw file](https://github.com/pair-code/deeplearnjs/blob/65c3ea7380d58b1beee9d973646d84775d2d369d/models/mobilenet/mobilenet.ts#L172)):*
> ```XML
>           classes = this.sofmax(classes).map((x) => (x * confidence)).map((x) => x > this.THRESHOLD ? x : 0);
> 
>           if (classes.reduce(( a, b ) => a + b, 0) > 0) {
> ```

here is where you can now download to the CPU. Make sure you call  "await softmaxOutput.data()" before doing this work.

---

*[models/mobilenet/mobilenet.ts, line 194 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-KzOxN38F9LS_HI4eg1f:-KzOxN38F9LS_HI4eg1g:b-towuk8) ([raw file](https://github.com/pair-code/deeplearnjs/blob/65c3ea7380d58b1beee9d973646d84775d2d369d/models/mobilenet/mobilenet.ts#L194)):*
> ```XML
>       var indices = new Array(all_probs.length);
> 
>       for (var i = 0; i < all_probs.length; ++i) indices[i] = i;
> ```

curly braces, linter will fail here

---

*[models/mobilenet/mobilenet.ts, line 195 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-KzOxPsHZPVQsSp_f4FE:-KzOxPsHZPVQsSp_f4FF:b-lbm5se) ([raw file](https://github.com/pair-code/deeplearnjs/blob/65c3ea7380d58b1beee9d973646d84775d2d369d/models/mobilenet/mobilenet.ts#L195)):*
> ```XML
> 
>       for (var i = 0; i < all_probs.length; ++i) indices[i] = i;
>       indices.sort((a,b) => {return all_probs[a] > all_probs[b] ? 1 : 0});
> ```

indices.sort((a,b) => all_probs[a] > all_probs[b] ? 1 : 0);

---

*[models/mobilenet/mobilenet.ts, line 200 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-KzOxSwyGP7fAR2SiW-i:-KzOxSwyGP7fAR2SiW-j:b2nh75k) ([raw file](https://github.com/pair-code/deeplearnjs/blob/65c3ea7380d58b1beee9d973646d84775d2d369d/models/mobilenet/mobilenet.ts#L200)):*
> ```XML
>         const index_i = indices[i];
> 
>         if (boxes[index_i].probs[cls] == 0) {
> ```

===

---

*[models/mobilenet/mobilenet.ts, line 201 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-KzOxTZeA-fClh1Edi_N:-KzOwnhzguP9GuNLHfge:b-qbf8ac) ([raw file](https://github.com/pair-code/deeplearnjs/blob/65c3ea7380d58b1beee9d973646d84775d2d369d/models/mobilenet/mobilenet.ts#L201)):*
> ```XML
> 
>         if (boxes[index_i].probs[cls] == 0) {
>           continue
> ```

semicolon

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-:-KzOxkPxEuTfM3kqnJOJ:b2rimpq)*

**Comment by experiencor** [comment]
Hi @nsthorat Thank you for your review. I have updated the code (https://github.com/experiencor/deeplearnjs).

```which version of mobilenet is this?```

Acorrding the MobileNet paper (https://arxiv.org/pdf/1704.04861.pdf), this version is 1.0-MobiletNet-416.

```By the way, I thought mobilenet also makes a prediction over the 1000 classes, or is it only doing bounding boxes?```

Yes. MobileNet can be trained to either do prediction over 1000 classess or do bounding box detection. I'm more familiar with detection, hence I give it try here. It can be easily repurposed for class prediction by changing the last layer of the current implementation.

```await softmaxOutput.data()```

Do you think that my new code need ```await softmaxOutput.data()``` (https://github.com/experiencor/deeplearnjs/blob/master/models/mobilenet/mobilenet.ts)? I want to get the raw Array4D.

**Comment by nsthorat** [comment]
Thanks for the notes. I'm looking at this page:

https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.md

And wondering which version of the checkpoint you dumped (accuracy / weights tradeoff). We should document that (and even rename the model to be clear).

Regarding the 1000 classes - is this part of the same model? Or is it totally separate? If it's separate, maybe we should call this MobileNetSegmentation with a version / checkpoint info as well.

Which point do you mean for `await softmax.data()`? This will resolve to the CPU, we probably want to return the NDArray itself, and let interpret netout do the BoundingBoxes. If we can return another NDArray for global class prediction as well, that would be ideal.

Cheers!

**Comment by experiencor** [comment]
Hi @nsthorat,

1. I didn't dump the weight from (https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.md), but from the model built using (https://github.com/fchollet/keras/blob/master/keras/applications/mobilenet.py). I trained the model myself. I can say that my model is equivalent to MobileNet_v1_1.0_416. 

2. The implemented model only do Object Detection, no class prediction at all. Maybe we can call it MobileNet_v1_1.0_416_ObjectDetection.

3. Got it. I don't download softmaxOutput to CPU in the new code hence it's not needed.

**Comment by nsthorat** [comment]
I see - what do you think of dumping it from the pretrained checkpoints instead of your own? Not that I don't trust you, but it's good to have the "official" checkpoint as a reference so we can match activations, etc.

**Comment by experiencor** [comment]
Hi @nsthorat! It's not possible to use the official weight of MobileNet for YOLO object detection as the official weight is trained for the classification task. The architecture is identical but the weights are completely different. Is it still able to merge to deeplearn.js? I find that object detection is also very interesting application besides classification.

Anyway, it's straightforward to use Google's official weight for the classification task using my code. I will make another demo for this classification task. It should be identical to the SqueezeNet that, except that the backend is MobileNet instead of SqueezeNet.

**Comment by experiencor** [comment]
@nsthorat I have add another classification demo using the official weights released by Google (@https://github.com/experiencor/deeplearnjs/tree/master/models).

mobilenet_detection corresponds to MobileNet_v1.0_416_YOLO_Detection
mobilenet_classification corresponds to MobileNet_v1_1.0_224 (in https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.md)

Cheers

**Comment by nsthorat** [comment]
Thanks for the clarification!

Okay, I moved the weights for YOLO onto GCP:
http://storage.googleapis.com/learnjs-data/checkpoint_zoo/yolo_mobilenet_v1_1.0_416/manifest.json

I started moving the regular mobilenet weights over, but I realized you also had dumped a bunch of training parameters (RMSProp weights, exponential moving average, etc).

Once you remove those, I will upload to GCP, then I will be able to review the PR (reviewable is freezing because 600 files :P )

**Comment by experiencor** [comment]
@nsthorat I have changed the Detection code to use the weights hosted on Google. I have also removed the redundant weights of Classification and changed the manifest.json file accordingly.

**Comment by nsthorat** [comment]
Alright, mobilenet is up!

http://storage.googleapis.com/learnjs-data/checkpoint_zoo/mobilenet_v1_1.0_224/manifest.json

Reviewing your PR now, in the meantime please remove the weights :)

**Comment by experiencor** [comment]
@nsthorat Local weights were removed.

**Comment by nsthorat** [comment]
High-level comments:

1) Rename the directories to match what we did on GCP (the folder names should match). MobileNet refers to classification, yolo_mobilenet is about detection.
2) You have lots of linter errors (which will make the build fail if we commit this). Please run "yarn lint" and fix the offending issues.

Almost there! Mostly style stuff (if this is checked in the build will break because of style problems)

---

Review status: 0 of 22 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[models/mobilenet_classification/demo.html, line 16 at r5](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-L-7r92DSzjNiKIvCbtT:-L-7r92DSzjNiKIvCbtU:b-thj4u0) ([raw file](https://github.com/pair-code/deeplearnjs/blob/7d7fb9ddd3f581c95e5cf8d154217a2f16a9f7a8/models/mobilenet_classification/demo.html#L16)):*
> ```HTML
> 
>     // If dl isn't loaded, wait 1 second.
>     if (dl == null) {
> ```

you dont need this check anymore

---

*[models/mobilenet_classification/imagenet_classes.ts, line 1 at r5](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-L-7rO_lVZwtAJKRsRUg:-L-7rO_lVZwtAJKRsRUh:bmol142) ([raw file](https://github.com/pair-code/deeplearnjs/blob/7d7fb9ddd3f581c95e5cf8d154217a2f16a9f7a8/models/mobilenet_classification/imagenet_classes.ts#L1)):*
> ```XML
> /**
> ```

can you move imagenet_classes out to a common place since we use this for SqueezeNet too?

---

*[models/mobilenet_classification/mobilenet_classification.ts, line 27 at r5](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-L-7rktjDDgyFXouZ3w-:-L-7rktjDDgyFXouZ3w0:b-rgyzkg) ([raw file](https://github.com/pair-code/deeplearnjs/blob/7d7fb9ddd3f581c95e5cf8d154217a2f16a9f7a8/models/mobilenet_classification/mobilenet_classification.ts#L27)):*
> ```XML
> 
>   // yolo variables
>   private HALF_TWO_FIVE_FIVE  = Scalar.new(255.0/2);
> ```

PREPROCESS_DIVISOR

---

*[models/mobilenet_classification/mobilenet_classification.ts, line 39 at r5](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-L-7rqrLAdHCgCUhcjrS:-L-7rqrLAdHCgCUhcjrT:btd3cno) ([raw file](https://github.com/pair-code/deeplearnjs/blob/7d7fb9ddd3f581c95e5cf8d154217a2f16a9f7a8/models/mobilenet_classification/mobilenet_classification.ts#L39)):*
> ```XML
>         (this.math as NDArrayMathGPU).getTextureManager());
> 
>         //this.math.enableDebugMode();
> ```

remove this comment

---

*[models/mobilenet_detection/index.ts, line 18 at r5](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-L-7sJgDXLIGnN-ThWb-:-L-7sJgDXLIGnN-ThWb0:bd1c0hc) ([raw file](https://github.com/pair-code/deeplearnjs/blob/7d7fb9ddd3f581c95e5cf8d154217a2f16a9f7a8/models/mobilenet_detection/index.ts#L18)):*
> ```XML
>  */
> 
> export {MobileNet} from './mobilenet_detection';
> ```

this should be called YoloMobileNetDetection (And directory should be renamed)

---

*[models/mobilenet_detection/mobilenet_detection.ts, line 42 at r5](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-L-7sPjw9iq40aNsp3TU:-L-7sPjw9iq40aNsp3TV:b-mu0t41) ([raw file](https://github.com/pair-code/deeplearnjs/blob/7d7fb9ddd3f581c95e5cf8d154217a2f16a9f7a8/models/mobilenet_detection/mobilenet_detection.ts#L42)):*
> ```XML
>         (this.math as NDArrayMathGPU).getTextureManager());
> 
>         //this.math.enableDebugMode();
> ```

remove this line

---

*[models/mobilenet_detection/mobilenet_detection.ts, line 102 at r5](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-L-7sVxnYJtyLyk5aT7A:-L-7sVxnYJtyLyk5aT7B:b1qwetj) ([raw file](https://github.com/pair-code/deeplearnjs/blob/7d7fb9ddd3f581c95e5cf8d154217a2f16a9f7a8/models/mobilenet_detection/mobilenet_detection.ts#L102)):*
> ```XML
>     const x1 = this.math.conv2d(inputs,
>                                 this.variables['conv1/kernel'] as Array4D,
>                                 null,
> ```

I wanted you to keep the comment where it's non-obvious (for places where you have a null)

---

*[models/mobilenet_detection/mobilenet_utils.ts, line 64 at r5](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-L-7smz6RIXhLXHoYOjf:-L-7smz6RIXhLXHoYOjg:bx1ekjb) ([raw file](https://github.com/pair-code/deeplearnjs/blob/7d7fb9ddd3f581c95e5cf8d154217a2f16a9f7a8/models/mobilenet_detection/mobilenet_utils.ts#L64)):*
> ```XML
>   }
> 
>   private overlap(interval_a: [number, number], interval_b: [number, number]): number {
> ```

camel cas in typescript: intervalA (and everywhere else in this file you do that)

---

*[models/squeezenet/bundle.js, line 0 at r5](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-L-7suTrRiBV0RVHvURq:-L-7suTrRiBV0RVHvURr:bmhmdrj) ([raw file](https://github.com/pair-code/deeplearnjs/blob/7d7fb9ddd3f581c95e5cf8d154217a2f16a9f7a8/models/squeezenet/bundle.js#L0)):*
How come this bundle is being checked in? This should be .gitignored

---

*[models/squeezenet/squeezenet.ts, line 159 at r5](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-L-7srA0i6hbzkGKhWwD:-L-7srA0i6hbzkGKhWwE:bf8h0c9) ([raw file](https://github.com/pair-code/deeplearnjs/blob/7d7fb9ddd3f581c95e5cf8d154217a2f16a9f7a8/models/squeezenet/squeezenet.ts#L159)):*
> ```XML
>     const topClassesToProbability: {[className: string]: number} = {};
>     for (let i = 0; i < topkIndices.length; i++) {
>       topClassesToProbability[IMAGENET_CLASSES[topkIndices[i]-1]] = topkValues[i];
> ```

why are you subtracting one here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-:-L-7r_p9zotgADHba4H1:bwl0hpg)*

**Comment by experiencor** [comment]
> can you move imagenet_classes out to a common place since we use this for SqueezeNet too?

@nsthorat The official MobileNet additionally has the Background class, so its imagenet_classes.ts has 1001 classes, instead of 1000 classes in the case of SqueezeNet. How would you like to handle this case?

**Comment by experiencor** [comment]
The code now passed all tests in ```yarn test``` and ```yarn lint```. It does not pass ```yarn test-travis``` as I don't have a MAC to test ```"karma start --browsers='bs_firefox_mac,bs_chrome_mac' --singleRun"```.

**Comment by nsthorat** [comment]
Woohoo! Almost done. Just lint errors now (please run `yarn lint` from each models directory)

I will merge after these changes :)

---

Review status: 0 of 21 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[models/mobilenet/mobilenet.ts, line 165 at r6](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-L-IGv3yCWBawIsCrcmS:-L-IGv3yCWBawIsCrcmT:b-6aakmk) ([raw file](https://github.com/pair-code/deeplearnjs/blob/7a5931f17cf85bba4e9c499bdc9b8be610029bf0/models/mobilenet/mobilenet.ts#L165)):*
> ```XML
>     }
>     return topClassesToProbability;
>   }   
> ```

`yarn lint` should be run from this directory as well

---

*[models/mobilenet/tsconfig.json, line 2 at r6](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-L-IH0rQCyUZhyuX7znb:-L-IH0rQCyUZhyuX7znc:b-blqny9) ([raw file](https://github.com/pair-code/deeplearnjs/blob/7a5931f17cf85bba4e9c499bdc9b8be610029bf0/models/mobilenet/tsconfig.json#L2)):*
> ```JSON
> {
>     "compilerOptions": {
> ```

this file needs to parallel the other models/tsconfig.json files (extends the top level tsconfig)

---

*[models/yolo_mobilenet/package.json, line 27 at r6](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-L-IHFTJl8BYQlvksO54:-L-IHFTJl8BYQlvksO55:b-d3ijdi) ([raw file](https://github.com/pair-code/deeplearnjs/blob/7a5931f17cf85bba4e9c499bdc9b8be610029bf0/models/yolo_mobilenet/package.json#L27)):*
> ```JSON
>     "prep": "yarn && mkdirp dist",
>     "build": "browserify --standalone yolo_mobilenet yolo_mobilenet.ts -p [tsify] -o dist/bundle.js",
>     "lint": "tslint -p . -t verbose",
> ```

make sure you run `yarn lint` from this dir (you still have lint errors)

---

*[models/yolo_mobilenet/tsconfig.json, line 2 at r6](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-L-IHJMgxjqKl2OjTCM_:-L-IHJMgxjqKl2OjTCMa:bnm92ux) ([raw file](https://github.com/pair-code/deeplearnjs/blob/7a5931f17cf85bba4e9c499bdc9b8be610029bf0/models/yolo_mobilenet/tsconfig.json#L2)):*
> ```JSON
> {
>     "compilerOptions": {
> ```

this needs to extend the base tsconfig (see squeezenet)

---

*[models/squeezenet/bundle.js, line  at r5](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-L-7suTrRiBV0RVHvURq:-L-IHQajAWDZXnF6Pxtj:b-bc7cgw) ([raw file](https://github.com/pair-code/deeplearnjs/blob/7d7fb9ddd3f581c95e5cf8d154217a2f16a9f7a8/models/squeezenet/bundle.js#L)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

How come this bundle is being checked in? This should be .gitignored
</blockquote></details>

This is still here, shouldn't be checked in.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-:-L-IHTGybzXLSRLXuVyz:b-jc1weu)*

**Comment by nsthorat** [comment]
If you look at the bottom of this PR:
image

You will see "the Travis CI build failed".

Please make sure this passes, you can click "details" to see the failure.

**Comment by nsthorat** [comment]
Here is the current failure:

https://travis-ci.org/PAIR-code/deeplearnjs/builds/310172581?utm_source=github_status&utm_medium=notification

**Comment by nsthorat** [comment]
Review status: 0 of 21 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[models/yolo_mobilenet/package.json, line 2 at r7](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-L-OO22Q7uD9x7LJJi_t:-L-OO22Q7uD9x7LJJi_u:b-46jwkq) ([raw file](https://github.com/pair-code/deeplearnjs/blob/108d549197a95b8b84b5ef7478a10d8c1b5aa4b7/models/yolo_mobilenet/package.json#L2)):*
> ```JSON
> {
>   "name": "deeplearn-yolo-mobilet",
> ```

mobilenet

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361)*

**Comment by nsthorat** [comment]
Let me know once the build succeeds! :)

**Comment by experiencor** [comment]
@nsthorat I passed all tests the first time :).

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: 0 of 22 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/361#-:-L-dfrIgIePWAmnNda4C:b-jbsf8z)*

**Comment by nsthorat** [comment]
Thanks for bearing with me, congrats!

**Comment by hpssjellis** [comment]
unpkg.com/deeplearn-mobilenet not working yet


`<script src="https://unpkg.com/deeplearn-mobilenet"></script>`

Does not seem to be working, also not on [npm](https://www.npmjs.com/search?q=deeplearn-mobilenet). Not sure if [yolo](https://github.com/PAIR-code/deeplearnjs/tree/master/models/yolo_mobilenet) has it's own src or uses the same one.

**Comment by nsthorat** [comment]
It's not ready yet, I have a little cleanup to do first!

**Pull request merged**
