### PR TITLE
Add dist dir to gitignore

### PR DESCRIPTION
**Pull request by Lewuathe**
`npm run build` creates a build directory in `dist`. We can add this dir to gitignore.

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/94)

### CODE REVIEW

**Comment by nsthorat** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[.gitignore, line 10 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/94#-KtItjjPWlDNm_Y0lo2y:-KtItjjPWlDNm_Y0lo2z:b-bis4xn) ([raw file](https://github.com/pair-code/deeplearnjs/blob/f0e703862c9624767f5bf1769564c95bde3d82b3/.gitignore#L10)):*
> ```
> npm-debug.log
> .DS_Store
> dist
> ```

can you make this `dist/` just so that it mirrors the style from above (and it's clear it's a dir)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/94)*

**Comment by Lewuathe** [comment]
@nsthorat Thanks for checking. I updated accordingly.

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/94#-:-KtMULbfD96-NmXNX4PI:b-jbsf8z)*

**Comment by nsthorat** [comment]
Update this branch and then I will merge it (someone added something else to gitignore)!

**Pull request merged**
