### PR TITLE
Add CI Travis testing for all modular libs (demos, models, starter projects)

### PR DESCRIPTION
**Pull request by dsmilkov**
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/362)

### CODE REVIEW

**Comment by nsthorat** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 5 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/362#-KzLbhYHuElo4y1ooQkX:-KzLbhYHuElo4y1ooQkY:b-9586wc) ([raw file](https://github.com/pair-code/deeplearnjs/blob/7bd15df091b7874e5afb79c21b802e262db897b0/.travis.yml#L5)):*
> ```YAML
> install:
>   - yarn prep
>   - cd demos && yarn prep && cd ..
> ```

What do you think of writing a simple script that does recursively looks at models / start subdirectories? that way every time we add new stuff we don't have to add it here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/362)*

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/362#-:-KzLcRkoPpNfj5tLhseR:b-jbsf8z)*

**Comment by dsmilkov** [comment]
Review status: 0 of 17 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[.travis.yml, line 5 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/362#-KzLbhYHuElo4y1ooQkX:-KzQif9g9tmeH8SN_n7t:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/19764ffb596c9011bdb0ac85fa06d4e8871f6383/.travis.yml#L5)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

What do you think of writing a simple script that does recursively looks at models / start subdirectories? that way every time we add new stuff we don't have to add it here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/362)*

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Reviewed 17 of 17 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[scripts/build_and_lint_all, line 34 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/362#-KzQit1FDNk1oRVCvGv4:-KzQit1GCPbl-7ClNixu:b2nh75k) ([raw file](https://github.com/pair-code/deeplearnjs/blob/c11e2ea9c3ec737e013ed9d7da7d5507de90292d/scripts/build_and_lint_all#L34)):*
> ```
>     if (fs.statSync(childPath).isDirectory()) {
>       filelist = getPackageDirs(childPath, filelist);
>     } else if (file == 'package.json') {
> ```

===

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/362#-:-KzQj9pDegKfRhKyq5Od:b-jbsf8z)*

**Comment by dsmilkov** [comment]
Review status: 16 of 17 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[scripts/build_and_lint_all, line 34 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/362#-KzQit1FDNk1oRVCvGv4:-KzRDkYRY3fPl2A-dtcN:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/c11e2ea9c3ec737e013ed9d7da7d5507de90292d/scripts/build_and_lint_all#L34)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

===
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/362)*

**Pull request merged**
