### PR TITLE
Fix a bug in the tape backprop logic where we error on irrelevant ops missing gradients

### PR DESCRIPTION
**Pull request by dsmilkov**
If user calls `dl.grad(a => {f1(a); return f2(a)});`, we shouldn't error if `f1` is missing gradients since `f1` is irrelevant for the result for which we compute gradients.

In order to decide which ops are relevant, regardless of whether they are missing gradients logic, we need to make `TapeNode.inputs` a required field, so we can always backtrack through the computation and find relevant inputs.

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/772)

### CODE REVIEW

**Comment by dsmilkov** [comment]
Review status: 0 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/engine.ts, line 421 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/772#-L6-y_2VnHQmH5Oq3lTR:-L6-y_2VnHQmH5Oq3lTS:bgbjzkm) ([raw file](https://github.com/pair-code/deeplearnjs/blob/1f6e7f0b16fbf4f92d63fb459ad540a9ce9e6d3c/src/engine.ts#L421)):*
> ```XML
> }
> 
> export type ScopeAny = void|Tensor|string|number|boolean|ScopeObject|ScopeArray;
> ```

this is just a move from tape.ts since it has nothing to do with tape (it's all tidy/scope logic)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/772)*

**Comment by dsmilkov** [comment]
Review status: 0 of 19 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/engine_test.ts, line 533 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/772#-L6-yoGCUsflvg3TGxJe:-L6-yoGCUsflvg3TGxJf:b6iz3vi) ([raw file](https://github.com/pair-code/deeplearnjs/blob/1f6e7f0b16fbf4f92d63fb459ad540a9ce9e6d3c/src/engine_test.ts#L533)):*
> ```XML
> });
> 
> describeWithFlags('extractTensorsFromScopeResult', CPU_ENVS, () => {
> ```

moved these tests from tape_test.ts since they are irrelevant to the tape logic

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/772)*

**Comment by caisq** [comment]
LGTM

---

Review status: 0 of 19 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/772#-:-L622SgFpsZiSc1P2wqo:bb6ywmx)*

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: 0 of 19 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/772#-:-L626gKI5pt_iGwCyfhj:b-jbsf8z)*

**Pull request merged**
