### PR TITLE
add adamax optimizer

### PR DESCRIPTION
**Pull request by frqc**
use relu to do the "larger than" trick, which could be done in a more elegant way

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/192)

### CODE REVIEW

**Comment by frqc** [comment]
Signed google cla

**Comment by nsthorat** [comment]
Thanks for the contribution, the implementation looks correct.

Couple comments, and then I will merge :)

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/graph/optimizers/adamax_optimizer.ts, line 32 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/192#-Kw5gl95xGeGdal2KKoo:-Kw5gl95xGeGdal2KKop:bx4xwi7) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d01629beb30106ade320d8f2af681ed7086b080/src/graph/optimizers/adamax_optimizer.ts#L32)):*
> ```XML
>       specifiedVariableList?: Node[]) {
>     super(learningRate, specifiedVariableList);
>     this.eps = Scalar.new(1e-8);
> ```

this is unused

---

*[src/graph/optimizers/adamax_optimizer.ts, line 77 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/192#-Kw5hHwZfxYMuRFIJEkB:-Kw5hHwZfxYMuRFIJEkC:b-k341vb) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d01629beb30106ade320d8f2af681ed7086b080/src/graph/optimizers/adamax_optimizer.ts#L77)):*
> ```XML
>         const ut1 = math.abs(gradient);
> 
>         const newWeightedInfNorm = math.add(
> ```

can you just add a TODO here saying that we should update this to use an element-wise max?

---

*[src/graph/optimizers/adamax_optimizer.ts, line 89 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/192#-Kw5hMlsfbuSF6YwfS7t:-Kw5hMlsfbuSF6YwfS7u:b-42uyl) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d01629beb30106ade320d8f2af681ed7086b080/src/graph/optimizers/adamax_optimizer.ts#L89)):*
> ```XML
>         this.firstMoment.set(node.output, keep(newFirstMoment));
>         this.weightedInfNorm.set(node.output, keep(newWeightedInfNorm));
>         
> ```

remove all the spaces on this line

---

*[src/graph/optimizers/adamax_optimizer.ts, line 90 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/192#-Kw5hQgwGkfiMGs59uuP:-Kw5hQgwGkfiMGs59uuQ:bmisapu) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d01629beb30106ade320d8f2af681ed7086b080/src/graph/optimizers/adamax_optimizer.ts#L90)):*
> ```XML
>         this.weightedInfNorm.set(node.output, keep(newWeightedInfNorm));
>         
>         ut0.dispose();
> ```

no need to dispose ut0, ut1, scope will take care of that (outputs of math operations will get cleaned up, the rest has to be disposed since it's part of the tensor array map).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/192#-:-Kw5ie9yWGp_Iw6WPiKh:b2mee4p)*

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/192#-:-KwG3aVZ-flQjVMlmuNo:b-jbsf8z)*

**Comment by nsthorat** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/192)*

**Pull request merged**
