### PR TITLE
Move pad1D/pad2D to array_ops & global namespace.

### PR DESCRIPTION
**Pull request by nkreeger**
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/587)

### CODE REVIEW

**Comment by nsthorat** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/math/array_ops.ts, line 149 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/587#-L3iQhH_0q4kyPcK-Msx:-L3iQhH_0q4kyPcK-Msy:bosewx4) ([raw file](https://github.com/pair-code/deeplearnjs/blob/3e76719a315746d66fbd32093e575594fbe6988e/src/math/array_ops.ts#L149)):*
> ```XML
>    */
>   @operation
>   static pad1D(x: Array1D, paddings: [number, number], constantValue = 0):
> ```

let's put these in a "pad.ts" file alone (this file is for construction of ndarrays)

when you do move this, please add a generic "pad" like we do here: https://github.com/PAIR-code/deeplearnjs/blob/master/src/math/batchnorm.ts#L172

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/587)*

**Comment by nkreeger** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/math/array_ops.ts, line 149 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/587#-L3iQhH_0q4kyPcK-Msx:-L3isfsfkD0mA9SMJcSM:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/3e76719a315746d66fbd32093e575594fbe6988e/src/math/array_ops.ts#L149)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

let's put these in a "pad.ts" file alone (this file is for construction of ndarrays)

when you do move this, please add a generic "pad" like we do here: https://github.com/PAIR-code/deeplearnjs/blob/master/src/math/batchnorm.ts#L172
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/587)*

**Comment by nkreeger** [comment]
Updated now that https://github.com/PAIR-code/deeplearnjs/pull/590 has landed - PTAL.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/587#-:-L3nK2By85WmsGYwU9F_:bdcbhqw)*

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/math/array_ops.ts, line 149 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/587#-L3iQhH_0q4kyPcK-Msx:-L3nKIcMjcmCfoq_UPDT:b-64euok) ([raw file](https://github.com/pair-code/deeplearnjs/blob/3e76719a315746d66fbd32093e575594fbe6988e/src/math/array_ops.ts#L149)):*
<details><summary><i>Previously, nkreeger (Nick Kreeger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Awesome! Can you add the generic pad method?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/587#-:-L3nKQ0Vjzfuh50WYp3t:b-jbsf8z)*

**Pull request merged**
