### PR TITLE
Comparison Operator: Adds math.less method 

### PR DESCRIPTION
**Pull request by ManrajGrover**
This PR adds less operator for NDArrays which can be used as `math.less(a, b)`.

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/554)

### CODE REVIEW

**Comment by nkreeger** [comment]
Thanks for the PR! I think this PR is hanging CI. I'm going to close it - @ManrajGrover can you please re-open to see if it fixes the Travis issue? Might help running the tests locally to make sure nothing hangs on your end first.

**Comment by ManrajGrover** [comment]
Hi @nkreeger,  looks like travis is facing issues on their end and it has nothing to do with changes made in this PR. [Source](https://www.traviscistatus.com)

**Comment by nkreeger** [comment]
@ManrajGrover yeah thanks I found that later today :-) Re-opening and I'll take a look soon.

**Comment by nkreeger** [comment]
Another nice PR! Looks good to me - over to @dsmilkov for LGTM.

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/math/compareop_test.ts, line 641 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/554#-L31X_yqTBfKAY21jVQT:-L31X_yqTBfKAY21jVQU:b-em9n5x) ([raw file](https://github.com/pair-code/deeplearnjs/blob/2ac88c8411eaf397922009521b61af2bec5181c2/src/math/compareop_test.ts#L641)):*
>  'float32'
FYI - NDArray subclasses default to `float32` when `dtype` is not provided.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/554#-:-L31Y8OhpOyfbgPI_TXK:b-aa8g4w)*

**Comment by dsmilkov** [comment]
:lgtm_strong: Great! Thanks!

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/554#-:-L36EfHVenixQ6C5Ce00:bwvkoqn)*

**Pull request merged**
