### PR TITLE
Add math.flatten

### PR DESCRIPTION
**Pull request by dnnsthnnr**
Adds sugar method flatten #223

This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/229)

### CODE REVIEW

**Comment by nsthorat** [comment]
Thanks for the contribution! Just one comment

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/math/math.ts, line 378 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/229#-Kwkw7I4gC0Te2-XUMDS:-Kwkw7I4gC0Te2-XUMDT:b-hrcny2) ([raw file](https://github.com/pair-code/deeplearnjs/blob/43bde577e74801d7fee3fff91870b014ef96dd8b/src/math/math.ts#L378)):*
> ```XML
>    * @returns {Array1D}
>    */
>   flatten<T1 extends NDArray>(ndarray: T1): Array1D {
> ```

this should actually live on NDArray, where reshape lives as well, then the test should be in ndarray_test

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/229#-:-KwkwAFSmOXbgqpShLmy:b-5zyvns)*

**Comment by dnnsthnnr** [comment]
Wasn't sure, but makes sense. Will change it.

**Comment by dnnsthnnr** [comment]
@nsthorat while changing i found that flatten is exactly the same as the existing method NDArray.as1D().
This makes a flatten method redundant, or is it all about the naming?

**Comment by nsthorat** [comment]
Ahh, looks like you are right.

Adding another method `flatten` to `NDArray` which just calls as1D() is all we need! Sorry about that. If you add that method I'll merge it in.

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/229#-:-Kwp-d1Ib6KVJVvtIGm0:b-jbsf8z)*

**Pull request merged**
