### PR TITLE
Add concat*D ops

### PR DESCRIPTION
**Pull request by Lewuathe**
- [x] : Add concat1d, concat2d, concat4d ops in graph as well as concat3d
- [x] : Add backprop to concat operations

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/386)

### CODE REVIEW

**Comment by nsthorat** [comment]
Hey Kai,

Thanks for putting this together. We're going to moving to eager in the next 2 months, so most of the forward mode pieces of the `Graph` are going to just go away. What do you think about writing the backwards portion of the concats? They should simply be slices. Those will be the pieces of this we'll be able to carry over to the new system.

We're going to have a detailed outline in an issue once we finalize our internal design doc.

**Comment by Lewuathe** [comment]
@nsthorat Thanks for the information. Then I'll stop adding these ops in Graph. Instead I'll try to add some backward calculations to `Concat*D` operations.

**Comment by Lewuathe** [comment]
@nsthorat Can you take a look when you get a chance? Or should it be pending until eager mode implementation?

**Comment by nsthorat** [comment]
Hi sorry! Was waiting for a comment to know when this was ready, apologies.

One comment for you

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/graph/ops/concat.ts, line 143 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/386#-L0eEHilXIxHW9OnDfs1:-L0eEHilXIxHW9OnDfs2:bvcy6mi) ([raw file](https://github.com/pair-code/deeplearnjs/blob/0c53ba4f63a7251dd93f92219a2899735a8b9f3a/src/graph/ops/concat.ts#L143)):*
> ```XML
> 
>     math.scope((keep) => {
>       const slice1Result = math.slice3D(dy, x1Begin, x1Size);
> ```

I think this doesn't quite work out in the case where axis = 2. Try this example:

const a = Array3D.new([2, 2, 2], [0, 1, 2, 3, 4, 5, 6, 7]);
const b = Array3D.new([2, 2, 2], [10, 11, 12, 13, 14, 15, 16, 17]);

const r = math.concat3D(a, b, 2);

You will get this result:

0,1,10,11,2,3,12,13,4,5,14,15,6,7,16,17

Now, if you backprop, you cant just slice (this is a special case).

This is the same for Concat4D

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/386#-:-L0eGCqzm8cjcIx2EdXv:bx9q6ap)*

**Comment by Lewuathe** [comment]
I'm so sorry. I should have commented when it was ready...

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/graph/ops/concat.ts, line 143 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/386#-L0eEHilXIxHW9OnDfs1:-L0muO4YuTnqfomNPW4X:b-ewavyo) ([raw file](https://github.com/pair-code/deeplearnjs/blob/0c53ba4f63a7251dd93f92219a2899735a8b9f3a/src/graph/ops/concat.ts#L143)):*
> 0,1,10,11,2,3,12,13,4,5,14,15,6,7,16,17

Is this result incorrect? It looks correct to me.

a[0][0][0] = 0
a[0][0][1] = 1

b[0][0][0] = 10
b[0][0][0] = 11

So the result should be:

r[0][0][0] = 0
r[0][0][1] = 1
r[0][0][2] = 10
r[0][0][3] = 11

Anyway let me check backprop result again.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/386#-:-L0mtVVm4gzWHeaDnvvz:bdiv19y)*

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/graph/ops/concat.ts, line 42 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/386#-L0uT4jL7mYE7uou4Fcu:-L0uT4jL7mYE7uou4Fcv:bvkjjqe) ([raw file](https://github.com/pair-code/deeplearnjs/blob/0c53ba4f63a7251dd93f92219a2899735a8b9f3a/src/graph/ops/concat.ts#L42)):*
> ```XML
> 
>   feedForward(math: NDArrayMath, inferecenArrays: TensorArrayMap) {
>     const x1 = inferecenArrays.get(this.x1Tensor) as Array1D;
> ```

"inference"

---

*[src/graph/ops/concat.ts, line 143 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/386#-L0eEHilXIxHW9OnDfs1:-L0uSBc4x0A2kKZLd9yx:bf6ks3) ([raw file](https://github.com/pair-code/deeplearnjs/blob/0c53ba4f63a7251dd93f92219a2899735a8b9f3a/src/graph/ops/concat.ts#L143)):*
<details><summary><i>Previously, Lewuathe (Kai Sasaki) wrote…</i></summary><blockquote>

> 0,1,10,11,2,3,12,13,4,5,14,15,6,7,16,17

Is this result incorrect? It looks correct to me.

a[0][0][0] = 0
a[0][0][1] = 1

b[0][0][0] = 10
b[0][0][0] = 11

So the result should be:

r[0][0][0] = 0
r[0][0][1] = 1
r[0][0][2] = 10
r[0][0][3] = 11

Anyway let me check backprop result again.

</blockquote></details>

Ah, apologies. You are totally right.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/386#-:-L0uTZWoqGaMv-hRwaB7:b-jbsf8z)*

**Comment by nsthorat** [comment]
Ah, just need to resolve operation_emitter and then I will merge.

**Comment by Lewuathe** [comment]
@nsthorat I updated to resolve conflict. Could you take a look again?

**Comment by nsthorat** [comment]
Yarn seems to be down right now, I'm waiting for that to come back up so we can make sure the build passes before merging this PR!

**Comment by Lewuathe** [comment]
@nsthorat Thank you!

**Pull request merged**
