### PR TITLE
Add LSTM ops and a simple LSTM demo

### PR DESCRIPTION
**Pull request by cghawthorne**
Adds ports of tf.contrib.rnn.BasicLSTMCell and tf.contrib.rnn.MultiRNNCell.

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/47)

### CODE REVIEW

**Comment by dsmilkov** [comment]
So cool to see this PR! We use Reviewable for this project which is similar to Gerrit and the internal Google tool. Let me know if you have any questions about Reviewable! Most comments are just style/API goodies. The only bigger question is about the API regarding the input data type of the math lstm methods.

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---

*[demos/lstm/index.html, line 4 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-Krb57bxMMDUaBNz4w7R:-Krb57bxMMDUaBNz4w7S:b-xksbqb) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/demos/lstm/index.html#L4)):*
> ```HTML
> <head>
>   <title>LSTM Demo</title>
>   <script src="bundle.js"></script>
> ```

move this <script> tag at the end of the body after `<div id="success">`

We follow this practice as a precaution to avoid situations where the code uses elements in the dom that are not yet rendered.

---

*[demos/lstm/lstm.ts, line 67 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrbEvRSXjo2zt-lZ-ir:-KrbEvRSXjo2zt-lZ-is:b-3b30hc) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/demos/lstm/lstm.ts#L67)):*
> ```XML
>       const weightedResult1D = math.reshape(
>           weightedResult, [fullyConnectedBiases.shape[0]]) as Array1D;
>       const logits = math.add(
> ```

we added support for broadcasting in #40.  `math.add(weightedResult, fullyConnectedBiases)` should work

---

*[demos/lstm/lstm.ts, line 85 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrbTM4QpyOtaVKnwO3D:-KrbTM4RWTu6zyI50GCt:b9dg69w) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/demos/lstm/lstm.ts#L85)):*
> ```XML
> });
> 
> function checkArrays(expected: number[], results: number[]) {
> ```

`import {util} from '../deeplearnjs'` and use `util.arraysEqual(a, b)`

---

*[demos/lstm/README.md, line 1 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-Krb6Uu1c1bfnN58ceWg:-Krb6Uu1c1bfnN58ceWh:b6nh2zk) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/demos/lstm/README.md#L1)):*
> LSTM Demo

How about a title like "Learning digits of pi using an LSTM"

---

*[demos/lstm/README.md, line 6 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-Krb5uCkLHEozlQrQcZE:-Krb5uCkLHEozlQrQcZF:bfw9aex) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/demos/lstm/README.md#L6)):*
> BasicLSTMCells

s/BasicLSTMCells/`BasicLSTMCell`s . Same for MultiRNNCell (wrap in ``)

---

*[demos/lstm/README.md, line 7 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-Krb6H9jvKXpFOQ6q9i3:-Krb6H9jvKXpFOQ6q9i4:b-cwi081) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/demos/lstm/README.md#L7)):*
> the

s/the/to

---

*[demos/lstm/README.md, line 15 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-Krb6O-VyfxUVo6AnP0k:-Krb6O-VyfxUVo6AnP0l:b-9tl8hy) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/demos/lstm/README.md#L15)):*
> .

s/.:/:

---

*[src/math/math.ts, line 1148 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrbCpWOmupeeDVvKSxm:-KrbCpWOmupeeDVvKSxn:bpm1d6p) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/src/math/math.ts#L1148)):*
> ```XML
>    * @param c Array of previous cell states.
>    * @param h Array of previous cell outputs.
>    */
> ```

add `@return Tuple [nextCellStates, cellOutputs]` Our doc generator thanks you!

---

*[src/math/math.ts, line 1150 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrbVMBZmy77lOpEX0WG:-KrbVMBZmy77lOpEX0WH:b3gq9m1) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/src/math/math.ts#L1150)):*
> ```XML
>    */
>   multiRNNCell(lstmCells: LSTMCell[], data: Array1D, c: Array2D[],
>       h: Array2D[]): Array2D[][] {
> ```

Since it's always a tuple of 2 you can type the returning result as:
`: [Array2D[], Array2D[]] {`

---

*[src/math/math.ts, line 1151 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrbD1qzCrkF2nLDmK6M:-KrbD1qzCrkF2nLDmK6N:b-alur0f) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/src/math/math.ts#L1151)):*
> keep, track

FYI, you can just say this.scope(() => {..} if you don't use keep and track

---

*[src/math/math.ts, line 1158 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrbDPgR0KzV2S2CJPPO:-KrbDPgR0KzV2S2CJPPP:bun6pc9) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/src/math/math.ts#L1158)):*
> this.reshape(output[1], [output[1].shape[1]]) as Array1D;

use `input = output[1].as1D()` here and elsewhere. `Math.reshape()` is going away - see other comment about reshape.

---

*[src/math/math.ts, line 1180 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrbUPgZCjpoAJxDRMt2:-KrbUPgZCjpoAJxDRMt3:bjc4wn2) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/src/math/math.ts#L1180)):*
> ```XML
>    * @param data The input to the cell.
>    * @param c Previous cell state.
>    * @param h Previous cell output.
> ```

add `@return Tuple [nextState, output]` to be used in the next iteration.

---

*[src/math/math.ts, line 1183 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrbFm9mZUkhgcYSGFjk:-KrbFm9mZUkhgcYSGFjl:bagsow6) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/src/math/math.ts#L1183)):*
> Array2D[]

if the result is always of length 2, you can type it more strictly:
`: [Array2D, Array2D] {`

Also, is the cell/hidden state `Array2D` because of batching? In that case, maybe change input data to `Array2D` as well, here and in MultiRNNCell. And throw an Error inside if batch size is > 1 for now, saying batch sizes > 1 are not yet supported.

---

*[src/math/math.ts, line 1189 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrbEDYcW_cP5Wf7fm6C:-KrbEDYdntmsLiIpNDZ0:b7vbs3b) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/src/math/math.ts#L1189)):*
> this.reshape

use data.as3D(1, 1, data.shape[0]) here and elsewhere (as2D, as1D etc) where you call this.reshape(). You don't need `Math.reshape`, which does physical texture reshaping and is going away since we are moving our shaders to logical sampling. `asXD()` methods use `NDArray.reshape()`, which does logical reshape and is practically free.

---

*[src/math/math.ts, line 1201 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-Krb7wEMzCYIi-V1a2nQ:-Krb7wEMzCYIi-V1a2nR:b-mb79cb) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/src/math/math.ts#L1201)):*
>       const weighted1D = this.reshape(weighted, [lstmBias.shape[0]]) as Array1D;
>       const res1D = this.add(weighted1D, lstmBias);

We added broadcasting in #40 so `this.add(weighted, lstmBias)` should work now!

---

*[src/math/math.ts, line 1215 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrbSfrl6jnmeoGLpYQQ:-KrbSfrl6jnmeoGLpYQR:b-lfk53h) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/src/math/math.ts#L1215)):*
> this.elementWiseMul

sorry API's is evolving while you are writing this demo :) we deprecated this method. Use `math.multiply(a, b)` (which supports broadcasting), or `math.multiplyStrict(a, b)`which makes sure `a` and `b` are of the same shape and doesn't do broadcasting.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-:-KrbVs111z_XHcxDDlO9:bnu7o79)*

**Comment by nsthorat** [comment]
I have only minor nits, Daniel covered all the non-trivial stuff! This is /so/ awesome, thank you for contributing to src/ and being the first major external contributor! :)

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 24 unresolved discussions, some commit checks failed.

---

*[demos/lstm/index.html, line 1 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrcPKl48md6WkXtnLua:-KrcPKl48md6WkXtnLub:b-be1g4g) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/demos/lstm/index.html#L1)):*
> ```HTML
> <html>
> ```

Add the HTML license docstring (check out demos/mnist.html)

---

*[demos/lstm/lstm.ts, line 1 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrcRH5VLmORIHZxVkyr:-KrcRH5VLmORIHZxVkys:b-z4q2fd) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/demos/lstm/lstm.ts#L1)):*
> ```XML
> /* Copyright 2017 Google Inc. All Rights Reserved.
> ```

can we maybe call this lstm_inference.ts so that it's clear this doesn't do any training?

---

*[demos/lstm/lstm.ts, line 39 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrcPVSN5fzm0-ysYHcC:-KrcPVSN5fzm0-ysYHcD:bfclfcd) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/demos/lstm/lstm.ts#L39)):*
> ```XML
>   const fullyConnectedWeights = vars['fully_connected/weights'] as Array2D;
> 
>   const results:number[] = [];
> ```

space before number[]

---

*[demos/lstm/lstm.ts, line 54 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrcPfOqn8NNxjmdDwMS:-KrcPfOqn8NNxjmdDwMT:b-vj9brc) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/demos/lstm/lstm.ts#L54)):*
> ```XML
> 
>     let input = primerData;
>     for (let i = 0; i <  expected.length; i++) {
> ```

remove extra space before expected

---

*[src/math/math.ts, line 1143 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrcQCUbGQMiVx2OSQ8d:-KrcQCUbGQMiVx2OSQ8e:b-ec47hr) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/src/math/math.ts#L1143)):*
> ```XML
>    * Computes the next states and outputs of a stack of LSTMCells.
>    * Each cell output is used as input to the next cell.
>    * Derived from tf.contrib.rn.MultiRNNCell.
> ```

can you say in the docstring here that this is only the forward mode?

---

*[src/math/math.ts, line 1163 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrcQM-AuVHLqKM7izsP:-KrcQM-AuVHLqKM7izsQ:brqspz0) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/src/math/math.ts#L1163)):*
> ```XML
>       return newStates;
>     });
>     const newC:Array2D[] = [];
> ```

Add space before "Array2D[]" and below

---

*[src/math/math.ts, line 1173 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrcQf9r7xxFtlVd-AuQ:-KrcQf9r7xxFtlVd-AuR:bp3q88d) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/src/math/math.ts#L1173)):*
> ```XML
> 
>   /**
>    * Computes the next state and output of a BasicLSTMCell.
> ```

add to docstring saying this is only forward mode

---

*[src/math/math.ts, line 1198 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrcQxEYj6-etWvl6Dgn:-KrcQxEYj6-etWvl6Dgo:bajn7f) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/src/math/math.ts#L1198)):*
> ```XML
> 
>       // tf.nn.bias_add(weighted, lstmBias)
>       // There is no broadcast add, but we can assume a batch size of 1,
> ```

just a reminder to update this comment when you do the broadcast add :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-:-KrcRONjimu0dMHZDRY9:bj7uv7d)*

**Comment by cghawthorne** [comment]
Review status: 8 of 13 files reviewed at latest revision, 24 unresolved discussions.

---

*[demos/lstm/index.html, line 1 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrcPKl48md6WkXtnLua:-Krg8KQ4_c5T2X3h61EK:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/demos/lstm/index.html#L1)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

Add the HTML license docstring (check out demos/mnist.html)
</blockquote></details>

Done.

---

*[demos/lstm/index.html, line 4 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-Krb57bxMMDUaBNz4w7R:-Krg8PyvSuN-wkajHyC9:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/demos/lstm/index.html#L4)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

move this <script> tag at the end of the body after `<div id="success">`

We follow this practice as a precaution to avoid situations where the code uses elements in the dom that are not yet rendered.
</blockquote></details>

Done.

---

*[demos/lstm/README.md, line 1 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-Krb6Uu1c1bfnN58ceWg:-KrgKBPz8xM0J-Pev6gu:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/demos/lstm/README.md#L1)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

> LSTM Demo

How about a title like "Learning digits of pi using an LSTM"
</blockquote></details>

Done.

---

*[demos/lstm/README.md, line 6 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-Krb5uCkLHEozlQrQcZE:-Krg9VKWtLAaSGqUqSBv:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/demos/lstm/README.md#L6)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

> BasicLSTMCells

s/BasicLSTMCells/`BasicLSTMCell`s . Same for MultiRNNCell (wrap in ``)
</blockquote></details>

Done.

---

*[demos/lstm/README.md, line 7 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-Krb6H9jvKXpFOQ6q9i3:-Krg9XoyrCMqrXUKDYyP:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/demos/lstm/README.md#L7)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

> the

s/the/to
</blockquote></details>

Done.

---

*[demos/lstm/README.md, line 15 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-Krb6O-VyfxUVo6AnP0k:-Krg9aeNXz1mDG9wxciY:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/demos/lstm/README.md#L15)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

> .

s/.:/:
</blockquote></details>

Done.

---

*[src/math/math.ts, line 1143 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrcQCUbGQMiVx2OSQ8d:-KrgA-qEbzD6bbdHVp-P:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/src/math/math.ts#L1143)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

can you say in the docstring here that this is only the forward mode?
</blockquote></details>

Done.

---

*[src/math/math.ts, line 1148 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrbCpWOmupeeDVvKSxm:-KrgADTfjuSGAXp3G4Aq:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/src/math/math.ts#L1148)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

add `@return Tuple [nextCellStates, cellOutputs]` Our doc generator thanks you!
</blockquote></details>

Done.

---

*[src/math/math.ts, line 1150 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrbVMBZmy77lOpEX0WG:-KrgAK3fRqgO0B0EtwXF:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/src/math/math.ts#L1150)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

Since it's always a tuple of 2 you can type the returning result as:
`: [Array2D[], Array2D[]] {`
</blockquote></details>

Done.

---

*[src/math/math.ts, line 1151 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrbD1qzCrkF2nLDmK6M:-KrgAT6WxBy6btcY8vF5:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/src/math/math.ts#L1151)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

> keep, track

FYI, you can just say this.scope(() => {..} if you don't use keep and track
</blockquote></details>

Done.

---

*[src/math/math.ts, line 1158 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrbDPgR0KzV2S2CJPPO:-KrgAfzRMr4Z9ce0sHnz:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/src/math/math.ts#L1158)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

> this.reshape(output[1], [output[1].shape[1]]) as Array1D;

use `input = output[1].as1D()` here and elsewhere. `Math.reshape()` is going away - see other comment about reshape.
</blockquote></details>

Done.

---

*[src/math/math.ts, line 1163 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrcQM-AuVHLqKM7izsP:-KrgAmfn-_vUuOcKJzib:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/src/math/math.ts#L1163)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

Add space before "Array2D[]" and below
</blockquote></details>

Done.

---

*[src/math/math.ts, line 1173 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrcQf9r7xxFtlVd-AuQ:-KrgAnaZglA160OtPF8W:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/src/math/math.ts#L1173)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

add to docstring saying this is only forward mode
</blockquote></details>

Done.

---

*[src/math/math.ts, line 1180 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrbUPgZCjpoAJxDRMt2:-KrgAtOVPOb5bcadU4SV:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/src/math/math.ts#L1180)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

add `@return Tuple [nextState, output]` to be used in the next iteration.
</blockquote></details>

Done.

---

*[src/math/math.ts, line 1183 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrbFm9mZUkhgcYSGFjk:-KrgFLEvvwTrV6SsI0th:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/src/math/math.ts#L1183)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

> Array2D[]

if the result is always of length 2, you can type it more strictly:
`: [Array2D, Array2D] {`

Also, is the cell/hidden state `Array2D` because of batching? In that case, maybe change input data to `Array2D` as well, here and in MultiRNNCell. And throw an Error inside if batch size is > 1 for now, saying batch sizes > 1 are not yet supported.
</blockquote></details>

Done.

---

*[src/math/math.ts, line 1189 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrbEDYcW_cP5Wf7fm6C:-KrgCreUAO2KL7jdS4fE:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/src/math/math.ts#L1189)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

> this.reshape

use data.as3D(1, 1, data.shape[0]) here and elsewhere (as2D, as1D etc) where you call this.reshape(). You don't need `Math.reshape`, which does physical texture reshaping and is going away since we are moving our shaders to logical sampling. `asXD()` methods use `NDArray.reshape()`, which does logical reshape and is practically free.
</blockquote></details>

Done.

---

*[src/math/math.ts, line 1198 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrcQxEYj6-etWvl6Dgn:-KrgCrJg5Kmfj7qllkil:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/src/math/math.ts#L1198)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

just a reminder to update this comment when you do the broadcast add :)
</blockquote></details>

Done.

---

*[src/math/math.ts, line 1201 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-Krb7wEMzCYIi-V1a2nQ:-KrgCvjcb--8MJ7qWsSS:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/src/math/math.ts#L1201)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

>       const weighted1D = this.reshape(weighted, [lstmBias.shape[0]]) as Array1D;
>       const res1D = this.add(weighted1D, lstmBias);

We added broadcasting in #40 so `this.add(weighted, lstmBias)` should work now!
</blockquote></details>

Done.

---

*[src/math/math.ts, line 1215 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrbSfrl6jnmeoGLpYQQ:-KrgDqDS2QHhwA67OnyV:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/src/math/math.ts#L1215)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

> this.elementWiseMul

sorry API's is evolving while you are writing this demo :) we deprecated this method. Use `math.multiply(a, b)` (which supports broadcasting), or `math.multiplyStrict(a, b)`which makes sure `a` and `b` are of the same shape and doesn't do broadcasting.
</blockquote></details>

Done.

---

*[demos/lstm/lstm.ts, line 1 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrcRH5VLmORIHZxVkyr:-Krg8j2WKhpEg9QKp6hK:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/demos/lstm/lstm.ts#L1)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

can we maybe call this lstm_inference.ts so that it's clear this doesn't do any training?
</blockquote></details>

Done.

---

*[demos/lstm/lstm.ts, line 39 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrcPVSN5fzm0-ysYHcC:-Krg8pShn-TCzjILfaEB:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/demos/lstm/lstm.ts#L39)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

space before number[]
</blockquote></details>

Done.

---

*[demos/lstm/lstm.ts, line 54 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrcPfOqn8NNxjmdDwMS:-Krg8tGb626G0_BTDjXC:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/demos/lstm/lstm.ts#L54)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

remove extra space before expected
</blockquote></details>

Done.

---

*[demos/lstm/lstm.ts, line 67 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrbEvRSXjo2zt-lZ-ir:-Krg92hTpeaifyBxi-J5:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/demos/lstm/lstm.ts#L67)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

we added support for broadcasting in #40.  `math.add(weightedResult, fullyConnectedBiases)` should work
</blockquote></details>

Done.

---

*[demos/lstm/lstm.ts, line 85 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-KrbTM4QpyOtaVKnwO3D:-Krg9FkArmdSaAkgXyeT:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/265635e2ea41edaa792ca8de2b4f169408251733/demos/lstm/lstm.ts#L85)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

`import {util} from '../deeplearnjs'` and use `util.arraysEqual(a, b)`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47)*

**Comment by cghawthorne** [comment]
Thanks for the review! I think I've got everything fixed up based on your comments.

---

Review status: 8 of 13 files reviewed at latest revision, 24 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-:-KrgKcr9yItYc4xnfjaJ:b-q5r6pq)*

**Comment by dsmilkov** [comment]
:lgtm_strong:  Thank you for the amazing contribution! We've learned a lot along the process regarding our API, such as the need for broadcasting support, adding concat1D/2D(), removing/deprecating math.reshape() etc.

If you have any other feedback of how the API can be simplified, or what it needs, would love to hear it!

---

Review status: 8 of 13 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/47#-:-KrgMEXWqmP0yq0p0MsM:b-hhcz6g)*

**Pull request merged**
