### PR TITLE
Add Adadelta and Adam to model-builder

### PR DESCRIPTION
**Pull request by Lewuathe**
Added two optimizers in model-builder.

- Adam
- Adadelta

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/209)

### CODE REVIEW

**Comment by nsthorat** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[demos/model-builder/model-builder.html, line 253 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/209#-KwG54dEQdJbrJPyTV8G:-KwG54dEQdJbrJPyTV8H:bipncj3) ([raw file](https://github.com/pair-code/deeplearnjs/blob/62273bb63c0989a1d3806c8f6433ecf4426172f3/demos/model-builder/model-builder.html#L253)):*
> ```HTML
>       </paper-input>
> 
>       <paper-input no-animations label="Beta1" id="beta1" disabled="[[!needBeta1]]" value={{beta1}}>
> ```

while you're here, would you mind changing disabled to hidden? As we add more hyperparameters, we're showing the union at all times, which takes up quite a bit of room. I think hiding them would be better.

https://deeplearnjs.org/demos/model-builder/

---

*[demos/model-builder/model-builder.ts, line 25 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/209#-KwG4z_6Ba6Nw_gH13N7:-KwG4z_6Ba6Nw_gH13N8:bun72y7) ([raw file](https://github.com/pair-code/deeplearnjs/blob/62273bb63c0989a1d3806c8f6433ecf4426172f3/demos/model-builder/model-builder.ts#L25)):*
> ```XML
> 
> // tslint:disable-next-line:max-line-length
> import {Array1D, Array3D, DataStats, FeedEntry, Graph, GraphRunner, GraphRunnerEventObserver, InCPUMemoryShuffledInputProviderBuilder, InMemoryDataset, MetricReduction, MomentumOptimizer, SGDOptimizer, RMSPropOptimizer, AdagradOptimizer, AdadeltaOptimizer, AdamOptimizer, NDArray, NDArrayMath, NDArrayMathCPU, NDArrayMathGPU, Optimizer, Scalar, Session, Tensor, util, xhr_dataset, XhrDataset, XhrDatasetConfig} from '../deeplearn';
> ```

we just added adadelta too, can you add that here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/209)*

**Comment by Lewuathe** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[demos/model-builder/model-builder.html, line 253 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/209#-KwG54dEQdJbrJPyTV8G:-KwHrlMqo0b9aEy9Y_ux:b-ioreru) ([raw file](https://github.com/pair-code/deeplearnjs/blob/62273bb63c0989a1d3806c8f6433ecf4426172f3/demos/model-builder/model-builder.html#L253)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

while you're here, would you mind changing disabled to hidden? As we add more hyperparameters, we're showing the union at all times, which takes up quite a bit of room. I think hiding them would be better.

https://deeplearnjs.org/demos/model-builder/
</blockquote></details>

Okay, I'll try to make it hidden.

---

*[demos/model-builder/model-builder.ts, line 25 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/209#-KwG4z_6Ba6Nw_gH13N7:-KwHrrCElHW3jNknIJ_U:b-8s6j9p) ([raw file](https://github.com/pair-code/deeplearnjs/blob/62273bb63c0989a1d3806c8f6433ecf4426172f3/demos/model-builder/model-builder.ts#L25)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

we just added adadelta too, can you add that here?
</blockquote></details>

Hmm, I added AdadeltaOptimizer too. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/209)*

**Comment by nsthorat** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[demos/model-builder/model-builder.html, line 253 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/209#-KwG54dEQdJbrJPyTV8G:-KwLVoTlTasDSmfu5Aky:b-fghfic) ([raw file](https://github.com/pair-code/deeplearnjs/blob/62273bb63c0989a1d3806c8f6433ecf4426172f3/demos/model-builder/model-builder.html#L253)):*
<details><summary><i>Previously, Lewuathe (Kai Sasaki) wrote…</i></summary><blockquote>

Okay, I'll try to make it hidden.
</blockquote></details>

You should just be able to use the magic "hidden" attribute

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/209)*

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/209#-:-KwWJh3tXW6WEq4N-_BW:b-jbsf8z)*

**Comment by nsthorat** [comment]
Update this branch and then I will merge it in!

**Pull request merged**
