### PR TITLE
Clean up: Merge separate test files to respective sources

### PR DESCRIPTION
**Pull request by ManrajGrover**
This PR cleans up code and merges separate test files to respective sources.

* Moves `math.tile` tests to `array_ops_tests`
* Moves `math.gather` tests to `array_ops_tests`
* Moves `math.clip` tests to `unary_ops_tests`
* Moves `math.oneHot` tests to `array_ops_tests`

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/618)

### CODE REVIEW

**Comment by nsthorat** [comment]
This looks great! One minor comment.

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/math/array_ops_test.ts, line 1400 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/618#-L4BbGSpKymG6bl-x0_t:-L4BbGSqvtJ7IfvBD9yD:b-wq0f8b) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6ce93af8b90afcfbb553f4ebd797c4379592bb58/src/math/array_ops_test.ts#L1400)):*
> ```XML
> ];
> 
> test_util.describeMathCPU('array_ops', allTests);
> ```

I just saw this, can we add a bunch of these calls to test_util so we can prefix each of the individual calls (I want to see array_ops.tile)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/618#-:-L4BesAwNjGqGjSF9jGC:b-96louh)*

**Comment by ManrajGrover** [comment]
@nsthorat I'm sorry I didn't get the comment. I would need more information on the change to be made

**Comment by ManrajGrover** [comment]
@nsthorat I've broken the test file and now each operation can be tested individually. Please let me know if I understood your comment correctly.

**Comment by nsthorat** [comment]
Nice work! Can you update the branch and I'll merge?

:lgtm_strong:

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/618#-:-L4N1hH3w1fMcLbGp8jh:bhbhr8p)*

**Comment by nsthorat** [comment]
Nevermind, it's updated :)

**Pull request merged**
