### PR TITLE
Logical Operators: Add math.logicalNot operation

### PR DESCRIPTION
**Pull request by ManrajGrover**
This PR adds logicalNot operator for NDArrays which can be used as `math.logicalNot(a)`.

@dsmilkov I need some inputs on this. Since this method will take a single input, should I make use of `UnaryInputConfig` and `UnaryNode` or make one for `LogicalUnaryNode`?

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/563)

### CODE REVIEW

**Comment by nsthorat** [comment]
@ManrajGrover let me know when this is updated and ready, sorry about the delay.

**Comment by ManrajGrover** [comment]
@nsthorat I actually needed some inputs here. Since this method will take a single input, should I make use of UnaryInputConfig and UnaryNode or make one for LogicalUnaryNode?

**Comment by nsthorat** [comment]
You can just use UnaryNode for this, even though it won't live in unary_ops.

**Comment by ManrajGrover** [comment]
@nsthorat Ready for review

**Comment by nsthorat** [comment]
Awesome work! Few comments inline.

---

Review status: 0 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/math/logical_ops.ts, line 28 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/563#-L4N-3Vbx9M7ulLK1IcY:-L4N-3Vbx9M7ulLK1IcZ:b-5en5uc) ([raw file](https://github.com/pair-code/deeplearnjs/blob/81d5c5f718cb886ea5eb8a4306b334c3ba6674a1/src/math/logical_ops.ts#L28)):*
> ```XML
> export class Ops {
>   /**
>    * Returns the truth value of NOT a element-wise.
> ```

remove "a"

---

*[src/math/logical_ops.ts, line 30 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/563#-L4N-1QcaoicPe3gZM04:-L4N-1QcaoicPe3gZM05:b-sjr4yn) ([raw file](https://github.com/pair-code/deeplearnjs/blob/81d5c5f718cb886ea5eb8a4306b334c3ba6674a1/src/math/logical_ops.ts#L30)):*
> ```XML
>    * Returns the truth value of NOT a element-wise.
>    *
>    * @param a x The input NDArray.
> ```

s/a x/x

---

*[src/math/logical_ops.ts, line 33 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/563#-L4N-R2rOf7E6UTpg3En:-L4N-R2rOf7E6UTpg3Eo:bjjz7f5) ([raw file](https://github.com/pair-code/deeplearnjs/blob/81d5c5f718cb886ea5eb8a4306b334c3ba6674a1/src/math/logical_ops.ts#L33)):*
> ```XML
>    */
>   @operation
>   static logicalNot<T extends NDArray>(x: T): T {
> ```

question: since I came to the logical stuff a little late (daniel has been reviewing), what happens if the dtype passed is not boolean?

---

*[src/math/unary_ops_test.ts, line 1279 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/563#-L4N-9kM4bxHMB9hPscQ:-L4N-9kM4bxHMB9hPscR:b5b2rn2) ([raw file](https://github.com/pair-code/deeplearnjs/blob/81d5c5f718cb886ea5eb8a4306b334c3ba6674a1/src/math/unary_ops_test.ts#L1279)):*
> ```XML
> }
> 
> // LogicalNot:
> ```

can you move this to logical_ops_test?

---

*[src/math/unary_ops_test.ts, line 1284 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/563#-L4N-DwI2kh5IIWM5jkc:-L4N-DwI2kh5IIWM5jkd:b-ecskt1) ([raw file](https://github.com/pair-code/deeplearnjs/blob/81d5c5f718cb886ea5eb8a4306b334c3ba6674a1/src/math/unary_ops_test.ts#L1284)):*
> ```XML
> 
>   const tests: MathTests = it => {
>     // Array1D:
> ```

remove these comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/563#-:-L4N-bBMmvMM2giRSfTO:b-6bcun1)*

**Comment by ManrajGrover** [comment]
@nsthorat 
>remove "a"

Done

> s/a x/x

Done

> question: since I came to the logical stuff a little late (daniel has been reviewing), what happens if the dtype passed is not boolean?

We've been throwing an error for this. I've added the assert statement for logicalNot as well.

> can you move this to logical_ops_test?

Done

> remove these comment

Done

**Comment by dsmilkov** [comment]
:lgtm_strong:

---

Reviewed 7 of 10 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/pair-code/deeplearnjs/563#-:-L4WkPGa4A4fWs6e67K1:b-jbsf8z)*

**Pull request merged**
