### PR TITLE
Add unit tests for NDArray.randNormal().

### PR DESCRIPTION
**Pull request by nkreeger**
Here is another upgrade to the NDArray unit test suite. I introduced some basic 95%-probability checking for normality using the Jarque-Bera normality test. There are some magic numbers, but they should be documented and essentially point to critical values of chi-squared: https://www.uam.es/personal_pdi/ciencias/anabz/Prest/Trabajos/Critical_Values_of_the_Chi-Squared_Distribution.pdf

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/347)

### CODE REVIEW

**Comment by dsmilkov** [comment]
:lgtm_strong: Nice work on the statistical tests

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/347#-:-Kyv1jFmKu0nfktjrHFN:b-dqd16d)*

**Comment by dsmilkov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/math/ndarray_test.ts, line 268 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/347#-Kyv2KE0VbeJbfgbaAY8:-Kyv2KE0VbeJbfgbaAY9:bo2pw9j) ([raw file](https://github.com/pair-code/deeplearnjs/blob/76f0c35079243bb30548a02b68fe50ea3f5a3db7/src/math/ndarray_test.ts#L268)):*
> ```XML
>     gpgpu.uploadMatrixToTexture(texture, 1, 3, new Float32Array([10, 7, 3]));
> 
>     const f = () => { return Array1D.make([3], {texture}); };
> ```

since these lines were touched in this PR, the tslint started to fail (see log [here](https://travis-ci.org/PAIR-code/deeplearnjs/builds/301787229#L1031))

these tests were written when the linter was less strict. it basically it wants a shorter syntax:

const f = () => Array1D.make([3], {texture});

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/347)*

**Comment by nkreeger** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[src/math/ndarray_test.ts, line 268 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/347#-Kyv2KE0VbeJbfgbaAY8:-KyvDmup8UQq1-_oZ4uI:b-fm66w7) ([raw file](https://github.com/pair-code/deeplearnjs/blob/76f0c35079243bb30548a02b68fe50ea3f5a3db7/src/math/ndarray_test.ts#L268)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

since these lines were touched in this PR, the tslint started to fail (see log [here](https://travis-ci.org/PAIR-code/deeplearnjs/builds/301787229#L1031))

these tests were written when the linter was less strict. it basically it wants a shorter syntax:

const f = () => Array1D.make([3], {texture});


</blockquote></details>

Cool - I re-formatted the file so lint now passes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/347)*

**Comment by nkreeger** [comment]
Seems like a false report on the Google bot?

**Comment by dsmilkov** [comment]
Yeah, ignore those messages. It's because when your branch gets out-of-date with the master branch, I get a button on github to sync it up to date without conflicts. I use this button since it's much faster and I don't have to go back and forth with the PR author to sync his/her branch. Clicking that button results in github sending a merge commit from my username, at which point the PR has commits from multiple users, at which point the google bots sends a false alarm :)

branch

**Comment by dsmilkov** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/347)*

**Pull request merged**
