### PR TITLE
Add API for getting library version

### PR DESCRIPTION
**Pull request by Lewuathe**
see: https://github.com/PAIR-code/deeplearnjs/issues/211

## Usage

```
import {version} from 'deeplearn';

console.log(version);
```

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/212)

### CODE REVIEW

**Comment by nsthorat** [comment]
Thank you!!

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/version_test.ts, line 20 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/212#-KwLW9WgB_N65j1yXc4x:-KwLW9WgB_N65j1yXc4y:b-ubv9px) ([raw file](https://github.com/pair-code/deeplearnjs/blob/fa56aab47eae244f1109934d1ffb632b728c6002/src/version_test.ts#L20)):*
> ```XML
> import {version} from './index';
> 
> describe('check', () => {
> ```

can you call this "version" in the describe

---

*[src/version_test.ts, line 22 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/212#-KwLWBbnct8qP2vfvLx6:-KwLWBboXNCWsrqh2znJ:b5378nq) ([raw file](https://github.com/pair-code/deeplearnjs/blob/fa56aab47eae244f1109934d1ffb632b728c6002/src/version_test.ts#L22)):*
> ```XML
> describe('check', () => {
>   it('version is contained', () => {
>   // tslint:disable-next-line:no-require-imports
> ```

indent this 2 more

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/212#-:-KwLW86WPopxM6xt8zNi:b-10zgjg)*

**Comment by dsmilkov** [comment]
Great! Can you check if the version is available when you produce a standalone bundle, by running `./scripts/build-standalone.sh` and importing it via a script tag in a simple html page?

**Comment by Lewuathe** [comment]
The version could be read as expected.

```html
<html>
  <script type="text/javascript" src="dist/deeplearn.js"></script>
  <body>
    <p>deeplearnjs version: <div id="version"></div></p>
  </body>

  <script type"text/javascript">
    console.log(deeplearn.version);
    var v = document.getElementById("version");
    v.innerHTML = deeplearn.version;
  </script>	
</html>
```

screen shot 2017-10-14 at 10 42 34

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/212#-:-KwWK6nGHd5QHqrB7CkY:b-jbsf8z)*

**Comment by nsthorat** [comment]
Update the branch and I will merge this in!

**Pull request merged**
