### PR TITLE
Add PReLU

### PR DESCRIPTION
**Pull request by wang2bo2**
See: #223

* Added PReLU activation function taking an array of alphas as parameter
* Added PReLU node and graph method taking a tensor of alphas as input
* Added new tests

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/453)

### CODE REVIEW

**Comment by wang2bo2** [comment]
I signed it!

**Comment by nsthorat** [comment]
Thanks for this awesome contribution!

High level questions:
1) I realize that we do the same thing for leakyrelu, but I think we can express this as a combination of other ops (we're going to try to reduce the number of kernels and do as much in the higher level methods as possible). Would you be up for that (basically, you wouldn't have the kernel method on backend.ts, NDArrayMath would just call other NDArrayMath methods).
2) What's the motivation for this change? Just getting familiar with the codebase or is there something you're going to use this for?

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/453#-:-L0W5MWFeLdcoqzsxAZr:b-al1x36)*

**Comment by wang2bo2** [comment]
Hi @nsthorat,

Thanks for checking it out. High level answers:

1. I thought about that at the beginning but still picked the current setup, because PReLU is quite different from LeakyReLU in 2 ways:
a) The alpha in LeakyReLU is a hyper-parameter (an arg), while the alphas in PReLU is a trainable parameter (an input like `bias` in `conv2d`). This difference suggests the op to be binary instead of unary.
b) PReLU could have different alphas for different channels, while LeakyReLU just have one alpha for all.

2. Some CNNs I'd like to use adopted it. More discussions could be found in [1], which proposed PReLU (1782 citations to date).

[1]: He K, Zhang X, Ren S, Sun J. Delving deep into rectifiers: Surpassing human-level performance on imagenet classification. InProceedings of the IEEE international conference on computer vision 2015 (pp. 1026-1034).

**Comment by nsthorat** [comment]
Really nice job with this PR! You followed our conventions quite nicely :)

Few minor comments and I will merge.

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/graph/ops/element_wise_activation.ts, line 148 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/453#-L0e7Xcnu-5GiBiFJabz:-L0e7Xcnu-5GiBiFJac-:b-c8znys) ([raw file](https://github.com/pair-code/deeplearnjs/blob/3d05a0d61962da9743488050692d6cca2c052711/src/graph/ops/element_wise_activation.ts#L148)):*
> ```XML
>       const dydx = math.pReluDer(x, alpha);
>       gradientArrays.add(this.xTensor, math.elementWiseMul(dy, dydx));
>       dydx.dispose();
> ```

you dont need this dispose since you're in a math.scope()

---

*[src/graph/ops/element_wise_activation.ts, line 151 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/453#-L0e7RRe-_6G7sZ0WVsv:-L0e7RRe-_6G7sZ0WVsw:b5gjf8j) ([raw file](https://github.com/pair-code/deeplearnjs/blob/3d05a0d61962da9743488050692d6cca2c052711/src/graph/ops/element_wise_activation.ts#L151)):*
> ```XML
>     });
>   }
> ```

remove this blank line.

---

*[src/math/binaryop_test.ts, line 53 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/453#-L0e8Cm12uvUmwaexaNU:-L0e8Cm12uvUmwaexaNV:b-9p9rz4) ([raw file](https://github.com/pair-code/deeplearnjs/blob/3d05a0d61962da9743488050692d6cca2c052711/src/math/binaryop_test.ts#L53)):*
> ```XML
>     {'WEBGL_FLOAT_TEXTURE_ENABLED': false, 'WEBGL_VERSION': 1}
>   ]);
> }
> ```

can you add some unit tests for the derivative here?

---

*[src/math/math.ts, line 1265 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/453#-L0e7KOCe3etk6vGrcSv:-L0e7KOCe3etk6vGrcSw:b-yc820f) ([raw file](https://github.com/pair-code/deeplearnjs/blob/3d05a0d61962da9743488050692d6cca2c052711/src/math/math.ts#L1265)):*
> ```XML
>    * @return {NDArray}
>    */
>   pRelu<T extends NDArray>(x: T, alpha: T): T {
> ```

can we call this prelu? We can always alias later, but for now let's go lower case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/453#-:-L0e8Kws2gwCd9ChtXqi:bxoiiw4)*

**Comment by wang2bo2** [comment]
Thanks :) I have added fixes and new tests, please have a look.

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: 3 of 13 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/453#-:-L0lmsGXFSuedGTVY_0o:b-jbsf8z)*

**Pull request merged**
