### PR TITLE
RMSProp: Adds RMSProp Optimizer with eager

### PR DESCRIPTION
**Pull request by ManrajGrover**
This PR adds RMSProp Optimizer with eager mode

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/687)

### CODE REVIEW

**Comment by ManrajGrover** [comment]
@nsthorat Please do double check the implementation here, especially for graph

**Comment by nsthorat** [comment]
Awesome change! Can you also update model-builder.ts and make sure this works, e.g. you learn with rmsprop in MNIST?

---

Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/math/optimizers/optimizer_constructors.ts, line 66 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/687#-L54skLvCiyefWJK7vXk:-L54skLvCiyefWJK7vXl:bvbfxwv) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6ff209c70ddab8b2508846bd62ddd72cfac898de/src/math/optimizers/optimizer_constructors.ts#L66)):*
> ```XML
>   @doc({heading: 'Training', subheading: 'Optimizers', namespace: 'train'})
>   static rmsprop(
>       learningRate: number, rho = .9, momentum = 0.0, epsilon = 1e-8):
> ```

let's call rho "decay" to mirror TF

---

*[src/math/optimizers/rmsprop_optimizer.ts, line 43 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/687#-L54srnJ3TIO9BlCKcLQ:-L54srnJ3TIO9BlCKcLR:b-32mhst) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6ff209c70ddab8b2508846bd62ddd72cfac898de/src/math/optimizers/rmsprop_optimizer.ts#L43)):*
> ```XML
> 
>   constructor(
>       protected learningRate: number, rho = 0.9, momentum = 0.0,
> ```

s/rho/decay

---

*[src/math/optimizers/rmsprop_optimizer.ts, line 51 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/687#-L54suBgvX_O44pqiKna:-L54suBgvX_O44pqiKnb:bwf1fiv) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6ff209c70ddab8b2508846bd62ddd72cfac898de/src/math/optimizers/rmsprop_optimizer.ts#L51)):*
> ```XML
>     this.epsilon = keep(scalar(epsilon));
>     this.rho = keep(scalar(rho));
>     this.m = keep(scalar(momentum));
> ```

s/this.m/this.momentum

---

*[src/math/optimizers/rmsprop_optimizer.ts, line 81 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/687#-L54vPfxHEuLKUbWf2qn:-L54vPfxHEuLKUbWf2qo:b-iai66b) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6ff209c70ddab8b2508846bd62ddd72cfac898de/src/math/optimizers/rmsprop_optimizer.ts#L81)):*
> ```XML
>             this.m.mul(accumulatedMoments)
>                 .add(this.c.mul(gradient).div(
>                     newAccumulatedMeanSquare.add(this.epsilon).sqrt()));
> ```

qq, do we need to subtract off mean_grad^2 in the denominator here?

https://github.com/tensorflow/tensorflow/blob/r1.5/tensorflow/python/training/rmsprop.py#L37

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/687#-:-L54vaNlrkedXucB7gY_:b2tq8zj)*

**Comment by ManrajGrover** [comment]
@nsthorat Actually, I've implemented [plain momentum version of RMSProp](https://github.com/tensorflow/tensorflow/blob/r1.5/tensorflow/python/training/rmsprop.py#L20). The tensorflow source contains both plain as well as the centered version of RMSProp. I couldn't find a good reference for centered version hence didn't implement it.

Making rest of the changes

**Comment by nsthorat** [comment]
Awesome, could you document that at the top-level call sight, the static "rmsprop" method?

**Comment by ManrajGrover** [comment]
@nsthorat Made the required changes

**Comment by nsthorat** [comment]
And just to confirm - model builder learns MNIST with RMSProp?

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/687#-:-L55KpuI-utqi1JNq3De:b-jbsf8z)*

**Comment by nsthorat** [comment]
Also, update the branch then I will merge!

**Comment by ManrajGrover** [comment]
@nsthorat Yeps, it was working

**Comment by ManrajGrover** [comment]
Adding a screenshot here
screen shot 2018-02-12 at 1 17 23 am

**Pull request merged**
