### PR TITLE
Add code snippets to jsdocs.

### PR DESCRIPTION
**Pull request by nsthorat**
* Add lots of code snippets.
* Remove dotProduct from docs and exports.
* Remove vectorTimesMatrix and matrixTimesVector from docs.
* Remove argMaxEquals from dl.* and docs. This now only lives on math for backwards compatibility.
* Adds norm on chain API.
* Chain API clip => clipByValue

This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/725)

### CODE REVIEW

**Comment by tafsiri** [comment]
Review status: 0 of 23 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[website/scripts/api-parser.ts, line 67 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/725#-L5PJPFinzwtqed1jZ26:-L5PJPFinzwtqed1jZ27:bbgxsea) ([raw file](https://github.com/pair-code/deeplearnjs/blob/8cd7f00b814f6c8669111df0f15a0b6ca7c1a84e/website/scripts/api-parser.ts#L67)):*
> ```XML
>           name: 'Classes',
>           description: `<p>
>           This section shows the common deeplearn.js classes and the methods
> ```

How about something like (its a small change)

"This section shows the main Tensor related classes in deeplearn.js classes and the methods we expose on them."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/725)*

**Comment by nsthorat** [comment]
Review status: 0 of 26 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[website/scripts/api-parser.ts, line 67 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/725#-L5PJPFinzwtqed1jZ26:-L5Pk2ZGZi_GmSDSoUJ8:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/8cd7f00b814f6c8669111df0f15a0b6ca7c1a84e/website/scripts/api-parser.ts#L67)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

How about something like (its a small change)

"This section shows the main Tensor related classes in deeplearn.js classes and the methods we expose on them."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/725)*

**Comment by ManrajGrover** [comment]
@nsthorat Looks like the build process here is stuck. https://travis-ci.org/PAIR-code/deeplearnjs/builds/341998019

**Comment by nsthorat** [comment]
Eek, I can't even kick it..

**Comment by ManrajGrover** [comment]
@nsthorat Can you try restarting the build?

**Comment by dsmilkov** [comment]
:lgtm_strong:

---

Reviewed 18 of 23 files at r1, 5 of 6 files at r2, 3 of 3 files at r4, 1 of 1 files at r5.
Review status: 23 of 26 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/725#-:-L5QGpu2QfTiq8ORcRXe:b-jbsf8z)*

**Pull request merged**
