### PR TITLE
Improves documentation 

### PR DESCRIPTION
**Pull request by ManrajGrover**
This PR fills in and fixes minor things in documentation

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/743)

### CODE REVIEW

**Comment by nsthorat** [comment]
Thanks for taking this pass, this is much better! Few small comments and then I will merge.

---

Review status: 0 of 9 files reviewed at latest revision, 20 unresolved discussions, some commit checks failed.

---

*[src/tensor.ts, line 333 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/743#-L5eSUYiLDCAwZlsNxkx:-L5eSUYiLDCAwZlsNxky:bm826p) ([raw file](https://github.com/pair-code/deeplearnjs/blob/2361efa4bc39bc7ef94759a83d6f229c29d79566/src/tensor.ts#L333)):*
> ```XML
>    * Casts a `Tensor` to a specified dtype.
>    *
>    * @param dtype Typecode or data-type to which the array is cast.
> ```

Let's just say "Data-type to cast the tensor to."

---

*[src/tensor.ts, line 437 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/743#-L5eSZz8pQBgZg7ScojM:-L5eSZz8pQBgZg7ScojN:b-ampbfo) ([raw file](https://github.com/pair-code/deeplearnjs/blob/2361efa4bc39bc7ef94759a83d6f229c29d79566/src/tensor.ts#L437)):*
> ```XML
> 
>   /**
>    * Disposes the `Tensor` from the memory.
> ```

remove "the"

---

*[src/tensor.ts, line 474 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/743#-L5eSrPnpN7JIAcxq31f:-L5eSrPnpN7JIAcxq31g:b6pfmzh) ([raw file](https://github.com/pair-code/deeplearnjs/blob/2361efa4bc39bc7ef94759a83d6f229c29d79566/src/tensor.ts#L474)):*
> ```XML
> 
>   /**
>    * Prints the tensor. See `print` for details.
> ```

Use back ticks and upper case Tensor

---

*[src/tensor.ts, line 476 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/743#-L5eSpsBXNugS-t9lBkc:-L5eSpsBXNugS-t9lBkd:b-d2pl3s) ([raw file](https://github.com/pair-code/deeplearnjs/blob/2361efa4bc39bc7ef94759a83d6f229c29d79566/src/tensor.ts#L476)):*
> ```XML
>    * Prints the tensor. See `print` for details.
>    *
>    * @param verbose Whether to print verbose information about the Tensor,
> ```

lower case T

---

*[src/tensor.ts, line 477 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/743#-L5eSodj1L8x19VTbwIm:-L5eSodj1L8x19VTbwIn:b61ahg4) ([raw file](https://github.com/pair-code/deeplearnjs/blob/2361efa4bc39bc7ef94759a83d6f229c29d79566/src/tensor.ts#L477)):*
> ```XML
>    *
>    * @param verbose Whether to print verbose information about the Tensor,
>    * including dtype and size.
> ```

indent this 4 more

---

*[src/tensor.ts, line 512 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/743#-L5eSveYJoKuaVtA_O5d:-L5eSveZlq3yAf_7peOS:b-wzcb3v) ([raw file](https://github.com/pair-code/deeplearnjs/blob/2361efa4bc39bc7ef94759a83d6f229c29d79566/src/tensor.ts#L512)):*
> ```XML
>    *
>    * @param axis The dimension index at which to insert shape of 1. Defaults to
>    * 0 (the first dimension).
> ```

indent 4

---

*[src/tensor.ts, line 523 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/743#-L5eSz-AwJE00Ja497Kq:-L5eSz-AwJE00Ja497Kr:b-aza21q) ([raw file](https://github.com/pair-code/deeplearnjs/blob/2361efa4bc39bc7ef94759a83d6f229c29d79566/src/tensor.ts#L523)):*
> ```XML
>    * See `squeeze` for more details.
>    *
>    * @param axis An optional list of numbers. If specified, only squeezes the
> ```

remove "optional" - we parse this automaticaly

---

*[src/tensor.ts, line 524 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/743#-L5eSyI4HitlZaKu6gP9:-L5eSyI4HitlZaKu6gPA:b-s00smv) ([raw file](https://github.com/pair-code/deeplearnjs/blob/2361efa4bc39bc7ef94759a83d6f229c29d79566/src/tensor.ts#L524)):*
> ```XML
>    *
>    * @param axis An optional list of numbers. If specified, only squeezes the
>    * dimensions listed. The dimension index starts at 0. It is an error to
> ```

indent 4.

---

*[src/tensor.ts, line 1014 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/743#-L5eT1nGhEAARr7zrkr_:-L5eT1nGhEAARr7zrkra:b-ylzrn) ([raw file](https://github.com/pair-code/deeplearnjs/blob/2361efa4bc39bc7ef94759a83d6f229c29d79566/src/tensor.ts#L1014)):*
> ```XML
>    * ```
>    *
>    * @param initialValue Initial value for tensor.
> ```

the tensor

---

*[src/tensor.ts, line 1033 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/743#-L5eT2i85WZ79QgXf5fL:-L5eT2i85WZ79QgXf5fM:b-o3b0kg) ([raw file](https://github.com/pair-code/deeplearnjs/blob/2361efa4bc39bc7ef94759a83d6f229c29d79566/src/tensor.ts#L1033)):*
> ```XML
>    * same shape and dtype as the old `Tensor`.
>    *
>    * @param newValue New `Tensor` to be assigned to this variable.
> ```

remove backticks around tensor (in params we don't do this since we automatically parse the type).

---

*[src/ops/array_ops.ts, line 314 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/743#-L5eTBGuyS_N54p725MO:-L5eTBGuyS_N54p725MP:by72ind) ([raw file](https://github.com/pair-code/deeplearnjs/blob/2361efa4bc39bc7ef94759a83d6f229c29d79566/src/ops/array_ops.ts#L314)):*
> ```XML
>    * ```
>    *
>    * @param x The tensor of required shape.
> ```

Let's revert this, I think we explain it in the documentation above. WDYT?

---

*[src/ops/array_ops.ts, line 577 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/743#-L5eTxfUJYOPgyXVH_VZ:-L5eTxfUJYOPgyXVH_V_:bia6heb) ([raw file](https://github.com/pair-code/deeplearnjs/blob/2361efa4bc39bc7ef94759a83d6f229c29d79566/src/ops/array_ops.ts#L577)):*
> ```XML
>    * ```
>    *
>    * @param x The input tensor which needs to be reshaped.
> ```

remove "which needs"

---

*[src/ops/array_ops.ts, line 604 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/743#-L5eU-kRgHBaFmlX6lkr:-L5eU-kRgHBaFmlX6lks:bia6heb) ([raw file](https://github.com/pair-code/deeplearnjs/blob/2361efa4bc39bc7ef94759a83d6f229c29d79566/src/ops/array_ops.ts#L604)):*
> ```XML
>    * ```
>    *
>    * @param x The input tensor which needs to be squeezed.
> ```

remove "which needs"

---

*[src/ops/array_ops.ts, line 683 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/743#-L5eU3nuSlLzu9ViLNds:-L5eU3nuSlLzu9ViLNdt:b9ihysw) ([raw file](https://github.com/pair-code/deeplearnjs/blob/2361efa4bc39bc7ef94759a83d6f229c29d79566/src/ops/array_ops.ts#L683)):*
> ```XML
>    * x.gather(indices).print();
>    * ```
>    * @param x The input tensor whose slices need to be gathered.
> ```

remove "needs"

---

*[src/ops/array_ops.ts, line 821 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/743#-L5eU8Caa5k1fB-x32LQ:-L5eU8Caa5k1fB-x32LR:b9ihysw) ([raw file](https://github.com/pair-code/deeplearnjs/blob/2361efa4bc39bc7ef94759a83d6f229c29d79566/src/ops/array_ops.ts#L821)):*
> ```XML
>    * ```
>    *
>    * @param x The input tensor whose dimensions need to be expanded.
> ```

remove "needs"

---

*[src/ops/binary_ops.ts, line 251 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/743#-L5eUEHLF3HsiUfAneaq:-L5eUEHLF3HsiUfAnear:bpnfsz5) ([raw file](https://github.com/pair-code/deeplearnjs/blob/2361efa4bc39bc7ef94759a83d6f229c29d79566/src/ops/binary_ops.ts#L251)):*
> ```XML
>    * a.mul(b).print();  // or dl.mul(a, b)
>    * ```
>    * @param a The first tensor to multiply with.
> ```

remove "with"

---

*[src/ops/binary_ops.ts, line 288 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/743#-L5eUFdkNKDIr4TKgx_D:-L5eUFdkNKDIr4TKgx_E:b-gevxfl) ([raw file](https://github.com/pair-code/deeplearnjs/blob/2361efa4bc39bc7ef94759a83d6f229c29d79566/src/ops/binary_ops.ts#L288)):*
> ```XML
>    * Inputs must be the same shape. For broadcasting support, use mul().
>    *
>    * @param a The first Tensor to multiply element-wise.
> ```

lower case T

remove "element-wise"

---

*[src/ops/binary_ops.ts, line 319 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/743#-L5eUK12VkBkTLwyobuU:-L5eUK12VkBkTLwyobuV:b-jejnaf) ([raw file](https://github.com/pair-code/deeplearnjs/blob/2361efa4bc39bc7ef94759a83d6f229c29d79566/src/ops/binary_ops.ts#L319)):*
> ```XML
>    * ```
>    *
>    * @param a The first tensor as numerator.
> ```

"as the numerator"

---

*[src/ops/binary_ops.ts, line 320 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/743#-L5eULfz2TdZG1h5qeYH:-L5eULfz2TdZG1h5qeYI:b-ehq4hn) ([raw file](https://github.com/pair-code/deeplearnjs/blob/2361efa4bc39bc7ef94759a83d6f229c29d79566/src/ops/binary_ops.ts#L320)):*
> ```XML
>    *
>    * @param a The first tensor as numerator.
>    * @param b The second tensor as denominator. Must have the same dtype as `a`.
> ```

"as the denominator"

add "the" below as well

---

*[src/optimizers/optimizer_constructors.ts, line 133 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/743#-L5eUSPE_Fh5N1m0ajjt:-L5eUSPFVejBuTjh9E34:b2h8csf) ([raw file](https://github.com/pair-code/deeplearnjs/blob/2361efa4bc39bc7ef94759a83d6f229c29d79566/src/optimizers/optimizer_constructors.ts#L133)):*
> ```XML
>    * descent algorithm.
>    * @param rho The learning rate decay over each update.
>    * @param epsilon A constant epsilon used to better conditioning the grad
> ```

is this for better conditioning or just divide by zero?

either way, say "better condition"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/743#-:-L5eUYv3PXqZnHjPDBUR:bkeyrlw)*

**Comment by nsthorat** [comment]
One missed comment then I will merge it!

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/tensor.ts, line 437 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/743#-L5eSZz8pQBgZg7ScojM:-L5n_5EgbqXJ4kOnL2Br:b-cvmvv2) ([raw file](https://github.com/pair-code/deeplearnjs/blob/2361efa4bc39bc7ef94759a83d6f229c29d79566/src/tensor.ts#L437)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

remove "the"
</blockquote></details>

I still see "the"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/743#-:-L5n_L1fuNXq8HBfg2DX:b-413cbx)*

**Comment by ManrajGrover** [comment]
@nsthorat I've fixed it. https://github.com/PAIR-code/deeplearnjs/pull/743/files#diff-844f6ef91ec8e8738f7b59e1a4e7d615R437

Not sure why it has not been updated on Reviewable.

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/743#-:-L67NCAjCtc9D4bVKppi:b-jbsf8z)*

**Comment by tafsiri** [comment]
@nsthorat is this ready for merge?

**Pull request merged**
