### PR TITLE
Migrate more math ops

### PR DESCRIPTION
**Pull request by dsmilkov**
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/582)

### CODE REVIEW

**Comment by ManrajGrover** [comment]
@dsmilkov Just noticed this PR. Awesome job! :) Would you be adding gradients for unary operations mentioned in  #561 while migrating? I just started working on a few of them #583

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Reviewed 12 of 19 files at r1, 36 of 36 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/graph/operation_emitter.ts, line 75 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/582#-L3Zpg2HWSaNttmAdJDo:-L3Zpg2Jd17R2d9GHz7Z:b-aebk7c) ([raw file](https://github.com/pair-code/deeplearnjs/blob/5c57a3a008120abfe2a42505ba707dc97bf357d3/src/graph/operation_emitter.ts#L75)):*
> ```XML
>     return [new LeakyReLU(node.inputs[LeakyReLUNode.X], 
>       node.output, node.alpha)];
>   } else if (node instanceof PReLUNode) {
> ```

I'm a little confused why this is going away. I understand why the derivatives don't need to be exposed, but this breaks "g.prelu", etc.

---

*[src/math/array_ops.ts, line 25 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/582#-L3Zq-mrfziikUHJVEjC:-L3Zq-mrfziikUHJVEjD:b-oa7gga) ([raw file](https://github.com/pair-code/deeplearnjs/blob/331e324680d66b6c5831423c7546309e7521e2e1/src/math/array_ops.ts#L25)):*
> ```XML
> import {DataType, DataTypeMap, Rank, RankMap} from './types';
> 
> export class Ops {
> ```

unit tests for this file? seems like it makes sense to have this as array_ops_test

---

*[src/math/unary_ops.ts, line 197 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/582#-L3ZrM6_5hSL73c6uF7f:-L3ZrM6_5hSL73c6uF7g:bhp8n13) ([raw file](https://github.com/pair-code/deeplearnjs/blob/331e324680d66b6c5831423c7546309e7521e2e1/src/math/unary_ops.ts#L197)):*
> ```XML
>       return {
>         x: () => {
>           return ENV.engine.executeKernel('PReLUDer', {inputs: {x, alpha}}) as
> ```

you shouldn't be executing a kernel here, it should be an op. move preluDer back to a method that calls the kernel (if we ever add a second derivative it shouldn't live here for consistency).

Same thing above for elu

---

*[src/math/unary_ops_test.ts, line 750 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/582#-L3ZrbmQTanPRs4qKDrG:-L3ZrbmQTanPRs4qKDrH:b-xhgefo) ([raw file](https://github.com/pair-code/deeplearnjs/blob/331e324680d66b6c5831423c7546309e7521e2e1/src/math/unary_ops_test.ts#L750)):*
> ```XML
>     it('derivative', math => {
>       const x = Array1D.new([1, 3, -2]);
>       const dy = Array1D.new([1, 1, 1]);
> ```

can you give a non 1 valued dy so we can make sure the product works?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/582#-:-L3Zrnj7edqxCa7eWy4m:b-jbsf8z)*

**Comment by dsmilkov** [comment]
Reviewed 1 of 19 files at r1, 3 of 36 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[src/graph/operation_emitter.ts, line 75 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/582#-L3Zpg2HWSaNttmAdJDo:-L3_81B_6Y9t8D3DXyuC:b-whwz66) ([raw file](https://github.com/pair-code/deeplearnjs/blob/5c57a3a008120abfe2a42505ba707dc97bf357d3/src/graph/operation_emitter.ts#L75)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

I'm a little confused why this is going away. I understand why the derivatives don't need to be exposed, but this breaks "g.prelu", etc.
</blockquote></details>

Done. Reverted.

---

*[src/math/array_ops.ts, line 25 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/582#-L3Zq-mrfziikUHJVEjC:-L3aR7_h90Owd8edTYIW:b-hpfkj4) ([raw file](https://github.com/pair-code/deeplearnjs/blob/331e324680d66b6c5831423c7546309e7521e2e1/src/math/array_ops.ts#L25)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

unit tests for this file? seems like it makes sense to have this as array_ops_test
</blockquote></details>

Done. Moved tests from `ndarray_test.ts`

---

*[src/math/unary_ops.ts, line 197 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/582#-L3ZrM6_5hSL73c6uF7f:-L3aRvqFUXziopneXgPW:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/331e324680d66b6c5831423c7546309e7521e2e1/src/math/unary_ops.ts#L197)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

you shouldn't be executing a kernel here, it should be an op. move preluDer back to a method that calls the kernel (if we ever add a second derivative it shouldn't live here for consistency).

Same thing above for elu
</blockquote></details>

Done.

---

*[src/math/unary_ops_test.ts, line 750 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/582#-L3ZrbmQTanPRs4qKDrG:-L3aSEFoqngCTpjP2WMA:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/331e324680d66b6c5831423c7546309e7521e2e1/src/math/unary_ops_test.ts#L750)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

can you give a non 1 valued dy so we can make sure the product works?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/582)*

**Comment by dsmilkov** [comment]
@ManrajGrover We'll be working on adding gradients, but we'll focus on ones that are not unary or binary so we don't overlap. Reviewed your PRs - nice work!

**Pull request merged**
