### PR TITLE
Comparison Operator: Adds math.lessEqual method

### PR DESCRIPTION
**Pull request by ManrajGrover**
This PR adds less equal operator for NDArrays which can be used as `math.lessEqual(a, b)`.

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/548)

### CODE REVIEW

**Comment by nkreeger** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/math/compareop_test.ts, line 1042 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/548#-L31WUYMqa-8_0Y4Bj37:-L31WUYMqa-8_0Y4Bj38:b-2egho6) ([raw file](https://github.com/pair-code/deeplearnjs/blob/5fce4e4f6e0d60e8bc5a2b7ba727e91c9efa59ce/src/math/compareop_test.ts#L1042)):*
> let a =
>           Array2D.new([2, 3], [[1.1, 4.1, 5.1], [8.1, 9.1, 11.1]], 'float32');
>       let b =
>           Array2D.new([2, 3], [[2.1, 3.1, 6.1], [7.1, 10.1, 11.1]], 'float32');

Any reason you changed the `dtype` here? Same throughout this file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/548)*

**Comment by nkreeger** [comment]
Nice work! Looks mostly good to me - one comment about number dtype changing in a test. Over to @dsmilkov for LGTM/approval.

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/548#-:-L31WvTxXOsS1NdrWceT:b6ef682)*

**Comment by ManrajGrover** [comment]
@nkreeger It was because the values were floats whereas dtype was defined as integer.

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/math/compareop_test.ts, line 1042 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/548#-L31WUYMqa-8_0Y4Bj37:-L34Dw9YDZqX1K78KPXD:b-xxdv0a) ([raw file](https://github.com/pair-code/deeplearnjs/blob/7d40b709a3add4aced547c9d533dde43c1c60e22/src/math/compareop_test.ts#L1042)):*
<details><summary><i>Previously, nkreeger (Nick Kreeger) wrote…</i></summary><blockquote>

> let a =
>           Array2D.new([2, 3], [[1.1, 4.1, 5.1], [8.1, 9.1, 11.1]], 'float32');
>       let b =
>           Array2D.new([2, 3], [[2.1, 3.1, 6.1], [7.1, 10.1, 11.1]], 'float32');

Any reason you changed the `dtype` here? Same throughout this file.
</blockquote></details>

Looks like it was wrong before

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/548#-:-L34Ez03ZUSnli_iTWTC:b-jbsf8z)*

**Pull request merged**
