### PR TITLE
 Use IteratorResult<T> to cleanly indicate end of stream.

### PR DESCRIPTION
**Pull request by davidsoergel**
Noe this builds on #785.  I'm curious to see how GitHub & Reviewable handle this situation.  If it's not convenient, let's just wait on this PR until the other one is merged.

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/790)

### CODE REVIEW

**Comment by davidsoergel** [comment]
OK, it looks like I'm proposing to merge this into async-stream-gc, which makes no sense.  But after that PR is merged into master, I can redirect this one to diff against master instead, so it will all work out as far as GitHub is concerned.  Dunno about Reviewable though.

**Comment by dsmilkov** [comment]
Yeah, you might have to close this PR and start a new PR against master. Let me know when/if ready. Either way, I just took a look and this looks great - fixes bug & aligns with future standards - LGTM++

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/790#-:-L6cFY8BFXi9XN1PJefm:b-84dqqz)*

**Comment by davidsoergel** [comment]
Switching the base branch to master worked, so this PR is ready for review.  Thanks!

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/790#-:-L6do476OoM-szbRVHNa:b-spc3ya)*

**Comment by dsmilkov** [comment]
:lgtm_strong: Nice, this is a big step in the right direction. Left a few comments, unrelated to this change, but something we should address in future PRs.

---

Reviewed 3 of 12 files at r1, 7 of 9 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/contrib/data/dataset.ts, line 259 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/790#-L6gGxEBiDrAhg0_BZ_6:-L6gGxEBiDrAhg0_BZ_7:btiw9u1) ([raw file](https://github.com/pair-code/deeplearnjs/blob/978e3655631d6f81e74b027f88baeb1e566aee41/src/contrib/data/dataset.ts#L259)):*
> ```XML
>    * within that element are disposed.
>    *
>    * @param f A function to apply to each dataset element.
> ```

say it returns a promise that resolves when done iterating over all elements.

---

*[src/contrib/data/streams/data_stream.ts, line 278 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/790#-L6gI-BUDHduDY7LE9LE:-L6gI-BUDHduDY7LE9LF:b-ruycm8) ([raw file](https://github.com/pair-code/deeplearnjs/blob/978e3655631d6f81e74b027f88baeb1e566aee41/src/contrib/data/streams/data_stream.ts#L278)):*
> ```XML
>   }
> 
>   async next(): Promise<IteratorResult<T>> {
> ```

How about FunctionCallStream taking a user-provided function that returns what `next()` returns.

This way the user is in full control when to stop iterating.
```js
// f looks a lot like `async function* f() {...}`
const f = streamFromFunction(() => {
  const value = await someVal();
  const done = await checkIfDone();
  return {value, done};
});
```
Up to you if you want to do it here, or leave a TODO

---

*[src/contrib/data/streams/data_stream.ts, line 292 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/790#-L6gP-xHnhwXfENMPlzU:-L6gP-xI8sph4bACZv4_:br71oec) ([raw file](https://github.com/pair-code/deeplearnjs/blob/978e3655631d6f81e74b027f88baeb1e566aee41/src/contrib/data/streams/data_stream.ts#L292)):*
> ```XML
>   async next(): Promise<IteratorResult<T>> {
>     while (this.count++ < this.maxCount) {
>       const skipped = await this.upstream.next();
> ```

we should read maxCount elements in parallel.
```js
const reads = [];
while (cond) { reads.push(this.upstream.next()); }
const doneReads = await Promise.all(reads);
...
```
Up to you if in this PR, or add a TODO for later.

---

*[src/contrib/data/streams/data_stream.ts, line 353 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/790#-L6gTdWX9B3I8nn9SN5y:-L6gTdWX9B3I8nn9SN5z:bdh7uiw) ([raw file](https://github.com/pair-code/deeplearnjs/blob/978e3655631d6f81e74b027f88baeb1e566aee41/src/contrib/data/streams/data_stream.ts#L353)):*
> ```XML
>     // output queue, then this stream is also exhausted.
>     while (this.outputQueue.length() === 0) {
>       if (!await this.pump()) {
> ```

this looks like none of the QueueStream derivatives will be able to read in parallel. E.g. BatchedStream below. If that's the case, add a TODO to fix this.

---

*[src/contrib/data/streams/data_stream.ts, line 372 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/790#-L6gUSYbQw-dxN-Hf46L:-L6gUSYbQw-dxN-Hf46M:b-2a17sf) ([raw file](https://github.com/pair-code/deeplearnjs/blob/978e3655631d6f81e74b027f88baeb1e566aee41/src/contrib/data/streams/data_stream.ts#L372)):*
> ```XML
>   async pump(): Promise<boolean> {
>     const item = await this.upstream.next();
>     if (item.done) {
> ```

If you want to read a whole batch in parallel, can't check for item.done here. Have to do something like:
```js
const doneReads = await Promise.all(batchOfReads);
// deal with partial batch, since last K reads may have `done: true`
```
And rework logic in QueueStream, or remove QueueStream altogether. See previous comment.

---

*[src/contrib/data/streams/data_stream_test.ts, line 187 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/790#-L6gVnWmJCbrREcdWofx:-L6gVnWmJCbrREcdWofy:b-twyd9u) ([raw file](https://github.com/pair-code/deeplearnjs/blob/978e3655631d6f81e74b027f88baeb1e566aee41/src/contrib/data/streams/data_stream_test.ts#L187)):*
> ```XML
>     const func = () => ++i < 100 ? i : undefined;
> 
>     // streamFromFunction never ends, so we truncate it
> ```

see another comment above re: streamFromFunction

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/790#-:-L6gW2QZVbQdjn-In7Go:bo69gf6)*

**Comment by davidsoergel** [comment]
Review status: 7 of 12 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[src/contrib/data/dataset.ts, line 259 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/790#-L6gGxEBiDrAhg0_BZ_6:-L6jIqP955NGEteZcYU6:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/978e3655631d6f81e74b027f88baeb1e566aee41/src/contrib/data/dataset.ts#L259)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

say it returns a promise that resolves when done iterating over all elements.
</blockquote></details>

Done.

---

*[src/contrib/data/streams/data_stream.ts, line 278 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/790#-L6gI-BUDHduDY7LE9LE:-L6jJenNCca8ElJc_D1Z:b-yloqjq) ([raw file](https://github.com/pair-code/deeplearnjs/blob/978e3655631d6f81e74b027f88baeb1e566aee41/src/contrib/data/streams/data_stream.ts#L278)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

How about FunctionCallStream taking a user-provided function that returns what `next()` returns.

This way the user is in full control when to stop iterating.
```js
// f looks a lot like `async function* f() {...}`
const f = streamFromFunction(() => {
  const value = await someVal();
  const done = await checkIfDone();
  return {value, done};
});
```
Up to you if you want to do it here, or leave a TODO
</blockquote></details>

Good idea; done here.

---

*[src/contrib/data/streams/data_stream.ts, line 292 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/790#-L6gP-xHnhwXfENMPlzU:-L6jKeeQlJgMSdj_QsqS:b-ij4bds) ([raw file](https://github.com/pair-code/deeplearnjs/blob/978e3655631d6f81e74b027f88baeb1e566aee41/src/contrib/data/streams/data_stream.ts#L292)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

we should read maxCount elements in parallel.
```js
const reads = [];
while (cond) { reads.push(this.upstream.next()); }
const doneReads = await Promise.all(reads);
...
```
Up to you if in this PR, or add a TODO for later.
</blockquote></details>

This bears discussion.  Added TODO.

---

*[src/contrib/data/streams/data_stream.ts, line 353 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/790#-L6gTdWX9B3I8nn9SN5y:-L6jLQhtDXDjTKe9tQyp:bx87h2y) ([raw file](https://github.com/pair-code/deeplearnjs/blob/978e3655631d6f81e74b027f88baeb1e566aee41/src/contrib/data/streams/data_stream.ts#L353)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

this looks like none of the QueueStream derivatives will be able to read in parallel. E.g. BatchedStream below. If that's the case, add a TODO to fix this.
</blockquote></details>

I'm unclear that parallel reads would have much real benefit here.  In any case an imminent PR reduces the use of QueueStreams.  Left a TODO to discuss the remaining cases.

---

*[src/contrib/data/streams/data_stream.ts, line 372 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/790#-L6gUSYbQw-dxN-Hf46L:-L6jM2p7UMN07nGty1I8:b-dpac8s) ([raw file](https://github.com/pair-code/deeplearnjs/blob/978e3655631d6f81e74b027f88baeb1e566aee41/src/contrib/data/streams/data_stream.ts#L372)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

If you want to read a whole batch in parallel, can't check for item.done here. Have to do something like:
```js
const doneReads = await Promise.all(batchOfReads);
// deal with partial batch, since last K reads may have `done: true`
```
And rework logic in QueueStream, or remove QueueStream altogether. See previous comment.
</blockquote></details>

Fix already queued up in followup PR :)

---

*[src/contrib/data/streams/data_stream_test.ts, line 187 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/790#-L6gVnWmJCbrREcdWofx:-L6jMsSRpMihHY0Thlwb:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/978e3655631d6f81e74b027f88baeb1e566aee41/src/contrib/data/streams/data_stream_test.ts#L187)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

see another comment above re: streamFromFunction
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/790)*

**Comment by dsmilkov** [comment]
Review status: 7 of 12 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[src/contrib/data/streams/data_stream.ts, line 292 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/790#-L6gP-xHnhwXfENMPlzU:-L6ltUQSCQyeZdvp-GFA:b-tg12uu) ([raw file](https://github.com/pair-code/deeplearnjs/blob/978e3655631d6f81e74b027f88baeb1e566aee41/src/contrib/data/streams/data_stream.ts#L292)):*
<details><summary><i>Previously, davidsoergel (David Soergel) wrote…</i></summary><blockquote>

This bears discussion.  Added TODO.
</blockquote></details>

Nice. The todo you added makes a great point - and not a high priority for now.

---

*[src/contrib/data/streams/data_stream.ts, line 353 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/790#-L6gTdWX9B3I8nn9SN5y:-L6ltngzwQDL5dmATYEE:b-b19k33) ([raw file](https://github.com/pair-code/deeplearnjs/blob/978e3655631d6f81e74b027f88baeb1e566aee41/src/contrib/data/streams/data_stream.ts#L353)):*
<details><summary><i>Previously, davidsoergel (David Soergel) wrote…</i></summary><blockquote>

I'm unclear that parallel reads would have much real benefit here.  In any case an imminent PR reduces the use of QueueStreams.  Left a TODO to discuss the remaining cases.
</blockquote></details>

Good point. It's unclear. TODO is great for now. if we ever come into a real-world example being bottleneck-ed by this, we can tackle it then. Until then, the simplest thing that works is the best :)

---

*[src/contrib/data/streams/data_stream.ts, line 372 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/790#-L6gUSYbQw-dxN-Hf46L:-L6lu7Zgkj3-OG4ldpOC:btbpfy2) ([raw file](https://github.com/pair-code/deeplearnjs/blob/978e3655631d6f81e74b027f88baeb1e566aee41/src/contrib/data/streams/data_stream.ts#L372)):*
<details><summary><i>Previously, davidsoergel (David Soergel) wrote…</i></summary><blockquote>

Fix already queued up in followup PR :)
</blockquote></details>

Nice. Looking forward.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/790)*

**Pull request merged**
