### PR TITLE
Update new api docs design

### PR DESCRIPTION
**Pull request by tafsiri**
sync up work on this feature with @nsthorat. Not 'complete', but should be mergeable as we iterate.

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/685)

### CODE REVIEW

**Comment by tafsiri** [comment]
Tried out a new header style that focuses more on subheadings as the place to add context.

Looks like 

screen shot 2018-02-09 at 11 02 42 pm

**Comment by nsthorat** [comment]
:lgtm_strong:

Feel free to merge after making these changes. Nice work, this is coming along nicely!

---

Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[package.json, line 21 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/685#-L5-KHUWYhqA88DOAQ0x:-L5-KHUWYhqA88DOAQ0y:bkto40x) ([raw file](https://github.com/pair-code/deeplearnjs/blob/4af1181aeeb4b2b0effb6ffc3e7615e9bbb3544f/package.json#L21)):*
> ```JSON
>     "clang-format": "~1.2.2",
>     "cross-spawn": "~5.1.0",
>     "handlebars": "^4.0.11",
> ```

use ~ for consistency

---

*[website/api/index.html, line 313 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/685#-L5-KMdcEjmNvshdGv0C:-L5-KMddKyae0mkiKtow:bqx6ynr) ([raw file](https://github.com/pair-code/deeplearnjs/blob/4af1181aeeb4b2b0effb6ffc3e7615e9bbb3544f/website/api/index.html#L313)):*
> ```HTML
>       </div>
>       {{/headings}}
> ```

remove blank line

---

*[website/api/index.html, line 319 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/685#-L5-KLkrpJyf2Dh9_hd8:-L5-KLkrpJyf2Dh9_hd9:b-jdiskk) ([raw file](https://github.com/pair-code/deeplearnjs/blob/4af1181aeeb4b2b0effb6ffc3e7615e9bbb3544f/website/api/index.html#L319)):*
> ```HTML
> 
> </body>
> ```

remove training spaces

---

*[website/scripts/make-api.ts, line 50 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/685#-L5-KeNatbamfkojaiZa:-L5-KeNatbamfkojaiZb:b909uao) ([raw file](https://github.com/pair-code/deeplearnjs/blob/4af1181aeeb4b2b0effb6ffc3e7615e9bbb3544f/website/scripts/make-api.ts#L50)):*
> ```XML
> // Renders a string to markdown but removes the outer <p> tag
> HandleBars.registerHelper('markdownInner', function(attr) {
>   const asMd: string =
> ```

string should be inferred automatically

---

*[website/scripts/make-api.ts, line 51 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/685#-L5-KYoPaJUocDxmvT8n:-L5-KYoPaJUocDxmvT8o:b-uflc5l) ([raw file](https://github.com/pair-code/deeplearnjs/blob/4af1181aeeb4b2b0effb6ffc3e7615e9bbb3544f/website/scripts/make-api.ts#L51)):*
> ```XML
> HandleBars.registerHelper('markdownInner', function(attr) {
>   const asMd: string =
>       md.render(attr.trim()).replace(/<p>/, '').replace(/(<\/p>\s*)$/, '');
> ```

why replace <p> tags? Instead of doing this, can we simply style them the way you want with CSS?

---

*[website/scripts/make-api.ts, line 61 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/685#-L5-KSxj_Tcl-BSLvlBT:-L5-KSxj_Tcl-BSLvlBU:b-942xh2) ([raw file](https://github.com/pair-code/deeplearnjs/blob/4af1181aeeb4b2b0effb6ffc3e7615e9bbb3544f/website/scripts/make-api.ts#L61)):*
> ```XML
> 
> const html = HandleBars.compile(mustacheTemplate)(docs);
> // const html = mustache.render(mustacheTemplate, docs);
> ```

remove this and dep on mustaceh

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/685#-:-L5-Klz04adjTFhnPPNz:b-y4ftwc)*

**Comment by dsmilkov** [comment]
:lgtm_strong: Very cool. Left one small comment.

---

Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[website/api/index.html, line 18 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/685#-L5-nNmc-APsOQZBIUBq:-L5-nNmdW078hE5KRAoE:b-1x2yqp) ([raw file](https://github.com/pair-code/deeplearnjs/blob/4af1181aeeb4b2b0effb6ffc3e7615e9bbb3544f/website/api/index.html#L18)):*
> ```HTML
>     }
> 
>     .container {
> ```

small suggestion (up to you): you can move this to separate css file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/685#-:-L5-nn2Le161mJhwW3QV:b-fs5xbr)*

**Comment by tafsiri** [comment]
Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[website/api/index.html, line 18 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/685#-L5-nNmc-APsOQZBIUBq:-L59WzypgJ35migSMSSw:bhao0s2) ([raw file](https://github.com/pair-code/deeplearnjs/blob/4af1181aeeb4b2b0effb6ffc3e7615e9bbb3544f/website/api/index.html#L18)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

If you do that, can we use the template renderer to inline the CSS so we don't have to deal with style-jumping?
</blockquote></details>

Good suggestion. I'm not going to do that now though. I'm pretty much deferring any cleanup until after 0.5 when we can figure out larger website things. 

---

*[website/scripts/make-api.ts, line 51 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/685#-L5-KYoPaJUocDxmvT8n:-L59WK8dEDZNy-tfMEA_:b-jljtgh) ([raw file](https://github.com/pair-code/deeplearnjs/blob/4af1181aeeb4b2b0effb6ffc3e7615e9bbb3544f/website/scripts/make-api.ts#L51)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

why replace <p> tags? Instead of doing this, can we simply style them the way you want with CSS?
</blockquote></details>

we could. i mostly just wanted to remove the outer paragraphs and not collapse any potential inner paragraphs created by actual line breaks in the text. however if i wrap them in a container i could probably use a first child selector or something to do it via css. I'll keep in this mind for the next round.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/685)*

**Pull request merged**
