### PR TITLE
Unary Ops Grad: Adds leaky relu gradient

### PR DESCRIPTION
**Pull request by ManrajGrover**
This PR adds gradient for `dl.leakyRelu`

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/679)

### CODE REVIEW

**Comment by nsthorat** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/math/unary_ops.ts, line 229 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/679#-L551StYFfehkgsVHdwP:-L551StYFfehkgsVHdwQ:b-wt9pvm) ([raw file](https://github.com/pair-code/deeplearnjs/blob/b12fc81a12f47003da89365ada0e737dc4df4275/src/math/unary_ops.ts#L229)):*
> ```XML
>     const gradient = (dy: T, y: T) => {
>       return {
>         x: () => {
> ```

shouldnt this derivative simply be dl.step(x, this.alpha)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/679)*

**Comment by ManrajGrover** [comment]
@nsthorat Yeah, I feel it could be simplified to `dy.mul(x.step(alpha))`. Making the required change

**Comment by nsthorat** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/math/unary_ops_test.ts, line 1221 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/679#-L55LJPny6VFb8d8vtiS:-L55LJPny6VFb8d8vtiT:b-f5hagx) ([raw file](https://github.com/pair-code/deeplearnjs/blob/c29624de1ea9ef6215a90d6c6c337cc31978804b/src/math/unary_ops_test.ts#L1221)):*
> ```XML
>     const gradients = dl.vjp(() => dl.leakyRelu(a, alpha), a, dy);
> 
>     const expected = [];
> ```

instead of doing this programmatically let's just do it manually, e.g.

expected = [1, 2 * alpha, .1]

kind of thing

And same in the test below

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/679)*

**Comment by nsthorat** [comment]
Update branch and I'll merge.

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/679#-:-L55VJ_Tkw6l6VWv_Xqr:b-jbsf8z)*

**Comment by dsmilkov** [comment]
:lgtm_strong:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/679#-:-L5ADALAarWs61Hj-sYv:b-jbsf8z)*

**Pull request merged**
