### PR TITLE
Redesign of teachable games demo

### PR DESCRIPTION
**Pull request by mpushkarna**
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/315)

### CODE REVIEW

**Comment by jameswex** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[demos/teachable_gaming/teachable_gaming.html, line 147 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/315#-KySNOCAy7xDOgtzkyN2:-KySNOCAy7xDOgtzkyN3:b-1ze985) ([raw file](https://github.com/pair-code/deeplearnjs/blob/37b910d03d314999c089fcd24c58276dbccf46b9/demos/teachable_gaming/teachable_gaming.html#L147)):*
> ```HTML
>               1. Pick a game to play
>             </div>
>             
> ```

move the dropdown closer to the game window, its very far vertically from the game with this new layout

---

*[demos/teachable_gaming/teachable_gaming.html, line 212 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/315#-KySN6Rfo0FjosCsS0wk:-KySN6Rfo0FjosCsS0wl:bki2el) ([raw file](https://github.com/pair-code/deeplearnjs/blob/37b910d03d314999c089fcd24c58276dbccf46b9/demos/teachable_gaming/teachable_gaming.html#L212)):*
> ```HTML
>               <div class="statsholder statsholder-key mdl-typography--caption mld-cell mdl-cell--6-col mdl-cell--1-offset-desktop mdl-cell--4-col-tablet mdl-cell--4-col-phone">
>                 <div>Rolling Average of FPS during Gameplay:</div>
>                 <div id="predfps statsholder-val"></div>
> ```

fix this id to just be predfps

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/315)*

**Comment by jameswex** [comment]
Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[demos/teachable_gaming/index.html, line 22 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/315#-KySQrkb-M5T-lzK8UQ8:-KySQo_StljMFboRBBNe:b-l6mwxj) ([raw file](https://github.com/pair-code/deeplearnjs/blob/0a92ad389c4861fb21619f6d98614dfc5fa13ad5/demos/teachable_gaming/index.html#L22)):*
> ```HTML
>   
>   <meta charset="UTF-8">
>   <meta http-equiv="X-UA-Compatible" content="IE=edge">
> ```

remove

---

*[demos/teachable_gaming/teachable_gaming.html, line 30 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/315#-KySR7tBFAKxwYSwZcBi:-KySR7tBFAKxwYSwZcBj:b-mtwqc9) ([raw file](https://github.com/pair-code/deeplearnjs/blob/0a92ad389c4861fb21619f6d98614dfc5fa13ad5/demos/teachable_gaming/teachable_gaming.html#L30)):*
> ```HTML
> <style>
> .gameholder {
>   margin-left: 10px;
> ```

remove this rule

---

*[demos/teachable_gaming/teachable_gaming.html, line 104 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/315#-KySR3Nf0j1KgXKiojM2:-KySR3Nf0j1KgXKiojM3:b-l6mwxj) ([raw file](https://github.com/pair-code/deeplearnjs/blob/0a92ad389c4861fb21619f6d98614dfc5fa13ad5/demos/teachable_gaming/teachable_gaming.html#L104)):*
> ```HTML
> }
> .reset-button {
>   /*margin-top:8px;*/
> ```

remove

---

*[demos/teachable_gaming/teachable_gaming.html, line 142 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/315#-KySR6eMClu393g7DQIk:-KySR6eMClu393g7DQIl:b-l6mwxj) ([raw file](https://github.com/pair-code/deeplearnjs/blob/0a92ad389c4861fb21619f6d98614dfc5fa13ad5/demos/teachable_gaming/teachable_gaming.html#L142)):*
> ```HTML
>         
>         <div class="holder mdl-grid">
>           
> ```

remove

---

*[demos/teachable_gaming/teachable_gaming.html, line 181 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/315#-KySRKiiiCo3fwQH_V0N:-KySRKiiiCo3fwQH_V0O:bvrbdn1) ([raw file](https://github.com/pair-code/deeplearnjs/blob/0a92ad389c4861fb21619f6d98614dfc5fa13ad5/demos/teachable_gaming/teachable_gaming.html#L181)):*
> <div id="ssl-message" style="display: none">
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>
>                     You must be visting this page via SSL to see the webcam demo.<br>
>                     To get around this temporarily, start chrome with <pre>--unsafely-treat-insecure-origin-as-secure=http://your.domain:5432/</pre>
>                   </div>
>                   
>                   <div id="webcam-message" style="display: none">
>                     Oops! We could not find a webcam. Please connect your webcam to view the full demo!
>                   </div>
</details>

remove these and add camera icon behind webcam video?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/315)*

**Comment by mpushkarna** [comment]
Review status: 0 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[demos/teachable_gaming/teachable_gaming.html, line 147 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/315#-KySNOCAy7xDOgtzkyN2:-KyST-O4HAeJ-6RWwMvw:bwdyd6b) ([raw file](https://github.com/pair-code/deeplearnjs/blob/37b910d03d314999c089fcd24c58276dbccf46b9/demos/teachable_gaming/teachable_gaming.html#L147)):*
<details><summary><i>Previously, jameswex (James Wexler) wrote…</i></summary><blockquote>

move the dropdown closer to the game window, its very far vertically from the game with this new layout
</blockquote></details>

addressed by changing from dropdown to horizontally stacked cards for each game in next visual overhaul

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/315)*

**Comment by nsthorat** [comment]
Review status: 0 of 4 files reviewed at latest revision, 15 unresolved discussions.

---

*[demos/demo-header.html, line 18 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/315#-KySUhatlqiu38PMrj4Y:-KySUhatlqiu38PMrj4Z:b-tqhywu) ([raw file](https://github.com/pair-code/deeplearnjs/blob/cb4e2d3dc53f41e71126635863f1df4b7c2ab209/demos/demo-header.html#L18)):*
> ```HTML
> <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
> <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
> <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.orange-deep_purple.min.css" />
> ```

one more place you need to update:
https://github.com/PAIR-code/deeplearnjs/blob/master/demos/performance_rnn/index.html#L21

---

*[demos/teachable_gaming/index.html, line 31 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/315#-KySV7i-8jPbn_6dtC7F:-KySV7i-8jPbn_6dtC7G:b-o4bjhi) ([raw file](https://github.com/pair-code/deeplearnjs/blob/cb4e2d3dc53f41e71126635863f1df4b7c2ab209/demos/teachable_gaming/index.html#L31)):*
> ```HTML
>   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dialog-polyfill/0.4.9/dialog-polyfill.min.css" />
>   <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
>   <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
> ```

do we need these ?

---

*[demos/teachable_gaming/index.html, line 32 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/315#-KySV49XUEXGqF64jheU:-KySV49XUEXGqF64jheV:b-tkd33z) ([raw file](https://github.com/pair-code/deeplearnjs/blob/cb4e2d3dc53f41e71126635863f1df4b7c2ab209/demos/teachable_gaming/index.html#L32)):*
> ```HTML
>   <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
>   <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
>   <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.orange-deep_purple.min.css" />
> ```

do we need this if it's also in the header?

---

*[demos/teachable_gaming/teachable_gaming.html, line 22 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/315#-KySV9dJz_rdG8p48RlU:-KySV9dJz_rdG8p48RlV:b-o4bjhi) ([raw file](https://github.com/pair-code/deeplearnjs/blob/cb4e2d3dc53f41e71126635863f1df4b7c2ab209/demos/teachable_gaming/teachable_gaming.html#L22)):*
> ```HTML
> <link rel="import" href="../bower_components/paper-item/paper-item.html">
> <link rel="import" href="../bower_components/paper-dialog/paper-dialog.html">
> <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
> ```

do we need these ?

---

*[demos/teachable_gaming/teachable_gaming.html, line 24 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/315#-KySUvw86xEYgGxKJG5K:-KySUvw86xEYgGxKJG5L:b-d26e2l) ([raw file](https://github.com/pair-code/deeplearnjs/blob/cb4e2d3dc53f41e71126635863f1df4b7c2ab209/demos/teachable_gaming/teachable_gaming.html#L24)):*
> ```HTML
> <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
> <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
> <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.orange-deep_purple.min.css" />
> ```

if you're doing this in the header, do you need to do it here too?

---

*[demos/teachable_gaming/teachable_gaming.html, line 161 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/315#-KySVGVp5GAhXZ25TXzx:-KySVGVp5GAhXZ25TXzy:bqx6ynr) ([raw file](https://github.com/pair-code/deeplearnjs/blob/cb4e2d3dc53f41e71126635863f1df4b7c2ab209/demos/teachable_gaming/teachable_gaming.html#L161)):*
> ```HTML
> 
>             
>             
> ```

remove blank line

---

*[demos/teachable_gaming/teachable_gaming.html, line 182 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/315#-KySVIs22rL0nByvzmfZ:-KySVIs22rL0nByvzmf_:bqx6ynr) ([raw file](https://github.com/pair-code/deeplearnjs/blob/cb4e2d3dc53f41e71126635863f1df4b7c2ab209/demos/teachable_gaming/teachable_gaming.html#L182)):*
> ```HTML
>                 </div>
>               </div>
>             
> ```

remove blank line

---

*[demos/teachable_gaming/teachable_gaming.html, line 197 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/315#-KySVJl_O1Y3iTGuR6M0:-KySVJl_O1Y3iTGuR6M1:bqx6ynr) ([raw file](https://github.com/pair-code/deeplearnjs/blob/cb4e2d3dc53f41e71126635863f1df4b7c2ab209/demos/teachable_gaming/teachable_gaming.html#L197)):*
> ```HTML
>               
>               <div id="dosbox" class="mld-cell mdl-cell--10-col mdl-cell--1-offset-desktop mdl-cell--10-col-tablet mdl-cell--4-col-phone mdl-typography--body-1"></div>
>               
> ```

remove blank line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/315)*

**Comment by mpushkarna** [comment]
Review status: 0 of 4 files reviewed at latest revision, 15 unresolved discussions.

---

*[demos/teachable_gaming/index.html, line 31 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/315#-KySV7i-8jPbn_6dtC7F:-KySYLzKYITnpW99Nbi9:b3417w0) ([raw file](https://github.com/pair-code/deeplearnjs/blob/cb4e2d3dc53f41e71126635863f1df4b7c2ab209/demos/teachable_gaming/index.html#L31)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

do we need these ?
</blockquote></details>

Removing all material stylesheet imports. If anything breaks we'll bring it back in the next iteration.

---

*[demos/teachable_gaming/index.html, line 32 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/315#-KySV49XUEXGqF64jheU:-KySYRTyeEkiCV_m_fW6:b-iihsc1) ([raw file](https://github.com/pair-code/deeplearnjs/blob/cb4e2d3dc53f41e71126635863f1df4b7c2ab209/demos/teachable_gaming/index.html#L32)):*
> Removing mdl stylesheet. If anything breaks we'll bring it back in the next iteration.

---

*[demos/teachable_gaming/teachable_gaming.html, line 22 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/315#-KySV9dJz_rdG8p48RlU:-KySYUnlA9LVkARAdvj0:b-rawec9) ([raw file](https://github.com/pair-code/deeplearnjs/blob/cb4e2d3dc53f41e71126635863f1df4b7c2ab209/demos/teachable_gaming/teachable_gaming.html#L22)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

do we need these ?
</blockquote></details>

Removing it. If anything breaks we'll bring it back in the next iteration.

---

*[demos/teachable_gaming/teachable_gaming.html, line 24 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/315#-KySUvw86xEYgGxKJG5K:-KySYU4qICOmYCg7QHSX:b-rawec9) ([raw file](https://github.com/pair-code/deeplearnjs/blob/cb4e2d3dc53f41e71126635863f1df4b7c2ab209/demos/teachable_gaming/teachable_gaming.html#L24)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

if you're doing this in the header, do you need to do it here too?
</blockquote></details>

Removing it. If anything breaks we'll bring it back in the next iteration.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/315)*

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Reviewed 1 of 4 files at r1, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/315#-:-KySalnGmyRZb3JfhzGx:b-jbsf8z)*

**Pull request merged**
