### PR TITLE
Update models to deeplearnjs 0.5.0

### PR DESCRIPTION
**Pull request by HalfdanJ**
Making required changes to the  knn image classifier and squeezenet models for 0.5.0. Added a simple demo to test knn image classifier.

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/769)

### CODE REVIEW

**Comment by HalfdanJ** [comment]
The travis errors seems to be because the demos and models are pulling in the old version of the code. Not sure how to get around that?

**Comment by nkreeger** [comment]
You'll have to update the demos I think (sorry). I think there are plans to move the demos and models out to make this easier in the future.

**Comment by dsmilkov** [comment]
This is awesome. Left a few comments (the only major comments are about not removing .scope, but replacing it with dl.tidy(), we renamed that).

Regarding Travis failure, you will have to update the versions in models/*/package.json and also the model versions in deps of demos/package.json to point to the newer models. Travis will still fail btw, since we haven't yet published these models. In the current build system, there is no way around that, but I can fix that right after we merge your PR - by publishing the new versions of those models on npm - which will make Travis happy

---

Reviewed 11 of 12 files at r1.
Review status: 11 of 12 files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[models/knn_image_classifier/demo.html, line 22 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yOVZmnCcElABgL15j:-L5yOVZmnCcElABgL15k:b-uk4j27) ([raw file](https://github.com/pair-code/deeplearnjs/blob/f8b173b327766b52f5f72b7f45d4d5f796e5fd23/models/knn_image_classifier/demo.html#L22)):*
> ```HTML
>     // If dl isn't loaded, wait 1 second.
>     if (dl == null) {
>       await new Promise(resolve => setTimeout(resolve, 1000));
> ```

is this necessarily, or is this because we are being very cautious? 

---

*[models/knn_image_classifier/demo.html, line 30 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yPFtlFhhKqavvGLbO:-L5yPFtlFhhKqavvGLbP:bxfvgo6) ([raw file](https://github.com/pair-code/deeplearnjs/blob/f8b173b327766b52f5f72b7f45d4d5f796e5fd23/models/knn_image_classifier/demo.html#L30)):*
> ```HTML
>     resultElement.innerText = 'Training...';
> 
>     const catPixels = dl.Array3D.fromPixels(cat);
> ```

dl.fromPixels: [doc here](https://deeplearnjs.org/docs/api/index.html#dl.fromPixels)

---

*[models/knn_image_classifier/knn_image_classifier.ts, line 23 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yRQrskwHaF_3iaMz6:-L5yRQrskwHaF_3iaMz7:b-xzbswu) ([raw file](https://github.com/pair-code/deeplearnjs/blob/f8b173b327766b52f5f72b7f45d4d5f796e5fd23/models/knn_image_classifier/knn_image_classifier.ts#L23)):*
> implements dl.Model

I think you can drop `implements dl.Model` (also dl.Model will change soon)

---

*[models/knn_image_classifier/knn_image_classifier.ts, line 34 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yPSErLYIaLUTddwGj:-L5yPSErLYIaLUTddwGk:bbd5j1t) ([raw file](https://github.com/pair-code/deeplearnjs/blob/f8b173b327766b52f5f72b7f45d4d5f796e5fd23/models/knn_image_classifier/knn_image_classifier.ts#L34)):*
> ```XML
> 
>   private varsLoaded = false;
>   private squashLogitsDenominator = dl.Scalar.new(300);
> ```

dl.scalar(300)

---

*[models/knn_image_classifier/knn_image_classifier.ts, line 88 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yOsYpH5y-nDhDDAmZ:-L5yOsYqoPkdosNzab_h:bxkhze9) ([raw file](https://github.com/pair-code/deeplearnjs/blob/4d71d8561fb7dfedcaa50227eb5ee8cfa87c8d04/models/knn_image_classifier/knn_image_classifier.ts#L88)):*
> ```XML
>     this.clearTrainLogitsMatrix();
> 
>     this.math.scope((keep, track) => {
> ```

[doc here](https://deeplearnjs.org/docs/api/index.html#dl.tidy)
dl.tidy(() => {
...
dl.keep(this.classLogitsMatrices[classIndex]);
}

---

*[models/knn_image_classifier/knn_image_classifier.ts, line 131 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yP68caYle5lX1xBLX:-L5yP68caYle5lX1xBLY:bavb07k) ([raw file](https://github.com/pair-code/deeplearnjs/blob/4d71d8561fb7dfedcaa50227eb5ee8cfa87c8d04/models/knn_image_classifier/knn_image_classifier.ts#L131)):*
> ```XML
>     }
> 
>     return this.math.scope((keep) => {
> ```

same here: use dl.tidy(() => ... dl.keep());

---

*[models/knn_image_classifier/knn_image_classifier.ts, line 149 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yPfvT4I7_DT3cGmCo:-L5yPfvT4I7_DT3cGmCp:b-66ae7q) ([raw file](https://github.com/pair-code/deeplearnjs/blob/f8b173b327766b52f5f72b7f45d4d5f796e5fd23/models/knn_image_classifier/knn_image_classifier.ts#L149)):*
> ```XML
> 
>     const numExamples = this.getNumExamples();
>     return dl
> ```

small suggestion: you can use chaining here:
a.matMul(b);

---

*[models/knn_image_classifier/knn_image_classifier.ts, line 237 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yPp-I9itXnY2IlPkL:-L5yPp-I9itXnY2IlPkM:b-5lb81h) ([raw file](https://github.com/pair-code/deeplearnjs/blob/f8b173b327766b52f5f72b7f45d4d5f796e5fd23/models/knn_image_classifier/knn_image_classifier.ts#L237)):*
> ```XML
>     }
>     if (ndarray1 == null) {
>       return dl.clone(ndarray2);
> ```

chaining: ndarray2.clone()

---

*[models/knn_image_classifier/knn_image_classifier.ts, line 254 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yQKBu223V4P6uvjpU:-L5yQKBu223V4P6uvjpV:b-do7ley) ([raw file](https://github.com/pair-code/deeplearnjs/blob/f8b173b327766b52f5f72b7f45d4d5f796e5fd23/models/knn_image_classifier/knn_image_classifier.ts#L254)):*
> ```XML
>     const squashedVec = dl.div(vec, this.squashLogitsDenominator);
> 
>     const sqrtSum = dl.mulStrict(squashedVec, squashedVec).sum().sqrt();
> ```

you can chain all the way. Also we have .square(), so:
`const sqrtSum = squashedVec.square().sum().sqrt();`

---

*[models/knn_image_classifier/package.json, line 3 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yQvI_flCc232ej6U5:-L5yQvI_flCc232ej6U6:bl618m) ([raw file](https://github.com/pair-code/deeplearnjs/blob/f8b173b327766b52f5f72b7f45d4d5f796e5fd23/models/knn_image_classifier/package.json#L3)):*
> ```JSON
> {
>   "name": "deeplearn-knn-image-classifier",
>   "version": "0.2.3",
> ```

update version

---

*[models/knn_image_classifier/package.json, line 12 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yQxIHq93pvCjJ6DFl:-L5yQxIHq93pvCjJ6DFm:b-ygbt20) ([raw file](https://github.com/pair-code/deeplearnjs/blob/f8b173b327766b52f5f72b7f45d4d5f796e5fd23/models/knn_image_classifier/package.json#L12)):*
> ```JSON
>   },
>   "dependencies": {
>     "deeplearn-squeezenet": "~0.1.9"
> ```

make it depend on the new, updated squeezenet version

---

*[models/squeezenet/package.json, line 3 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yQmqkfpPVHguINxr5:-L5yQmqkfpPVHguINxr6:bb83ps5) ([raw file](https://github.com/pair-code/deeplearnjs/blob/f8b173b327766b52f5f72b7f45d4d5f796e5fd23/models/squeezenet/package.json#L3)):*
> ```JSON
> {
>   "name": "deeplearn-squeezenet",
>   "version": "0.1.9",
> ```

update squeezenet version

---

*[models/squeezenet/squeezenet.ts, line 29 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yRHRSdwIQMq5l2k3P:-L5yRHRTkKVt4RpTf6LB:b5rgea1) ([raw file](https://github.com/pair-code/deeplearnjs/blob/f8b173b327766b52f5f72b7f45d4d5f796e5fd23/models/squeezenet/squeezenet.ts#L29)):*
> ```XML
>     'fire4'|'fire5'|'maxpool_3'|'fire6'|'fire7'|'fire8'|'fire9'|'conv10';
> 
> export class SqueezeNet implements dl.Model {
> ```

I think you can drop `implements dl.Model` (also dl.Model will change soon)

---

*[models/squeezenet/squeezenet.ts, line 31 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yPUezM1W3J5wVj-aM:-L5yPUezM1W3J5wVj-aN:bktgz96) ([raw file](https://github.com/pair-code/deeplearnjs/blob/f8b173b327766b52f5f72b7f45d4d5f796e5fd23/models/squeezenet/squeezenet.ts#L31)):*
> ```XML
> export class SqueezeNet implements dl.Model {
>   private variables: {[varName: string]: dl.Tensor};
>   private preprocessOffset = Tensor1D.new([103.939, 116.779, 123.68]);
> ```

dl.tensor1d([...])

---

*[models/squeezenet/squeezenet.ts, line 66 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yRltNMBy1_7ThXFW_:-L5yRltNMBy1_7ThXFWa:b-kk9y4c) ([raw file](https://github.com/pair-code/deeplearnjs/blob/4d71d8561fb7dfedcaa50227eb5ee8cfa87c8d04/models/squeezenet/squeezenet.ts#L66)):*
> ```XML
>   predictWithActivation(input: Array3D, activationName?: ActivationName):
>       {logits: Array1D, activation: Array3D} {
>     const [logits, activation] = this.math.scope(() => {
> ```

same here: use dl.tidy(() => ...);

---

*[models/squeezenet/squeezenet.ts, line 93 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yRtZF_ESczTWyFi1T:-L5yRtZF_ESczTWyFi1U:b-getw40) ([raw file](https://github.com/pair-code/deeplearnjs/blob/f8b173b327766b52f5f72b7f45d4d5f796e5fd23/models/squeezenet/squeezenet.ts#L93)):*
> ```XML
>     }
> 
>     const pool2 = dl.maxPool(fire3, 3, 2, 'valid');
> ```

small suggestion here and elsewhere below: you can chain
`fire3.maxPool(3, 2, 'valid');`

---

*[models/squeezenet/squeezenet.ts, line 175 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yRoqWD5c6GuaXHrGl:-L5yRoqWD5c6GuaXHrGm:b-kk9y4c) ([raw file](https://github.com/pair-code/deeplearnjs/blob/4d71d8561fb7dfedcaa50227eb5ee8cfa87c8d04/models/squeezenet/squeezenet.ts#L175)):*
> ```XML
>   async getTopKClasses(logits: Array1D, topK: number):
>       Promise<{[className: string]: number}> {
>     const predictions = this.math.scope(() => {
> ```

same here: use dl.tidy(() => ...);

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-:-L5yS7dX_29tE5JWYfPM:bak11d6)*

**Comment by HalfdanJ** [comment]
They are updated, I can revert the demos to not be updated (since they are pulling the models from npm) and update them later. But knn-image-classifier is also pulling squeezenet from npm registry, and that will also result in errors.

**Comment by dsmilkov** [comment]
See my previous comment (above your comment). Update all versions as if everything was pulished to npm. Once we merge your PR (I'll force merge), I'll publish on npm and Travis will be happy

**Comment by HalfdanJ** [comment]
Review status: 8 of 13 files reviewed at latest revision, 17 unresolved discussions.

---

*[models/knn_image_classifier/demo.html, line 22 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yOVZmnCcElABgL15j:-L5yTpPyUV8ozpM3feW5:b-pyl362) ([raw file](https://github.com/pair-code/deeplearnjs/blob/f8b173b327766b52f5f72b7f45d4d5f796e5fd23/models/knn_image_classifier/demo.html#L22)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

is this necessarily, or is this because we are being very cautious? 
</blockquote></details>

I copied it from the squeezenet demo, but don't know if it is

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769)*

**Comment by HalfdanJ** [comment]
Review status: 7 of 14 files reviewed at latest revision, 17 unresolved discussions.

---

*[models/knn_image_classifier/demo.html, line 22 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yOVZmnCcElABgL15j:-L5ydvi3ACdJVDELQQTY:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/f8b173b327766b52f5f72b7f45d4d5f796e5fd23/models/knn_image_classifier/demo.html#L22)):*
<details><summary><i>Previously, HalfdanJ (Jonas Jongejan) wrote…</i></summary><blockquote>

I copied it from the squeezenet demo, but don't know if it is
</blockquote></details>

Done.

---

*[models/knn_image_classifier/demo.html, line 30 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yPFtlFhhKqavvGLbO:-L5ydjOQB8DJ2wungsXw:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/f8b173b327766b52f5f72b7f45d4d5f796e5fd23/models/knn_image_classifier/demo.html#L30)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

dl.fromPixels: [doc here](https://deeplearnjs.org/docs/api/index.html#dl.fromPixels)
</blockquote></details>

Done.

---

*[models/knn_image_classifier/knn_image_classifier.ts, line 23 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yRQrskwHaF_3iaMz6:-L5yd44ad82SZkaN8ER_:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/f8b173b327766b52f5f72b7f45d4d5f796e5fd23/models/knn_image_classifier/knn_image_classifier.ts#L23)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

> implements dl.Model

I think you can drop `implements dl.Model` (also dl.Model will change soon)
</blockquote></details>

Done.

---

*[models/knn_image_classifier/knn_image_classifier.ts, line 34 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yPSErLYIaLUTddwGj:-L5yd5UUMI26ph0l10pj:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/f8b173b327766b52f5f72b7f45d4d5f796e5fd23/models/knn_image_classifier/knn_image_classifier.ts#L34)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

dl.scalar(300)
</blockquote></details>

Done.

---

*[models/knn_image_classifier/knn_image_classifier.ts, line 88 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yOsYpH5y-nDhDDAmZ:-L5yd620Wm8RXSFxv-6h:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/4d71d8561fb7dfedcaa50227eb5ee8cfa87c8d04/models/knn_image_classifier/knn_image_classifier.ts#L88)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

[doc here](https://deeplearnjs.org/docs/api/index.html#dl.tidy)
dl.tidy(() => {
...
dl.keep(this.classLogitsMatrices[classIndex]);
}
</blockquote></details>

Done.

---

*[models/knn_image_classifier/knn_image_classifier.ts, line 131 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yP68caYle5lX1xBLX:-L5yd6_xhym5d6Alk41m:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/4d71d8561fb7dfedcaa50227eb5ee8cfa87c8d04/models/knn_image_classifier/knn_image_classifier.ts#L131)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

same here: use dl.tidy(() => ... dl.keep());
</blockquote></details>

Done.

---

*[models/knn_image_classifier/knn_image_classifier.ts, line 149 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yPfvT4I7_DT3cGmCo:-L5yd7yEu3Z0vGPmRZYd:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/f8b173b327766b52f5f72b7f45d4d5f796e5fd23/models/knn_image_classifier/knn_image_classifier.ts#L149)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

small suggestion: you can use chaining here:
a.matMul(b);
</blockquote></details>

Done.

---

*[models/knn_image_classifier/knn_image_classifier.ts, line 237 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yPp-I9itXnY2IlPkL:-L5yd8FgqnHkQHSRhNoS:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/f8b173b327766b52f5f72b7f45d4d5f796e5fd23/models/knn_image_classifier/knn_image_classifier.ts#L237)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

chaining: ndarray2.clone()
</blockquote></details>

Done.

---

*[models/knn_image_classifier/knn_image_classifier.ts, line 254 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yQKBu223V4P6uvjpU:-L5yd9ZcozQE8OLJtl1j:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/f8b173b327766b52f5f72b7f45d4d5f796e5fd23/models/knn_image_classifier/knn_image_classifier.ts#L254)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

you can chain all the way. Also we have .square(), so:
`const sqrtSum = squashedVec.square().sum().sqrt();`
</blockquote></details>

Done.

---

*[models/knn_image_classifier/package.json, line 3 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yQvI_flCc232ej6U5:-L5ydXl_pdldMzCLw49o:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/f8b173b327766b52f5f72b7f45d4d5f796e5fd23/models/knn_image_classifier/package.json#L3)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

update version
</blockquote></details>

Done.

---

*[models/knn_image_classifier/package.json, line 12 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yQxIHq93pvCjJ6DFl:-L5ydYJBakh9FRo1PfwG:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/f8b173b327766b52f5f72b7f45d4d5f796e5fd23/models/knn_image_classifier/package.json#L12)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

make it depend on the new, updated squeezenet version
</blockquote></details>

Done.

---

*[models/squeezenet/package.json, line 3 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yQmqkfpPVHguINxr5:-L5yd_DEtw3S1TDG2SyC:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/f8b173b327766b52f5f72b7f45d4d5f796e5fd23/models/squeezenet/package.json#L3)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

update squeezenet version
</blockquote></details>

Done.

---

*[models/squeezenet/squeezenet.ts, line 29 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yRHRSdwIQMq5l2k3P:-L5yd_u15kirwgxZ5zQg:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/f8b173b327766b52f5f72b7f45d4d5f796e5fd23/models/squeezenet/squeezenet.ts#L29)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

I think you can drop `implements dl.Model` (also dl.Model will change soon)
</blockquote></details>

Done.

---

*[models/squeezenet/squeezenet.ts, line 31 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yPUezM1W3J5wVj-aM:-L5ydaSf1KRVLhQgAQVM:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/f8b173b327766b52f5f72b7f45d4d5f796e5fd23/models/squeezenet/squeezenet.ts#L31)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

dl.tensor1d([...])
</blockquote></details>

Done.

---

*[models/squeezenet/squeezenet.ts, line 66 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yRltNMBy1_7ThXFW_:-L5ydbEpWaKFK0cMJEYt:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/4d71d8561fb7dfedcaa50227eb5ee8cfa87c8d04/models/squeezenet/squeezenet.ts#L66)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

same here: use dl.tidy(() => ...);
</blockquote></details>

Done.

---

*[models/squeezenet/squeezenet.ts, line 93 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yRtZF_ESczTWyFi1T:-L5ydcm55N7_uQOhnjqT:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/f8b173b327766b52f5f72b7f45d4d5f796e5fd23/models/squeezenet/squeezenet.ts#L93)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

small suggestion here and elsewhere below: you can chain
`fire3.maxPool(3, 2, 'valid');`
</blockquote></details>

Done.

---

*[models/squeezenet/squeezenet.ts, line 175 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yRoqWD5c6GuaXHrGl:-L5ydeeCOUDb7Rl7x54I:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/4d71d8561fb7dfedcaa50227eb5ee8cfa87c8d04/models/squeezenet/squeezenet.ts#L175)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

same here: use dl.tidy(() => ...);
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769)*

**Comment by dsmilkov** [comment]
:lgtm_strong: Nice work

---

Reviewed 1 of 12 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[models/knn_image_classifier/demo.html, line 22 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-L5yOVZmnCcElABgL15j:-L5zPzC_TKPw5e-IhxhR:b-54ne9r) ([raw file](https://github.com/pair-code/deeplearnjs/blob/f8b173b327766b52f5f72b7f45d4d5f796e5fd23/models/knn_image_classifier/demo.html#L22)):*
<details><summary><i>Previously, HalfdanJ (Jonas Jongejan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It's probably not necessary, but we can remove it later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/769#-:-L5zRIpdYQSg2NP3cTv2:bmmvdxd)*

**Pull request merged**
