### PR TITLE
Fonts

### PR DESCRIPTION
**Pull request by shancarter**
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/399)

### CODE REVIEW

**Comment by nsthorat** [comment]
Review status: 0 of 17 files reviewed at latest revision, 22 unresolved discussions.

---

*[demos/fonts/App.vue, line 65 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/399#-L-EnXgc28jztxgrhpPM:-L-EnXgc28jztxgrhpPN:bpdbryy) ([raw file](https://github.com/pair-code/deeplearnjs/blob/b9e8187a9e7cc72ad1ba0c85b35e599a410a77a5/demos/fonts/App.vue#L65)):*
> ```Vue
> </template>
> 
> <script>
> ```

can we put the typescript in a separate file, and same for the other .vue files?

---

*[demos/fonts/components/Sample.vue, line 16 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/399#-L-Enx08Fp4eDVSc6Cng:-L-Enx08Fp4eDVSc6Cnh:b-pi9d9n) ([raw file](https://github.com/pair-code/deeplearnjs/blob/b9e8187a9e7cc72ad1ba0c85b35e599a410a77a5/demos/fonts/components/Sample.vue#L16)):*
> ```Vue
> ==============================================================================-->
> 
> 
> ```

remove this

---

*[demos/fonts/components/Sample.vue, line 78 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/399#-L-Eny7UXDJDS_tVI87_:-L-Eny7UXDJDS_tVI87a:b-l6mwxj) ([raw file](https://github.com/pair-code/deeplearnjs/blob/b9e8187a9e7cc72ad1ba0c85b35e599a410a77a5/demos/fonts/components/Sample.vue#L78)):*
> ```Vue
>   },
>   methods: {
>     // select: function(event) {
> ```

remove

---

*[demos/fonts/components/Tray.vue, line 22 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/399#-L-EnzJKo5dVFq5J2dlQ:-L-EnzJKo5dVFq5J2dlR:b-hmayd1) ([raw file](https://github.com/pair-code/deeplearnjs/blob/b9e8187a9e7cc72ad1ba0c85b35e599a410a77a5/demos/fonts/components/Tray.vue#L22)):*
> ```Vue
>     :style="{height: height + 'px'}"
> 
>   >
> ```

put > on the line with }"

---

*[demos/fonts/components/Tray.vue, line 94 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/399#-L-Eo2Qx4ZNZE53SFbQo:-L-Eo2Qx4ZNZE53SFbQp:b-l6mwxj) ([raw file](https://github.com/pair-code/deeplearnjs/blob/b9e8187a9e7cc72ad1ba0c85b35e599a410a77a5/demos/fonts/components/Tray.vue#L94)):*
> ```Vue
>       return math.divide(this.direction, length);
>     },
>     // selectedScalar: function() {
> ```

remove

---

*[demos/fonts/utils/ChunkedQueue.ts, line 22 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/399#-L-EowO2pbfPJahUcyRx:-L-EowO2pbfPJahUcyRy:b-pj2q1) ([raw file](https://github.com/pair-code/deeplearnjs/blob/b9e8187a9e7cc72ad1ba0c85b35e599a410a77a5/demos/fonts/utils/ChunkedQueue.ts#L22)):*
> ```XML
> 
> export class Queue {
>   public interval: number;
> ```

public is default in ts

---

*[demos/fonts/utils/ChunkedQueue.ts, line 24 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/399#-L-EoXAHL1AnEx9oOtVS:-L-EoXAHL1AnEx9oOtVT:bx3zu7a) ([raw file](https://github.com/pair-code/deeplearnjs/blob/b9e8187a9e7cc72ad1ba0c85b35e599a410a77a5/demos/fonts/utils/ChunkedQueue.ts#L24)):*
> ```XML
>   public interval: number;
>   public elementsPerChunk: number;
>   private _timeoutID: number;
> ```

remove the underscores, private is good enough for ts style

---

*[demos/fonts/utils/ChunkedQueue.ts, line 37 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/399#-L-Eo6MwoN_Ttu5ZIA6j:-L-Eo6MwoN_Ttu5ZIA6k:b-hsd751) ([raw file](https://github.com/pair-code/deeplearnjs/blob/b9e8187a9e7cc72ad1ba0c85b35e599a410a77a5/demos/fonts/utils/ChunkedQueue.ts#L37)):*
> ```XML
>   add(cb: () => void, id: number, priority: number) {
>     this.remove(id);
>     if (id === undefined) id = -1;
> ```

Replace with:
`if (id == null) {
  id = -1;
}`

Double equals will do an implicit cast to catch both undefined and null. TypeScript google style also says always have {}. Same comment for "priority" below

---

*[demos/fonts/utils/ChunkedQueue.ts, line 58 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/399#-L-EoL48tMDuC0yX7O2n:-L-EoL48tMDuC0yX7O2o:bm5twhp) ([raw file](https://github.com/pair-code/deeplearnjs/blob/b9e8187a9e7cc72ad1ba0c85b35e599a410a77a5/demos/fonts/utils/ChunkedQueue.ts#L58)):*
> ```XML
>   }
> 
>   _nextChunk() {
> ```

why the underscores? if this is meant to be private, remove underscore and call it "private", same everywhere else

---

*[demos/fonts/utils/ChunkedQueue.ts, line 65 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/399#-L-EoRX5DBCodWKdYVit:-L-EoRX5DBCodWKdYViu:bms38xg) ([raw file](https://github.com/pair-code/deeplearnjs/blob/b9e8187a9e7cc72ad1ba0c85b35e599a410a77a5/demos/fonts/utils/ChunkedQueue.ts#L65)):*
> ```XML
>     if (!this._running) {
>       this._running = true;
>       this._timeoutID = setTimeout(this._run.bind(this), this.interval);
> ```

use a closure for consistency with our codebase

setTimeout(() => this._run(), this.interval);

---

*[demos/fonts/utils/ChunkedQueue.ts, line 77 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/399#-L-EoQXS2DZ7iK41_kZW:-L-EoQXS2DZ7iK41_kZX:bqx6ynr) ([raw file](https://github.com/pair-code/deeplearnjs/blob/b9e8187a9e7cc72ad1ba0c85b35e599a410a77a5/demos/fonts/utils/ChunkedQueue.ts#L77)):*
> ```XML
>     if (this._queue.length) this._kick();
>   }
> ```

remove blank line

---

*[demos/fonts/utils/FontExamples.ts, line 15 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/399#-L-Eo_vM7p7dK-cu_Mli:-L-Eo_vM7p7dK-cu_Mlj:bb1hprr) ([raw file](https://github.com/pair-code/deeplearnjs/blob/b9e8187a9e7cc72ad1ba0c85b35e599a410a77a5/demos/fonts/utils/FontExamples.ts#L15)):*
> ```XML
> ==============================================================================*/
> 
> import { Array1D } from 'deeplearn';
> ```

Can you make sure clang-format command line tool, clant-format vscode extension, and tslint vscode extension are installed? It will fix this formatting problem..

make sure you save all the other files too (there are formatting issues in other files)

---

*[demos/fonts/utils/FontModel.ts, line 21 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/399#-L-Eopa5wq1DVki48Q1t:-L-Eopa5wq1DVki48Q1u:b-elvkl0) ([raw file](https://github.com/pair-code/deeplearnjs/blob/b9e8187a9e7cc72ad1ba0c85b35e599a410a77a5/demos/fonts/utils/FontModel.ts#L21)):*
> ```XML
> 
> let variables: { [varName: string]: NDArray };
> let math: NDArrayMathGPU;
> ```

can you make these scoped to FontModel

---

*[demos/fonts/utils/FontModel.ts, line 27 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/399#-L-Eomr_I1mXsVVJJJZL:-L-Eomr_I1mXsVVJJJZM:b6rf2wa) ([raw file](https://github.com/pair-code/deeplearnjs/blob/b9e8187a9e7cc72ad1ba0c85b35e599a410a77a5/demos/fonts/utils/FontModel.ts#L27)):*
> ```XML
> 
> export class FontModel {
>   public metaData = "A";
> ```

single quotes

---

*[demos/fonts/utils/FontModel.ts, line 28 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/399#-L-EosDpBHB_EpDSs5Su:-L-EosDpBHB_EpDSs5Sv:b52mu7x) ([raw file](https://github.com/pair-code/deeplearnjs/blob/b9e8187a9e7cc72ad1ba0c85b35e599a410a77a5/demos/fonts/utils/FontModel.ts#L28)):*
> ```XML
> export class FontModel {
>   public metaData = "A";
>   public dimensions = 40;
> ```

public is default in typescript

---

*[demos/fonts/utils/FontModel.ts, line 51 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/399#-L-Eoy2bBF654U1CyauQ:-L-Eoy2bBF654U1CyauR:b6rf2wa) ([raw file](https://github.com/pair-code/deeplearnjs/blob/b9e8187a9e7cc72ad1ba0c85b35e599a410a77a5/demos/fonts/utils/FontModel.ts#L51)):*
> ```XML
>   load(cb: () => void) {
>     const checkpointLoader = new CheckpointLoader(
>       "https://storage.googleapis.com/learnjs-data/checkpoint_zoo/fonts/");
> ```

single quotes

---

*[demos/fonts/utils/FontModel.ts, line 67 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/399#-L-EozJr1gZRxbhQIRU6:-L-EozJr1gZRxbhQIRU7:b-l6mwxj) ([raw file](https://github.com/pair-code/deeplearnjs/blob/b9e8187a9e7cc72ad1ba0c85b35e599a410a77a5/demos/fonts/utils/FontModel.ts#L67)):*
> ```XML
>   }
> 
>   remove(id: number) {
> ```

remove

---

*[demos/fonts/utils/ModelCache.ts, line 18 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/399#-L-Ep1hXyP2nrMJOGw50:-L-Ep1hYsudoSRce-uJM:bqx6ynr) ([raw file](https://github.com/pair-code/deeplearnjs/blob/b9e8187a9e7cc72ad1ba0c85b35e599a410a77a5/demos/fonts/utils/ModelCache.ts#L18)):*
> ```XML
> 
> export class Cache {
> ```

remove blank line

---

*[demos/fonts/utils/ModelCache.ts, line 33 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/399#-L-Ep4k1MUkTws6llVZZ:-L-Ep4k1MUkTws6llVZ_:bop7lir) ([raw file](https://github.com/pair-code/deeplearnjs/blob/b9e8187a9e7cc72ad1ba0c85b35e599a410a77a5/demos/fonts/utils/ModelCache.ts#L33)):*
> ```XML
> 
>   get(id: number, argsArray: Array<{}>) {
>     //TODO actually cache/retrieve the values.
> ```

// TODO(shancarter)

---

*[demos/fonts/utils/ModelCache.ts, line 51 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/399#-L-Ep3az3pfezBFkyfBA:-L-Ep3az3pfezBFkyfBB:bqx6ynr) ([raw file](https://github.com/pair-code/deeplearnjs/blob/b9e8187a9e7cc72ad1ba0c85b35e599a410a77a5/demos/fonts/utils/ModelCache.ts#L51)):*
> ```XML
>     return this._paused;
>   }
> ```

remove blank line

---

*[demos/fonts/utils/Utils.ts, line 17 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/399#-L-Ep79cXGBTJMfTqbLT:-L-Ep79cXGBTJMfTqbLU:b-yqe39z) ([raw file](https://github.com/pair-code/deeplearnjs/blob/b9e8187a9e7cc72ad1ba0c85b35e599a410a77a5/demos/fonts/utils/Utils.ts#L17)):*
> ```XML
> import { NDArray, Array1D, Scalar, NDArrayMathCPU } from 'deeplearn';
> 
> const math = new NDArrayMathCPU(false);
> ```

no need to pass false

---

*[demos/fonts/utils/Utils.ts, line 49 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/399#-L-EpB7A95t9FNNawD1n:-L-EpB7A95t9FNNawD1o:b-jjzns0) ([raw file](https://github.com/pair-code/deeplearnjs/blob/b9e8187a9e7cc72ad1ba0c85b35e599a410a77a5/demos/fonts/utils/Utils.ts#L49)):*
> ```XML
> export function unit(v: NDArray) {
>   const n = Scalar.new(norm(v).get());
>   if (n.get() === 0) console.warn("Divide by zero");
> ```

use {}

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/399)*

**Comment by shancarter** [comment]
Should be good to re-review. I snuck in a few new features, apologies. :)

**Comment by nsthorat** [comment]
:lgtm_strong:

Couple of minor things then I will merge. If <script src="blah.ts"> from .vue files doesn't work, ignore my comment.

---

Reviewed 2 of 28 files at r1, 11 of 28 files at r2.
Review status: 8 of 18 files reviewed at latest revision, 6 unresolved discussions.

---

*[demos/latent-space-explorer/components/Sample.vue, line 83 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/399#-L-ON0w0v8PhK6pA1oOw:-L-ON0w0v8PhK6pA1oOx:b-jjzns0) ([raw file](https://github.com/pair-code/deeplearnjs/blob/dfead33b92ebc46d28ba9c639eb201b158e4f87c/demos/latent-space-explorer/components/Sample.vue#L83)):*
> ```Vue
>     render: function() {
>       this.waiting = true;
>       if (this.model) this.model.metaData = this.modelData;
> ```

use {}

---

*[demos/latent-space-explorer/components/Sample.vue, line 84 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/399#-L-ON0LHc_nbuCZSotmY:-L-ON0LHc_nbuCZSotmZ:btd3cno) ([raw file](https://github.com/pair-code/deeplearnjs/blob/dfead33b92ebc46d28ba9c639eb201b158e4f87c/demos/latent-space-explorer/components/Sample.vue#L84)):*
> ```Vue
>       this.waiting = true;
>       if (this.model) this.model.metaData = this.modelData;
>       // let localPriority = (priority === 0 ? -position : priority);
> ```

remove this comment

---

*[demos/latent-space-explorer/components/Tray.vue, line 43 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/399#-L-OMpngrWnyf2IyrBMf:-L-OMpnhJHE6-jOXn0Hk:bued911) ([raw file](https://github.com/pair-code/deeplearnjs/blob/dfead33b92ebc46d28ba9c639eb201b158e4f87c/demos/latent-space-explorer/components/Tray.vue#L43)):*
> ```Vue
> </template>
> 
> <script>
> ```

Just curious, you can't just do this? If it's not that simple, ignore me.

https://github.com/PAIR-code/deeplearnjs/blob/master/demos/vue-demo/App.vue#L31

---

*[demos/latent-space-explorer/components/Tray.vue, line 193 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/399#-L-ON32_FBj6sdgWCjCd:-L-ON32_FBj6sdgWCjCe:b-pi9d9n) ([raw file](https://github.com/pair-code/deeplearnjs/blob/dfead33b92ebc46d28ba9c639eb201b158e4f87c/demos/latent-space-explorer/components/Tray.vue#L193)):*
> ```Vue
>   width: 3px;
>   border-radius: 2px;
>   /*border: 1px solid black;*/
> ```

remove this

---

*[demos/latent-space-explorer/utils/ChunkedQueue.ts, line 79 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/399#-L-ONBkNDrjlNyedlySr:-L-ONBkNDrjlNyedlySs:b-jjzns0) ([raw file](https://github.com/pair-code/deeplearnjs/blob/dfead33b92ebc46d28ba9c639eb201b158e4f87c/demos/latent-space-explorer/utils/ChunkedQueue.ts#L79)):*
> ```XML
>     });
>     this.running = false;
>     if (this.queue.length) this.kick();
> ```

use {}

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/399#-:-L-ONTsrP9JSmQYjEMyn:b-2dlw8s)*

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: 7 of 18 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/399#-:-L-SNgloOKDcJXKeMu0S:b-jbsf8z)*

**Pull request merged**
