### PR TITLE
Turn off localResponseNormalization#D test for integer-packed textures.

### PR DESCRIPTION
**Pull request by nsthorat**
I disabled the wrong test in the previous PR. This will remove flake, but we should investigate why this is flaky.

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/633)

### CODE REVIEW

**Comment by nsthorat** [comment]
@chaosmail any idea why this test would be flaky?

**Comment by chaosmail** [comment]
hmm very strange, all tests passed on travis for LRN right? Could you give me the exact test settings to reproduce the bug so I could take a look?

**Comment by nsthorat** [comment]
It seems to be flaky, so it's unclear. Here is an example: https://api.travis-ci.org/v3/job/336158839/log.txt

**Comment by dsmilkov** [comment]
:lgtm_strong: Add a todo in the test

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/633#-:-L4N5TirNYKuUe5k8WpX:b8s1hkj)*

**Comment by tafsiri** [comment]
@nsthorat Just FYI doubt its related to the change you made but i'm seeing other failures in the log. e.g.  dl.reverse as well. We can continue to track flakiness in #630

**Pull request merged**
