### PR TITLE
Logical Operators: Add math.logicalXor method 

### PR DESCRIPTION
**Pull request by ManrajGrover**
This PR adds logicalXor operator for NDArrays which can be used as `math.logicalXor(a, b)`.

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/564)

### CODE REVIEW

**Comment by dsmilkov** [comment]
When you update this, let me know and I'll happily review

**Comment by ManrajGrover** [comment]
@dsmilkov Ready for review :)

**Comment by dsmilkov** [comment]
Awesome. Can you also add this to the chain API in NDArray?

---

Reviewed 7 of 8 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/math/logical_ops.ts, line 60 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/564#-L3tKPtttebrPYPovsr-:-L3tKPtttebrPYPovsr0:blsa9kj) ([raw file](https://github.com/pair-code/deeplearnjs/blob/8f33f467e38da7653be4fde092a311c06a8b0e1c/src/math/logical_ops.ts#L60)):*
> ```XML
>    * Returns the truth value of a XOR b element-wise. Supports broadcasting.
>    *
>    * @param a The first input `NDArray`.
> ```

Append `Must be of dtype bool.` to the jsdoc of @param a and @param b.
Also if you can update that in other places in this file, that would be great. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/564#-:-L3tKoOrHEt2I1lI9M_A:b-jkwn87)*

**Comment by dsmilkov** [comment]
:lgtm_strong:

---

Review status: 3 of 11 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/564#-:-L4WiRkZ01b1J77NDdG0:b-jbsf8z)*

**Pull request merged**
