### PR TITLE
Add conv1d ops

### PR DESCRIPTION
**Pull request by easadler**
In reference to #223. I copied how tensorflow uses `conv2d` for `conv1d` under the hood.

### Todo
- [x] split conv1d tests out of conv2d tests
- [x] more tests
- [x] linting  & doc strings

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/368)

### CODE REVIEW

**Comment by easadler** [comment]
@nsthorat Hey! Ready for an initial review. 

Not sure why travis-ci failed. Didn't seem to have a problem until I changed the comment.

**Comment by dsmilkov** [comment]
This is great!! I restarted travis CI and it passes (it was a network failure that failed the test - it happens). I left couple of comments. Ping me when you addressed and I'll take another look. Thanks!

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/math/conv2d_test.ts, line 183 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/368#-Kzy9kG3CHOBqnV2D7VY:-Kzy9kG3CHOBqnV2D7VZ:b-1eobj1) ([raw file](https://github.com/pair-code/deeplearnjs/blob/23e170e4c2e795e3bc24556a6c2336c8f0a79e95/src/math/conv2d_test.ts#L183)):*
> ```XML
> // math.conv1d
> {
>   const tests: MathTests = it => {
> ```

To avoid future user confusing, we should move these tests to `conv1d_test.ts`

---

*[src/math/math.ts, line 1342 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/368#-KzyAF8KgdDCc1rzqz94:-KzyAF8KgdDCc1rzqz95:bjponyq) ([raw file](https://github.com/pair-code/deeplearnjs/blob/23e170e4c2e795e3bc24556a6c2336c8f0a79e95/src/math/math.ts#L1342)):*
> ```XML
>    * Computes a 1D convolution over the input x.
>    * @param input The input ndarray, of rank 4 or rank 3, of shape
>    *     `[batch, height, width, inChannels]`. If rank 3, batch of 1 is assumed.
> ```

input should be rank 3 or rank 2, of shape [batch, width, inChannels]. Change jsdoc and the logic below to test for rank 2 and 3, instead of 3 and 4.

This is to be consistent with: https://www.tensorflow.org/api_docs/python/tf/nn/conv1d

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/368#-:-KzyAdG9rHajta81nTYM:b-y3pf0i)*

**Comment by dsmilkov** [comment]
:lgtm_strong: Sorry for the delay! Thanks for this great contribution! Ready to merge, just 1 more thing: the branch is out-of-sync with master. Let me know when you sync and I'll merge.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/368#-:-L-h4PHNQ_5eAOu-tGZq:bcodlzm)*

**Comment by easadler** [comment]
@dsmilkov should be good go now. Thanks for the review and I'm excited to keep contributing!

**Pull request merged**
