### PR TITLE
AdamOpt: Adds Adam Optimizer with eager mode

### PR DESCRIPTION
**Pull request by ManrajGrover**
This PR adds Adam Optimizer with eager mode

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/689)

### CODE REVIEW

**Comment by nsthorat** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/math/optimizers/adam_optimizer.ts, line 50 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/689#-L54w9280qzjQLE8erL-:-L54w9280qzjQLE8erL0:b-4jvccm) ([raw file](https://github.com/pair-code/deeplearnjs/blob/c376b803bfde5e35661133361d4b5bc71b809bcc/src/math/optimizers/adam_optimizer.ts#L50)):*
> ```XML
>     this.eps = keep(scalar(1e-8));
>     // b1, b2 keep initial value of beta* hyperparameters.
>     this.b1 = keep(scalar(this.beta1));
> ```

wrap these in variable so you can simply call assign

also name them:
this.beta1
this.beta1
this.accBeta1
this.accBeta2

---

*[src/math/optimizers/adam_optimizer.ts, line 99 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/689#-L54x4vNBx6U3wBbet3D:-L54x4vNBx6U3wBbet3E:b-7662p) ([raw file](https://github.com/pair-code/deeplearnjs/blob/c376b803bfde5e35661133361d4b5bc71b809bcc/src/math/optimizers/adam_optimizer.ts#L99)):*
> ```XML
>     }
> 
>     this.disposeAndUpdateBetas();
> ```

Remove this as a function, inline it inside of the tidy (when you add variable to the beta params you will be able to just call assign)

---

*[src/math/optimizers/optimizer_constructors.ts, line 59 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/689#-L54wSxevmwL--W1y3kq:-L54wSxfDtjEnSMvSV_l:b-yabmhm) ([raw file](https://github.com/pair-code/deeplearnjs/blob/c376b803bfde5e35661133361d4b5bc71b809bcc/src/math/optimizers/optimizer_constructors.ts#L59)):*
> ```XML
>    */
>   @doc({heading: 'Training', subheading: 'Optimizers', namespace: 'train'})
>   static adam(learningRate: number, beta1: number, beta2: number):
> ```

set the same defaults as TF, and add epsilon as a param

https://www.tensorflow.org/api_docs/python/tf/train/AdamOptimizer

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/689)*

**Comment by nsthorat** [comment]
We just did a big directory restructure, your merge should be straightforward but let me know when that's done.

**Comment by ManrajGrover** [comment]
@nsthorat Looks like there is no `assign` public method on `variable`. Cannot find `assign` method on `variable(scalar(1))`. Could you please look into it?

**Comment by nsthorat** [comment]
`dl.variable` returns a `dl.Variable`, which contains an `assign` method:
https://github.com/PAIR-code/deeplearnjs/blob/master/src/tensor.ts#L857-L872

**Comment by ManrajGrover** [comment]
@nsthorat This can be reviewed again

**Comment by nsthorat** [comment]
:lgtm_strong:

Will merge after 2 tiny changes. Nice work on this!!

---

Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/optimizers/adam_optimizer.ts, line 79 at r5](https://reviewable.io:443/reviews/pair-code/deeplearnjs/689#-L5EfYIBU8Pv1InmrCFN:-L5EfYIBU8Pv1InmrCFO:b-lnun25) ([raw file](https://github.com/pair-code/deeplearnjs/blob/27ef9d73092131463f273e04531ef8d083133feb/src/optimizers/adam_optimizer.ts#L79)):*
> ```XML
>       tidy(() => {
>         const newFirstMoment = this.beta1.mul(firstMoment)
>                                    .add(this.one.sub(this.beta1).mul(gradient));
> ```

1 - beta1 and 1 - beta2 are computed over and over, maybe we can make these their own variables in the constructor

---

*[src/optimizers/optimizer_constructors.ts, line 76 at r5](https://reviewable.io:443/reviews/pair-code/deeplearnjs/689#-L5Egn9Q2JOyfOM4YniM:-L5Egn9Q2JOyfOM4YniN:bbio04s) ([raw file](https://github.com/pair-code/deeplearnjs/blob/27ef9d73092131463f273e04531ef8d083133feb/src/optimizers/optimizer_constructors.ts#L76)):*
> ```XML
> 
>   /**
>    * Constructs a `dl.train.AdamOptimizer` that uses the Adam algorithm.
> ```

instead of using the whole namespace simply use the symbol (I'm going to link by non-namespaced symbol ID in the doc generator).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/689#-:-L5Eh2joloyCX4IUOXz0:blyb7dv)*

**Comment by ManrajGrover** [comment]
@nsthorat Done :)

**Comment by nsthorat** [comment]
:lgtm_strong:

1 more merge with master and I'll merge :) 

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/689#-:-L5Gs2QRSbmumFAxTM8N:bfc0por)*

**Pull request merged**
