### PR TITLE
Add math.pad1D() and math.pad2D() ops.

### PR DESCRIPTION
**Pull request by nkreeger**
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/531)

### CODE REVIEW

**Comment by dsmilkov** [comment]
Nice work! Just a few comments regarding the user-facing API and jsdoc. Ping me when done and I'll take another look!

---

Reviewed 8 of 9 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/math/math.ts, line 1018 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-L2_xV_Ogd2Ft1kXFThn:-L2_xV_Pnfd3uKv2uOH2:b6kvhje) ([raw file](https://github.com/pair-code/deeplearnjs/blob/aaeadf55f99edd6756bbbbff6627e8d9a0b90726/src/math/math.ts#L1018)):*
> Paddings must be described as int32.

you can skip paddings type description here and add below
`@param paddings A tuple of ints [padLeft, padRight], how much to pad on the left and right side of the array.`

Also no need to say int32, since its `number[]`

You can also skip `Paddings rank must match target array's rank` since this is only for Array1D.

Make similar changes for pad2D also.

---

*[src/math/math.ts, line 1025 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-L2_yzi2Gjui0IvmmmC1:-L2_yzi2Gjui0IvmmmC2:b-l1hk0u) ([raw file](https://github.com/pair-code/deeplearnjs/blob/aaeadf55f99edd6756bbbbff6627e8d9a0b90726/src/math/math.ts#L1025)):*
> paddings: number[]

Type `paddings` as `[number, number]` which tells the compiler to force it to have length of 2. We still keep run-time check of course.

---

*[src/math/math.ts, line 1026 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-L2a-_QnhffpoUu74MLL:-L2a-_QnhffpoUu74MLM:b5vn1rk) ([raw file](https://github.com/pair-code/deeplearnjs/blob/aaeadf55f99edd6756bbbbff6627e8d9a0b90726/src/math/math.ts#L1026)):*
> ```XML
>    */
>   pad1D(x: Array1D, paddings: number[]): Array1D {
>     util.assert(
> ```

in CONSTANT mode, TF also takes: `constant_values`: the scalar pad value to use. Must be same type as tensor.

Let's add that here as well.

---

*[src/math/math.ts, line 1044 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-L2_zILQ0QIL583ftSnt:-L2_zILQ0QIL583ftSnu:bc45z1h) ([raw file](https://github.com/pair-code/deeplearnjs/blob/aaeadf55f99edd6756bbbbff6627e8d9a0b90726/src/math/math.ts#L1044)):*
> paddings: number[][]

type it as `Array<[number, number]>` which forces the inner dim to be of length 2

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-:-L2a0C9jam4hY0CBRCGV:b-yc4lzk)*

**Comment by nkreeger** [comment]
Updated to address comments. PTAL.

---

Review status: 1 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/math/math.ts, line 1018 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-L2_xV_Ogd2Ft1kXFThn:-L2avuG5Llas7KMAlrmk:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/aaeadf55f99edd6756bbbbff6627e8d9a0b90726/src/math/math.ts#L1018)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

> Paddings must be described as int32.

you can skip paddings type description here and add below
`@param paddings A tuple of ints [padLeft, padRight], how much to pad on the left and right side of the array.`

Also no need to say int32, since its `number[]`

You can also skip `Paddings rank must match target array's rank` since this is only for Array1D.

Make similar changes for pad2D also.
</blockquote></details>

Done.

---

*[src/math/math.ts, line 1025 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-L2_yzi2Gjui0IvmmmC1:-L2avwYj8Yrz6e8WCqxY:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/aaeadf55f99edd6756bbbbff6627e8d9a0b90726/src/math/math.ts#L1025)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

> paddings: number[]

Type `paddings` as `[number, number]` which tells the compiler to force it to have length of 2. We still keep run-time check of course.

</blockquote></details>

Done.

---

*[src/math/math.ts, line 1026 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-L2a-_QnhffpoUu74MLL:-L2bGhR6DZBw1OcOXlqy:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/aaeadf55f99edd6756bbbbff6627e8d9a0b90726/src/math/math.ts#L1026)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

in CONSTANT mode, TF also takes: `constant_values`: the scalar pad value to use. Must be same type as tensor.

Let's add that here as well.
</blockquote></details>

Done.

---

*[src/math/math.ts, line 1044 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-L2_zILQ0QIL583ftSnt:-L2awfRbSvf-UN5IiyvZ:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/aaeadf55f99edd6756bbbbff6627e8d9a0b90726/src/math/math.ts#L1044)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

> paddings: number[][]

type it as `Array<[number, number]>` which forces the inner dim to be of length 2
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-:-L2bGjVzEXhQyyx2fhFI:bbz8ec2)*

**Comment by dsmilkov** [comment]
Looking pretty good! Left a few more comments - mostly style nits. Only one more important regarding calls to `scalar.get()`

---

Review status: 1 of 9 files reviewed at latest revision, 14 unresolved discussions.

---

*[src/math/math.ts, line 1026 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-L2a-_QnhffpoUu74MLL:-L2b_-L7CszXfwKcmuA0:b-3d1sfc) ([raw file](https://github.com/pair-code/deeplearnjs/blob/aaeadf55f99edd6756bbbbff6627e8d9a0b90726/src/math/math.ts#L1026)):*
<details><summary><i>Previously, nkreeger (Nick Kreeger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

rename to singular `constantValue`, since we only accept Scalar.

---

*[src/math/math.ts, line 1018 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-L2b_Cn-d45cjRRoVuUI:-L2b_Cn-d45cjRRoVuUJ:bxbkzyc) ([raw file](https://github.com/pair-code/deeplearnjs/blob/0337c1fc98e3a64cc7b40bef6966b22fe701cdff/src/math/math.ts#L1018)):*
> Paddings rank must match target array's rank.

remove this sentence here and in pad2d below.

---

*[src/math/math.ts, line 1025 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-L2b_MqBqmmtSv0SWQou:-L2b_MqBqmmtSv0SWQov:b6dybq7) ([raw file](https://github.com/pair-code/deeplearnjs/blob/0337c1fc98e3a64cc7b40bef6966b22fe701cdff/src/math/math.ts#L1025)):*
> left and right side of the array.

indent lines of param comments, other than the first line, with 4 spaces.

---

*[src/math/math.ts, line 1029 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-L2bcCjgMeUUVlg6uadJ:-L2bcCjgMeUUVlg6uadK:b-gjwalm) ([raw file](https://github.com/pair-code/deeplearnjs/blob/0337c1fc98e3a64cc7b40bef6966b22fe701cdff/src/math/math.ts#L1029)):*
> constantValues?: Scalar

Let's change constantValues to be `number` for now. I see below you are doing `scalar.get()` which puts the handbrake on the gpu, downloads the value to cpu and stalls the whole program. We can chat more offline.

Later, if we want to accept Scalar, we need to sample it in the glsl as texture2D, in order to avoid download to CPU.

---

*[src/math/math.ts, line 1053 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-L2ba7vicZIJrYbyJkw7:-L2ba7vicZIJrYbyJkw8:ba5sb3l) ([raw file](https://github.com/pair-code/deeplearnjs/blob/0337c1fc98e3a64cc7b40bef6966b22fe701cdff/src/math/math.ts#L1053)):*
> tiple

typo: tuple

---

*[src/math/math.ts, line 1054 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-L2b_XuSPODP88RdE10c:-L2b_XuSPODP88RdE10d:b-xgve5f) ([raw file](https://github.com/pair-code/deeplearnjs/blob/0337c1fc98e3a64cc7b40bef6966b22fe701cdff/src/math/math.ts#L1054)):*
> ```XML
>    * @param x The array to pad.
>    * @param paddings A pair of tiple ints
>    * [[padTop, padBottom], [padLeft, padRight]], how much to pad on the array.
> ```

indent lines of param comments, other than the first line, with 4 spaces.

---

*[src/math/math.ts, line 1058 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-L2baowojLqss_zxIeNr:-L2baNYQLCwaFlDBa_-W:b-jfcmkt) ([raw file](https://github.com/pair-code/deeplearnjs/blob/0337c1fc98e3a64cc7b40bef6966b22fe701cdff/src/math/math.ts#L1058)):*
> Array<[number, number]>

ha, I didn't realize on the first pass of review that paddings must be 2x2 matrix. In that case, can you type it as `[[number, number], [number, number]]` instead of `Array<[number, number]>`, This forces it to be 2x2, instead of Nx2. Sorry about that.

---

*[src/math/math.ts, line 1060 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-L2baQXuBPO5vgrHmj_Q:-L2baQXuBPO5vgrHmj_R:bhe9vx) ([raw file](https://github.com/pair-code/deeplearnjs/blob/0337c1fc98e3a64cc7b40bef6966b22fe701cdff/src/math/math.ts#L1060)):*
> ```XML
>   pad2D(x: Array2D, paddings: Array<[number, number]>, constantValues?: Scalar):
>       Array2D {
>     util.assert(
> ```

Can you also check that `paddings.length === 2`.

---

*[src/math/pad_test.ts, line 37 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-L2b_en8YOFXjnCF4vrC:-L2b_en8YOFXjnCF4vrD:b-7cu3ou) ([raw file](https://github.com/pair-code/deeplearnjs/blob/0337c1fc98e3a64cc7b40bef6966b22fe701cdff/src/math/pad_test.ts#L37)):*
> KREEGER'

remove KREEGER

---

*[src/math/pad_test.ts, line 106 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-L2b_ozQLx3kJZxXZW48:-L2b_ozQLx3kJZxXZW49:b-95sqyx) ([raw file](https://github.com/pair-code/deeplearnjs/blob/0337c1fc98e3a64cc7b40bef6966b22fe701cdff/src/math/pad_test.ts#L106)):*
> KREEGER

remove KREEGER

---

*[src/math/backends/backend_cpu.ts, line 1100 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-L2bb44TQQ-QatjjbYl_:-L2bb44TQQ-QatjjbYla:b52211o) ([raw file](https://github.com/pair-code/deeplearnjs/blob/0337c1fc98e3a64cc7b40bef6966b22fe701cdff/src/math/backends/backend_cpu.ts#L1100)):*
> !== undefined

js/ts@google decided to not use undefined. We followed them in our codebase. Instead just do `!= null`, or `== null` (note it's double-equal on purpose, not triple equal. The linter will let you do that when using null.
`!= null` handles both `undefined` and `null`, which is nice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-:-L2b_Hb6AmUs8AKtcu8W:bepnnaq)*

**Comment by nkreeger** [comment]
Review status: 1 of 9 files reviewed at latest revision, 14 unresolved discussions.

---

*[src/math/math.ts, line 1026 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-L2a-_QnhffpoUu74MLL:-L2beuC2f07saZnEiUcG:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/aaeadf55f99edd6756bbbbff6627e8d9a0b90726/src/math/math.ts#L1026)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

rename to singular `constantValue`, since we only accept Scalar.
</blockquote></details>

Done.

---

*[src/math/math.ts, line 1044 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-L2_zILQ0QIL583ftSnt:-L2bg_UfQ4k09NCMg1fH:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/aaeadf55f99edd6756bbbbff6627e8d9a0b90726/src/math/math.ts#L1044)):*
<details><summary><i>Previously, nkreeger (Nick Kreeger) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[src/math/math.ts, line 1018 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-L2b_Cn-d45cjRRoVuUI:-L2behu3DZmRZ0hyQuC0:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/0337c1fc98e3a64cc7b40bef6966b22fe701cdff/src/math/math.ts#L1018)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

> Paddings rank must match target array's rank.

remove this sentence here and in pad2d below.
</blockquote></details>

Done.

---

*[src/math/math.ts, line 1025 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-L2b_MqBqmmtSv0SWQou:-L2berRtSP3Brs9wgcnD:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/0337c1fc98e3a64cc7b40bef6966b22fe701cdff/src/math/math.ts#L1025)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

> left and right side of the array.

indent lines of param comments, other than the first line, with 4 spaces.
</blockquote></details>

Done.

---

*[src/math/math.ts, line 1029 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-L2bcCjgMeUUVlg6uadJ:-L2bi7H3HctcRT2tVpPJ:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/0337c1fc98e3a64cc7b40bef6966b22fe701cdff/src/math/math.ts#L1029)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

> constantValues?: Scalar

Let's change constantValues to be `number` for now. I see below you are doing `scalar.get()` which puts the handbrake on the gpu, downloads the value to cpu and stalls the whole program. We can chat more offline.

Later, if we want to accept Scalar, we need to sample it in the glsl as texture2D, in order to avoid download to CPU.
</blockquote></details>

Done.

---

*[src/math/math.ts, line 1053 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-L2ba7vicZIJrYbyJkw7:-L2bew0IGoX2AjXAJ8HO:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/0337c1fc98e3a64cc7b40bef6966b22fe701cdff/src/math/math.ts#L1053)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

> tiple

typo: tuple
</blockquote></details>

Done.

---

*[src/math/math.ts, line 1054 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-L2b_XuSPODP88RdE10c:-L2bewQspyyXrxjG6oAf:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/0337c1fc98e3a64cc7b40bef6966b22fe701cdff/src/math/math.ts#L1054)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

indent lines of param comments, other than the first line, with 4 spaces.
</blockquote></details>

Done.

---

*[src/math/math.ts, line 1058 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-L2baowojLqss_zxIeNr:-L2bgaBgFYGsAFoiYCDA:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/0337c1fc98e3a64cc7b40bef6966b22fe701cdff/src/math/math.ts#L1058)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

> Array<[number, number]>

ha, I didn't realize on the first pass of review that paddings must be 2x2 matrix. In that case, can you type it as `[[number, number], [number, number]]` instead of `Array<[number, number]>`, This forces it to be 2x2, instead of Nx2. Sorry about that.
</blockquote></details>

Done.

---

*[src/math/math.ts, line 1060 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-L2baQXuBPO5vgrHmj_Q:-L2bhwBSzY9lJ6BUS7Fx:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/0337c1fc98e3a64cc7b40bef6966b22fe701cdff/src/math/math.ts#L1060)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

Can you also check that `paddings.length === 2`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531)*

**Comment by nkreeger** [comment]
Review status: 1 of 9 files reviewed at latest revision, 14 unresolved discussions.

---

*[src/math/pad_test.ts, line 37 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-L2b_en8YOFXjnCF4vrC:-L2bjpCGSJYdEj6t4liD:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/0337c1fc98e3a64cc7b40bef6966b22fe701cdff/src/math/pad_test.ts#L37)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

> KREEGER'

remove KREEGER
</blockquote></details>

Done.

---

*[src/math/pad_test.ts, line 106 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-L2b_ozQLx3kJZxXZW48:-L2bjqpbp9sUxQ2Zo3my:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/0337c1fc98e3a64cc7b40bef6966b22fe701cdff/src/math/pad_test.ts#L106)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

> KREEGER

remove KREEGER
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531)*

**Comment by dsmilkov** [comment]
:lgtm_strong: Nice work! This touches on all of our stack :) One tiny suggestion. Feel free to submit!

---

Reviewed 8 of 8 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/math/backends/webgl/pad_gpu.ts, line 78 at r4](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-L2boPCotQiaKJVCCYHz:-L2boPCotQiaKJVCCYI-:b-cku4bn) ([raw file](https://github.com/pair-code/deeplearnjs/blob/439296d324067011e38de6adf2fc4b9db341aa8a/src/math/backends/webgl/pad_gpu.ts#L78)):*
> ```XML
>         if (resRC.x < ${topPadding} || resRC.x >= topShape ||
>             resRC.y < ${leftPadding} || resRC.y >= leftShape) {
>           setOutput(${constant});
> ```

you can maybe avoid the `getConstantFloatingStr` helper if you do:
`setOutput(float(${constantValue}))`, but I'm not 100% sure :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-:-L2boexse7M3CTFjjRc9:b-f28cp9)*

**Comment by nkreeger** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/math/backends/webgl/pad_gpu.ts, line 78 at r4](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531#-L2boPCotQiaKJVCCYHz:-L2c1Nijvt6UY8H2J4jb:b-9bp6di) ([raw file](https://github.com/pair-code/deeplearnjs/blob/439296d324067011e38de6adf2fc4b9db341aa8a/src/math/backends/webgl/pad_gpu.ts#L78)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

you can maybe avoid the `getConstantFloatingStr` helper if you do:
`setOutput(float(${constantValue}))`, but I'm not 100% sure :)
</blockquote></details>

Nice - this worked, thank you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/531)*

**Pull request merged**
