### PR TITLE
Add unary ops benchmark

### PR DESCRIPTION
**Pull request by Lewuathe**
Add benchmark for unary ops. (e.g. `sum`, `exp`, `sigmoid`)

screen shot 2017-09-16 at 11 21 57

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/130)

### CODE REVIEW

**Comment by dsmilkov** [comment]
Hi Kai,

`min`, `max` and `sum` are not unary op - they are reduction ops (mapping N -> 1), thus slower than cpu (for now) since they don't parallelize across the output. Can you separate them in another category.

FYI, we will significantly speed up min/max/sum soon, but using pooling mechanisms (e.g. divide the array in K parts and compute K max values along 1/Kth of the array, then merge)

**Comment by Lewuathe** [comment]
@dsmilkov I see. I'll exclude these reduction unary ops from there for now. 

> FYI, we will significantly speed up reduction ops (min/max/sum) soon, by using pooling mechanisms (e.g. divide the array in K parts and compute K max values along 1/Kth of the array, then merge)

**Comment by dsmilkov** [comment]
Thanks. No need to exclude them altogether, you can just add them in a separate category (it's own dropdown) with the name `Reduction Op Benchmark`

**Comment by dsmilkov** [comment]
This is very very cool! Thank you! I left a few comments, but almost all are style/formatting related. 

---

Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[demos/benchmarks/math-benchmark-run-groups.ts, line 41 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/130#-KuUdAFnSaoKF9gn0Xti:-KuUdAFnSaoKF9gn0Xtj:b-ro1noo) ([raw file](https://github.com/pair-code/deeplearnjs/blob/7c2b8f4eefcd69bd34937aaf3f1f502fdde5a5de/demos/benchmarks/math-benchmark-run-groups.ts#L41)):*
> hasOptions: false

remove `hasOptions` since it is redundant with `options`. That is, check if `options == null` as a way to infer whether the run has options. Then you can remove the `hasOptions: false` in the runs below

---

*[demos/benchmarks/math-benchmark-run-groups.ts, line 71 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/130#-KuUczATjNZTCmrr7C2b:-KuUczATjNZTCmrr7C2c:b-8sj1vp) ([raw file](https://github.com/pair-code/deeplearnjs/blob/7c2b8f4eefcd69bd34937aaf3f1f502fdde5a5de/demos/benchmarks/math-benchmark-run-groups.ts#L71)):*
> ····
remove trailing space

---

*[demos/benchmarks/math-benchmark-run-groups.ts, line 86 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/130#-KuUd2IvHgRL3_2mQWda:-KuUd2IvHgRL3_2mQWdb:b-6xgtkz) ([raw file](https://github.com/pair-code/deeplearnjs/blob/7c2b8f4eefcd69bd34937aaf3f1f502fdde5a5de/demos/benchmarks/math-benchmark-run-groups.ts#L86)):*
> ```XML
>     max: 1024,
>     stepSize: 64,
>     hasOptions: false,    
> ```

same here and below, remove trailing space

---

*[demos/benchmarks/reduction_ops_benchmark.ts, line 32 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/130#-KuUdfyzG6CdEzj7pU4n:-KuUdfyzG6CdEzj7pU4o:b-wmxmv1) ([raw file](https://github.com/pair-code/deeplearnjs/blob/7c2b8f4eefcd69bd34937aaf3f1f502fdde5a5de/demos/benchmarks/reduction_ops_benchmark.ts#L32)):*
> ```XML
>       (input: NDArray) => Scalar {
> 	switch (option) {
> 		case "max":
> ```

replace tabs with spaces. Are you using a code editor? You can install `clang-format` (available for most editors) and run it to format the files. Also if you are using visual studio code, you can enable `formatOnSave` (I'm sure other editors have the same option) so you don't have to worry at all about this.

More info [here](https://github.com/PAIR-code/deeplearnjs#development)

---

*[demos/benchmarks/unary_ops_benchmark.ts, line 79 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/130#-KuUeIVU6md456Ure6Ga:-KuUeIVU6md456Ure6Gb:b-q1dy9i) ([raw file](https://github.com/pair-code/deeplearnjs/blob/7c2b8f4eefcd69bd34937aaf3f1f502fdde5a5de/demos/benchmarks/unary_ops_benchmark.ts#L79)):*
> ```XML
> 	    for (let i = 0; i < OPS_PER_RUN; i++) {
> 		    math.scope(() => {
>                 op(input).get();
> ```

same here, replace tabs with spaces

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/130#-:-KuUeLlpdiwGvXIp5yPQ:blcm7xw)*

**Comment by Lewuathe** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[demos/benchmarks/reduction_ops_benchmark.ts, line 32 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/130#-KuUdfyzG6CdEzj7pU4n:-KuUiF6C6yn-bZTUV4vS:bvlivx4) ([raw file](https://github.com/pair-code/deeplearnjs/blob/7c2b8f4eefcd69bd34937aaf3f1f502fdde5a5de/demos/benchmarks/reduction_ops_benchmark.ts#L32)):*
> here
Thank you for information. I'll try.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/130)*

**Comment by dsmilkov** [comment]
:lgtm_strong: Awesome. Thanks so much!

---

Reviewed 1 of 5 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/130#-:-Ku_74j33VTKpH6FDH0M:b-yuh3tn)*

**Pull request merged**
