### PR TITLE
Moves away from `math` to `dl`

### PR DESCRIPTION
**Pull request by ManrajGrover**
This PR makes sure everything makes use of `dl` and moves away from `math`. Changes made in:

1. `math_test`
2. `multinomial_test`
3. `resize_bilinear_test`
4. `slice_test`
5. `softmax_test`
6. `tensor_test`
7.  `transpose_test`
8. `unary_ops_test`
9. `variable_test`
10. `debug_mode_test`
11. `conv2d_test`
12. `conv2dtranspose_test`
13. `conv2d_depthwise_test`
14. `lstm_test`
15. `pad_test`

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/647)

### CODE REVIEW

**Comment by ManrajGrover** [comment]
@dsmilkov I will wait for #646 to be merged before making any more changes in this (due to conflicting changes) :)

**Comment by dsmilkov** [comment]
:lgtm_strong: This is awesome. Feel free to also use the chain api in tests.

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/647#-:-L4fSQuf6MjSz5IGm3Nn:b8zejun)*

**Comment by dsmilkov** [comment]
PR still says work in progress. Let me know if you want me to merge this now , or wait for more stuff.

**Comment by ManrajGrover** [comment]
@dsmilkov Yeah, there are some migrations in #661. I'm trying not to have overlapping changes.

I'm still making changes and will ping once done.

One thing, `math.getNumTensors()` is not available publically. Do we plan to add it to public api?

**Comment by dsmilkov** [comment]
Sounds great! Great q. Absolutely. We'll probably expose it as `dl.memoryProfile()` which will return a rich object, currently `{numTensors: number, numDataBuffers: number}` , where `numDataBuffers <= numTensors`, since doing `b = a.reshape(newShape)` makes a new Tensor `b` that shares the same data buffer with `a`. Feedback welcome.

**Comment by dsmilkov** [comment]
Iterating on the profile idea in #662

**Comment by ManrajGrover** [comment]
@dsmilkov Awesome :)

This PR is ready for review now. Few things we might need to add to public api apart from `math.getNumTensors()`:

1. `math.scaledArrayAdd`
2. `math.localResponseNormalization4D`

**Comment by dsmilkov** [comment]
:lgtm_strong: Very cool. Thank you for helping us with this large migration!

---

Reviewed 3 of 4 files at r3, 3 of 3 files at r4, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/647#-:-L4ftVhA4TfnNoa9UDU-:b-hvempp)*

**Pull request merged**
