### PR TITLE
Add RMSProp and Adagrad optimizers.

### PR DESCRIPTION
**Pull request by mnottheone**
Also resolved texture leakage and optimizers inherited from optimizer.ts

This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/102)

### CODE REVIEW

**Comment by mnottheone** [comment]
Indentation left. Will do soon.

**Comment by nsthorat** [comment]
Are you using vscode? If so can you merge with master and make sure you have clang-format extension installed? If not using vscode, make sure you format with clang-format and clang-format.style = "Google" (I won't comment on individual stylistic changes that this will fix).

Overall looks great after these minor changes!

---

Reviewed 1 of 7 files at r1.
Review status: 1 of 7 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[demos/model-builder/model-builder.ts, line 853 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/102#-KtP-nXwM16pJ1o12Rue:-KtP-nXwM16pJ1o12Ruf:b-6nr0jd) ([raw file](https://github.com/pair-code/deeplearnjs/blob/cd59ab4ad8aa3f789023ae0371a92e82fb64e1c7/demos/model-builder/model-builder.ts#L853)):*
> ```XML
> }
> 
> document.registerElement(ModelBuilder.prototype.is, ModelBuilder);
> ```

revert this file

---

*[src/adagrad_optimizer.ts, line 54 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/102#-KtXS1rxUHrxHMC4Pspc:-KtXS1rxUHrxHMC4Pspd:b2rfbl8) ([raw file](https://github.com/pair-code/deeplearnjs/blob/cd59ab4ad8aa3f789023ae0371a92e82fb64e1c7/src/adagrad_optimizer.ts#L54)):*
> ```XML
>         const gradientSquare = math.multiply(gradient, gradient);
>         const cache = math.add(oldCache, gradientSquare);
>         const variable = math.scaledArrayAdd(this.c!,
> ```

remove ! everywhere.

---

*[src/rmsprop_optimizer.ts, line 20 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/102#-KtXSUSKc69__ME16xkw:-KtXSUSKc69__ME16xkx:bp50san) ([raw file](https://github.com/pair-code/deeplearnjs/blob/cd59ab4ad8aa3f789023ae0371a92e82fb64e1c7/src/rmsprop_optimizer.ts#L20)):*
> ```XML
> import {TensorArrayMap, SummedTensorArrayMap} from './tensor_array_map';
> 
> export class RmspropOptimizer extends Optimizer {
> ```

call this RMSPropOptimizer

---

*[src/rmsprop_optimizer.ts, line 36 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/102#-KtXSbaIux_nhHalYcxz:-KtXSbaIux_nhHalYcy-:bc6osy6) ([raw file](https://github.com/pair-code/deeplearnjs/blob/cd59ab4ad8aa3f789023ae0371a92e82fb64e1c7/src/rmsprop_optimizer.ts#L36)):*
> ```XML
>     super.beforeBatch(math, batchSize, runtime,
>       activationArrayMap, gradientArrayMap);
>       if (this.cache.size() === 0) {
> ```

can we rename this from cache? How about accumulatedGradients

---

*[src/rmsprop_optimizer.ts, line 55 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/102#-KtXSSG6-G1r7j3hubDO:-KtXSSG6-G1r7j3hubDP:b995nuq) ([raw file](https://github.com/pair-code/deeplearnjs/blob/cd59ab4ad8aa3f789023ae0371a92e82fb64e1c7/src/rmsprop_optimizer.ts#L55)):*
> ```XML
>         const oldCache = this.cache.get(node.output);
>         const gradientSquare = math.multiply(gradient, gradient);
>         const cache = math.scaledArrayAdd(this.g!, oldCache,
> ```

remove ! everywhere

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/102#-:-KtRokDcxkXr-ywZqmyV:b-f2a88n)*

**Comment by mnottheone** [comment]
*[src/rmsprop_optimizer.ts, line 36 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/102#-KtXSbaIux_nhHalYcxz:-Kta9NI9REyuhJP5fMGh:b-of73ea) ([raw file](https://github.com/pair-code/deeplearnjs/blob/cd59ab4ad8aa3f789023ae0371a92e82fb64e1c7/src/rmsprop_optimizer.ts#L36)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

can we rename this from cache? How about accumulatedGradients
</blockquote></details>

We have already used accumulatedGradients in optimizer.ts's after example, so it may be confusing. Here, we are storing sum of gradient squares so, we can use something like accumulatedSquaredGradients and for rmsprop we have discounted prev cache , so we can use accumulatedDiscountedSquaredGradients or accumulatedSquaredGradients only. What do you think ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/102)*

**Comment by nsthorat** [comment]
Let me know when you're auto formatting and I will merge this!

---

Reviewed 2 of 7 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/adagrad_optimizer.ts, line 22 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/102#-KtduzOggYwNaLVsjpt1:-KtduzOggYwNaLVsjpt2:bpp8hsv) ([raw file](https://github.com/pair-code/deeplearnjs/blob/c9b33872f96a119c85a7df51050e42d8b68bfe58/src/adagrad_optimizer.ts#L22)):*
> ```XML
> export class AdagradOptimizer extends Optimizer {
>   constructor(protected learningRate: number,
>     protected momentum: number, specifiedVariableList?: Node[]) {
> ```

with clang-format, this should be indented, can you make sure you've got it running (same for the other files)

Sorry about that, everything else looks good after the code gets formatted

---

*[src/rmsprop_optimizer.ts, line 36 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/102#-KtXSbaIux_nhHalYcxz:-Ktdv8RUcpWbiZ_HX_XQ:bcoip1k) ([raw file](https://github.com/pair-code/deeplearnjs/blob/b0a117537784c68a9333fd82899923b5183b8aec/src/rmsprop_optimizer.ts#L36)):*
<details><summary><i>Previously, mnottheone (Aman Kumar Singh) wrote…</i></summary><blockquote>

We have already used accumulatedGradients in optimizer.ts's after example, so it may be confusing. Here, we are storing sum of gradient squares so, we can use something like accumulatedSquaredGradients and for rmsprop we have discounted prev cache , so we can use accumulatedDiscountedSquaredGradients or accumulatedSquaredGradients only. What do you think ?
</blockquote></details>

Ah, got it. accumulatedSquaredGradients sounds good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/102#-:-Kti99YhJKGvcMNZu9A0:ba0ocst)*

**Comment by nsthorat** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/adagrad_optimizer.ts, line 1 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/102#-Ktlc-SN6ftp4W6Z76iC:-Ktlc-SN6ftp4W6Z76iD:b-ue9a0t) ([raw file](https://github.com/pair-code/deeplearnjs/blob/c9b33872f96a119c85a7df51050e42d8b68bfe58/src/adagrad_optimizer.ts#L1)):*
> ```XML
> /* Copyright 2017 Google Inc. All Rights Reserved.
> ```

quick update, this license format slightly changed, can you update it (after merging)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/102)*

**Comment by mnottheone** [comment]
Please review them and let me know anything left. I guess, now I have clang-format setting right \m/ :)

**Comment by nsthorat** [comment]
Haha, unfortunately this indentation is still because clang-format isn't quite set up properly (it's not formatting with clang, it's formatting with the vscode settings). Do you have both the command line clang-format tool and the visual studio code extension installed?

Sorry to be pedantic, it's just important to have consistent looking code :)

---

Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/102#-:-KuAUFGmlxT1uTrtfMCb:b-3wil7q)*

**Comment by nsthorat** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/rmsprop_optimizer.ts, line 36 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/102#-KtXSbaIux_nhHalYcxz:-KuAUjvTsGbHvJWjBpkA:bt04qaz) ([raw file](https://github.com/pair-code/deeplearnjs/blob/b0a117537784c68a9333fd82899923b5183b8aec/src/rmsprop_optimizer.ts#L36)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

Ah, got it. accumulatedSquaredGradients sounds good.
</blockquote></details>

Still need to change from cache :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/102)*

**Comment by mnottheone** [comment]
Hopefully, okay now.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/102#-:-KuAdC8V6LFFDvYG7Wtc:b8gvn2f)*

**Comment by nsthorat** [comment]
One more tiny comment then I will merge, thanks for bearing with me :)

---

Reviewed 2 of 8 files at r3, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/index.ts, line 1 at r4](https://reviewable.io:443/reviews/pair-code/deeplearnjs/102#-KuAdkgadiTc1ONRnQQP:-KuAdkgbV-rxPTUMQ0y2:b-8m2ihb) ([raw file](https://github.com/pair-code/deeplearnjs/blob/41b9ff1658a32bff1f9946b2191cf779952523db/src/index.ts#L1)):*
> ```XML
> /**
> ```

open this file and hit save to format so we dont commit these old formatter changes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/102#-:-KuAe1nVgIElUzBHo36X:b8b7vtm)*

**Comment by nsthorat** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/102)*

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/102#-:-KuAfFF-4RDJ6jGBud7e:b-jbsf8z)*

**Comment by mnottheone** [comment]
Thanks !  :) 

Next things to do : 
- Implement Adadelta, Adam, and Adamax.
- Add documentation in API docs for new optimizers.

You can add or change anything, you want.

**Comment by nsthorat** [comment]
Awesome! BTW, I'm about to do a big directory structure change (optimizers in a directory, etc). You can start working on those, but just know merging will be.. fun ;)

We'll update the API docs with your new optimizers since it's automatically generated.

**Pull request merged**
