### PR TITLE
Support add broadcast in graph (2d, 1d)

### PR DESCRIPTION
**Pull request by minsukkahng**
This update enables to do add broadcasting in graph. Currently, it supports two basic, typical cases that can be used for batch computation: 
- Add(Array2D (shape: n, m), Array1D (shape: m))
- Add(Array1D (shape: m), Array2D (shape: n, m))

It can be used for implementing batch computation of bias addition.

Thank you for your review!
Minsuk Kahng

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/364)

### CODE REVIEW

**Comment by nsthorat** [comment]
Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/graph/graph.ts, line 533 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/364#-KzOsMSrqTFdYftnN-_e:-KzOsMSrqTFdYftnN-_f:b-efai9d) ([raw file](https://github.com/pair-code/deeplearnjs/blob/73ae0ed20fa8ea6805c73c44e50bab1a1d42ca67/src/graph/graph.ts#L533)):*
> ```XML
>             util.sizeFromShape(this.t2.shape) === 1 ||
>             util.arraysEqual(this.t1.shape, this.t2.shape) ||
>             this.t1.shape.length === 2 && this.t2.shape.length === 1 &&
> ```

looks like you need parens? Also, it's strange that we don't allow the mirror (t2.shape.length === 2)

also, use ndarray.rank

---

*[src/graph/graph_test.ts, line 232 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/364#-KzOs9Be3koMGQB7Uy1E:-KzOs9Be3koMGQB7Uy1F:b-a2vczz) ([raw file](https://github.com/pair-code/deeplearnjs/blob/73ae0ed20fa8ea6805c73c44e50bab1a1d42ca67/src/graph/graph_test.ts#L232)):*
> ```XML
>   });
> 
>   it('Special broadcast case does not throw', () => {
> ```

be a little bit more explicity with "special"

---

*[src/graph/graph_test.ts, line 236 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/364#-KzOsCRhQqZEMqNAsjHb:-KzOsCRhQqZEMqNAsjHc:bpvf3nu) ([raw file](https://github.com/pair-code/deeplearnjs/blob/73ae0ed20fa8ea6805c73c44e50bab1a1d42ca67/src/graph/graph_test.ts#L236)):*
> ```XML
>   });
> 
>   it('Another different shapes throws', () => {
> ```

how about 'non-matching broadcast'

---

*[src/graph/ops/add.ts, line 85 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/364#-KzOt1WPKITeMhqO-97t:-KzOt1WPKITeMhqO-97u:b-1ef7c6) ([raw file](https://github.com/pair-code/deeplearnjs/blob/73ae0ed20fa8ea6805c73c44e50bab1a1d42ca67/src/graph/ops/add.ts#L85)):*
> ```XML
>       }
> 
>       // Special broadcast case. Need to be generalized later.
> ```

make sure you cover the mirror case

---

*[src/graph/ops/add.ts, line 90 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/364#-KzOsb4SYER0EbMAmvUh:-KzOsb4SYER0EbMAmvUi:b-rejp7u) ([raw file](https://github.com/pair-code/deeplearnjs/blob/73ae0ed20fa8ea6805c73c44e50bab1a1d42ca67/src/graph/ops/add.ts#L90)):*
> ```XML
>           this.x1Tensor.shape[1] === this.x2Tensor.shape[0] &&
>           graph_util.shouldBackProp(this.x2Tensor)) {
>         const oneForSum = Array2D.zeros([1, this.x1Tensor.shape[0]]);
> ```

constructing new arrays is really slow, can't this be done as functions of other ops without constructing a new NDArray and uploading?

---

*[src/graph/ops/add_test.ts, line 210 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/364#-KzOt-C95jwnv1XDdrV5:-KzOt-C95jwnv1XDdrV6:bqx6ynr) ([raw file](https://github.com/pair-code/deeplearnjs/blob/73ae0ed20fa8ea6805c73c44e50bab1a1d42ca67/src/graph/ops/add_test.ts#L210)):*
> ```XML
>     addOp.feedForward(math, activations);
>     const yVal = activations.get(y);
>     
> ```

remove blank line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/364)*

**Comment by minsukkahng** [comment]
Thanks for your review and great suggestions. I have addressed all your comments!

---

Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/graph/graph.ts, line 533 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/364#-KzOsMSrqTFdYftnN-_e:-KzS42jcEEnps44iHtWz:ba18a15) ([raw file](https://github.com/pair-code/deeplearnjs/blob/73ae0ed20fa8ea6805c73c44e50bab1a1d42ca67/src/graph/graph.ts#L533)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

looks like you need parens? Also, it's strange that we don't allow the mirror (t2.shape.length === 2)

also, use ndarray.rank
</blockquote></details>

Added the mirror case.
I don't think we can use rank here, as it is Tensor, not NDArray.

---

*[src/graph/graph_test.ts, line 232 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/364#-KzOs9Be3koMGQB7Uy1E:-KzS4OZ5bYLMs37lqdSS:biay2zs) ([raw file](https://github.com/pair-code/deeplearnjs/blob/73ae0ed20fa8ea6805c73c44e50bab1a1d42ca67/src/graph/graph_test.ts#L232)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

be a little bit more explicity with "special"
</blockquote></details>

I agree. Removed special and rephrased.

---

*[src/graph/graph_test.ts, line 236 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/364#-KzOsCRhQqZEMqNAsjHb:-KzS4VyNocZk612ENdTo:b-ido4d0) ([raw file](https://github.com/pair-code/deeplearnjs/blob/73ae0ed20fa8ea6805c73c44e50bab1a1d42ca67/src/graph/graph_test.ts#L236)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

how about 'non-matching broadcast'
</blockquote></details>

Good suggestion.

---

*[src/graph/ops/add.ts, line 85 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/364#-KzOt1WPKITeMhqO-97t:-KzS4aI14v0I1uoR5HHB:b-lw0prs) ([raw file](https://github.com/pair-code/deeplearnjs/blob/73ae0ed20fa8ea6805c73c44e50bab1a1d42ca67/src/graph/ops/add.ts#L85)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

make sure you cover the mirror case
</blockquote></details>

I added the mirror case.

---

*[src/graph/ops/add.ts, line 90 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/364#-KzOsb4SYER0EbMAmvUh:-KzS4emrW_DQAGGKcTPb:b75hi41) ([raw file](https://github.com/pair-code/deeplearnjs/blob/73ae0ed20fa8ea6805c73c44e50bab1a1d42ca67/src/graph/ops/add.ts#L90)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

constructing new arrays is really slow, can't this be done as functions of other ops without constructing a new NDArray and uploading?
</blockquote></details>

I realized that you already have sum by axis! Replaced with it.

---

*[src/graph/ops/add_test.ts, line 210 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/364#-KzOt-C95jwnv1XDdrV5:-KzS56_ZEpsCRF5rV6rF:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/73ae0ed20fa8ea6805c73c44e50bab1a1d42ca67/src/graph/ops/add_test.ts#L210)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

remove blank line
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/364#-:-KzS5JjhuMc52KFRmVse:b65zih8)*

**Comment by minsukkahng** [comment]
Thanks for your review! Revised code based on your comments and left my comments on Reviewable.

**Comment by nsthorat** [comment]
Almost there, last 2 comments :)

---

Reviewed 1 of 4 files at r2.
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/graph/ops/add.ts, line 98 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/364#-Kzjyq36Bui8l76gZOy5:-Kzjyq36Bui8l76gZOy6:b-updase) ([raw file](https://github.com/pair-code/deeplearnjs/blob/d28ffb15915ebd0699b208476f5aec9488cce221/src/graph/ops/add.ts#L98)):*
> ```XML
>             this.x1Tensor.shape[1] === this.x2Tensor.shape[0]) {
>           const sum = math.sum(dy as Array2D, 0);
>           const gradient = math.divide(sum, Scalar.new(this.x1Tensor.shape[0]));
> ```

This new scalar should be created in the constructor of the operation, otherwise this will be a memory leak (it never gets cleaned up)

---

*[src/graph/ops/add.ts, line 99 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/364#-KzjzEy9eRBfmMnMP-Ua:-KzjzEy9eRBfmMnMP-Ub:b-l1saqm) ([raw file](https://github.com/pair-code/deeplearnjs/blob/d28ffb15915ebd0699b208476f5aec9488cce221/src/graph/ops/add.ts#L99)):*
> ```XML
>           const sum = math.sum(dy as Array2D, 0);
>           const gradient = math.divide(sum, Scalar.new(this.x1Tensor.shape[0]));
>           gradientArrays.add(this.x2Tensor, gradient);
> ```

I don't think this is correct for the mirror case (it seems like only one of the cases).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/364#-:-Kzjzf5l9TMMJv5PGoVS:b-823d76)*

**Comment by minsukkahng** [comment]
Thanks for your review. I've revised code and left inline comments.

---

Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/graph/ops/add.ts, line 85 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/364#-KzOt1WPKITeMhqO-97t:-KzklehG2LA6prpb9RPP:b-qshj0u) ([raw file](https://github.com/pair-code/deeplearnjs/blob/73ae0ed20fa8ea6805c73c44e50bab1a1d42ca67/src/graph/ops/add.ts#L85)):*
<details><summary><i>Previously, minsukkahng (Minsuk Kahng) wrote…</i></summary><blockquote>

I added the mirror case.
</blockquote></details>

Please see line 75 and my new comments below.

---

*[src/graph/ops/add.ts, line 98 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/364#-Kzjyq36Bui8l76gZOy5:-Kzkjc3XD1LFnjzGqg87:b-ul5lz2) ([raw file](https://github.com/pair-code/deeplearnjs/blob/d28ffb15915ebd0699b208476f5aec9488cce221/src/graph/ops/add.ts#L98)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

This new scalar should be created in the constructor of the operation, otherwise this will be a memory leak (it never gets cleaned up)
</blockquote></details>

Thanks for this comment. Revised code based on how you guys did for other similar cases.

---

*[src/graph/ops/add.ts, line 99 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/364#-KzjzEy9eRBfmMnMP-Ua:-KzkjraRMO5dCs1mB8Ra:b3tebuj) ([raw file](https://github.com/pair-code/deeplearnjs/blob/d28ffb15915ebd0699b208476f5aec9488cce221/src/graph/ops/add.ts#L99)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

I don't think this is correct for the mirror case (it seems like only one of the cases).
</blockquote></details>

Hmm, not sure what you are saying. Yes, the two cases I'm handling do not cover all possible broadcast cases. As we discussed, we can do that later. For now, it can handle [a, b] + [b] and [b] + [a, b], which covers typical, basic batch computation scenarios. We may generalize it later based on how Daniel implemented broadcast_util for math. If you think, there is an error in gradient computation, let me know. You can also check out test cases I added.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/364#-:-KzklBq-jC3IAhy5oKAG:b-mivtp3)*

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: 1 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/364#-:-Kzo2A2mXHCfqWyS7Di5:b-jbsf8z)*

**Pull request merged**
