### PR TITLE
Clone input for reshape nodes on the graph.

### PR DESCRIPTION
**Pull request by nsthorat**
This also adds some tooling to track down disposed textures. We now show meaningful errors when trying to use disposed NDArrays.

This fixes https://github.com/PAIR-code/deeplearnjs/issues/337

This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/341)

### CODE REVIEW

**Comment by reiinakano** [comment]
Oh, I faced this issue when I was building gan playground but had no idea if I was just doing something dumb and decided to just hack a workaround and wait for eager mode. Sorry for not reporting sooner!

**Comment by nsthorat** [comment]
@reiinakano no problem at all :)

**Comment by dsmilkov** [comment]
:lgtm_strong:

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/math/ndarray.ts, line 420 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/341#-KyqUPvQHRvDI4Zo-yXv:-KyqUPvQHRvDI4Zo-yXw:b-4o7pkd) ([raw file](https://github.com/pair-code/deeplearnjs/blob/c4cec2eb99efd0d5b43448a9acf72e93a0c8a281/src/math/ndarray.ts#L420)):*
> console.error(`NDArray is disposed.`);

Throw new Error instead, since we want users to be able to try/catch it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/341#-:-KyqUieC9qk-3-tkSdyR:b-jbsf8z)*

**Comment by nsthorat** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[src/math/ndarray.ts, line 420 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/341#-KyqUPvQHRvDI4Zo-yXv:-KyqVyBlFrP1uHUSsvcG:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/c4cec2eb99efd0d5b43448a9acf72e93a0c8a281/src/math/ndarray.ts#L420)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

> console.error(`NDArray is disposed.`);

Throw new Error instead, since we want users to be able to try/catch it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/341)*

**Pull request merged**
