### PR TITLE
switchDim for GPU

### LINKED ISSUE #132: math.switchDimInternal() is showing "Not yet implemented!". How to transpose a matrix if switchDimInternal isn't implemented yet?
Is there any other way to transpose a matrix in deeplearn?

### PR DESCRIPTION
**Pull request by reiinakano**
Fixes #132 

I took a shot at implementing `switchDim` in GPU. For testing, I just copied the test from @dsmilkov's #167 and uncommented the GPU tests. I would also be willing to merge this into #167 instead since they overlap a bit (looks like it's renamed to `transpose`).

Since tests pass on my local, I think this is ready for review.

PS: How do I select only specific tests to run? It takes me a full minute to verify if a small edit I make breaks the relevant test.

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/195)

### CODE REVIEW

**Comment by dsmilkov** [comment]
:lgtm_strong: Awesome work. I'll let you sync to master and submit this PR first. Then I'll merge and continue the work on #167 (this contribution helps me push #167 further. Thank you!

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/math/webgl/switch_dim_gpu.ts, line 34 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/195#-KwI2qQjZC-vVLLFGQf0:-KwI2qQjZC-vVLLFGQf1:btnb339) ([raw file](https://github.com/pair-code/deeplearnjs/blob/e2d8277c4e924325f0064c0a58b105e5519afc5b/src/math/webgl/switch_dim_gpu.ts#L34)):*
> ```XML
>     }
>     this.outputShape = outputShape;
>     this.rank = outputShape.length;
> ```

add `this.params = [newDim.toString()];` since the permutation should be a parameter of the shader.

---

*[src/math/webgl/switch_dim_gpu.ts, line 55 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/195#-KwI40CGKe2arneaNhYs:-KwI40CGKe2arneaNhYt:b-pcgc83) ([raw file](https://github.com/pair-code/deeplearnjs/blob/e2d8277c4e924325f0064c0a58b105e5519afc5b/src/math/webgl/switch_dim_gpu.ts#L55)):*
> switchedCoords[newDim[i]] = (originalOrder[i])

no need to wrap `originalOrder[i]` in `()`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/195#-:-KwI5gw1QzoGaotAu4j-:b-fu9tug)*

**Comment by dsmilkov** [comment]
Forgot to mention. I left 2 comments on reviewable. They are tiny and let me know when you sync the branch and address them and I'll push this to master

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/195#-:-KwI68UdNWrEjQoUBtc5:b-6fe4u7)*

**Comment by reiinakano** [comment]
Done! Also switched tests to use `test_util.expectArraysClose`

**Comment by dsmilkov** [comment]
Sweet! Merged. Thank you!

**Pull request merged**
