### PR TITLE
update demos package.json/yarn.lock to deeplearn-0.4.2

### PR DESCRIPTION
**Pull request by tafsiri**
The typings were fixed in #558, this updates the package.json dependency to match.

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/565)

### CODE REVIEW

**Comment by nsthorat** [comment]
Don't forget to sign the CLA

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[demos/package.json, line 55 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/565#-L3FEYKF1lkSpbgnvkuw:-L3FEYKGk5vf3Biun2JB:b437mtf) ([raw file](https://github.com/pair-code/deeplearnjs/blob/514cdee0a0a609a3439541e90406af7b8a1614b0/demos/package.json#L55)):*
> ```JSON
>     "@bower_components/webcomponentsjs": "webcomponents/webcomponentsjs#^0.7.24",
>     "chart.js": "~2.7.1",
>     "deeplearn": "~0.4.2",
> ```

don't we need to update that benchmark demo as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/565#-:-L3FEhGl8Sf7AcEgvEY-:byvi7rh)*

**Comment by dsmilkov** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[demos/package.json, line 55 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/565#-L3FEYKF1lkSpbgnvkuw:-L3J1VvayszknStb3-ri:b-ayf7qo) ([raw file](https://github.com/pair-code/deeplearnjs/blob/514cdee0a0a609a3439541e90406af7b8a1614b0/demos/package.json#L55)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

don't we need to update that benchmark demo as well?
</blockquote></details>

Actually we don't. demos at master are fixed but only if you have 0.4.2. When I updated demos, I happened to have 0.4.2 installed, because I had reran `yarn` after `rm -r demos/node_modules` and yarn picked up `0.4.2` since it's compatible with `~0.4.1`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/565)*

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/565#-:-L3P_ikkq_kdsdLzQu_y:b-jbsf8z)*

**Comment by tafsiri** [comment]
I signed it! 

(the cla)

**Pull request merged**
