### PR TITLE
api docs integration

### PR DESCRIPTION
**Pull request by tafsiri**
some visual tweaks & bug fixes
add google analytics.
integrate new api into site build

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/724)

### CODE REVIEW

**Comment by tafsiri** [comment]
FYI to preview the site with docs built against master, run ./scripts/make-website.sh --master

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/724#-:-L5LcBYZqO1hStFKx-WV:b-jbsf8z)*

**Comment by dsmilkov** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[scripts/make-website.sh, line 29 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/724#-L5LiQEEEFY10Nhy6J23:-L5LiQEEEFY10Nhy6J24:bganh7o) ([raw file](https://github.com/pair-code/deeplearnjs/blob/e8b9858bccf2ea92c8cc1c075b15a16df7f6c82b/scripts/make-website.sh#L29)):*
> ```Shell
> 
> # Make the documentation.
> ./node_modules/.bin/ts-node ./website/scripts/make-api.ts -o $TMP_DIR/docs/api/ $1
> ```

remove typedoc from package.json and run yarn to update yarn.lock file

---

*[website/api/index.html, line 351 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/724#-L5Li6NRXsL3QFIegbep:-L5Li6NRXsL3QFIegbeq:b-oovu9a) ([raw file](https://github.com/pair-code/deeplearnjs/blob/e8b9858bccf2ea92c8cc1c075b15a16df7f6c82b/website/api/index.html#L351)):*
> ```HTML
>           }
>           tocFound.classList.add('highlighted');
>           // tocFound.scrollIntoView(false);
> ```

any reason to keep it as comment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/724)*

**Comment by tafsiri** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[scripts/make-website.sh, line 29 at r1](https://beta.reviewable.io/reviews/pair-code/deeplearnjs/724#-L5LiQEEEFY10Nhy6J23:-L5OtV_j2frz7jcWQTbD:bb6un1j) ([raw file](https://github.com/pair-code/deeplearnjs/blob/e8b9858bccf2ea92c8cc1c075b15a16df7f6c82b/scripts/make-website.sh#L29)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

remove typedoc from package.json and run yarn to update yarn.lock file
</blockquote></details>

Done

---

*[website/api/index.html, line 351 at r1](https://beta.reviewable.io/reviews/pair-code/deeplearnjs/724#-L5Li6NRXsL3QFIegbep:-L5OtWN487aOL8HPVgXa:b-9kcix3) ([raw file](https://github.com/pair-code/deeplearnjs/blob/e8b9858bccf2ea92c8cc1c075b15a16df7f6c82b/website/api/index.html#L351)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

any reason to keep it as comment?
</blockquote></details>

mostly as a reminder to myself to think of a way to try and restore this functionality

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/pair-code/deeplearnjs/724)*

**Pull request merged**
