### PR TITLE
Updates .npmignore to ignore website and other files

### PR DESCRIPTION
**Pull request by ManrajGrover**
This PR cleans up npm package removing not-so important files.

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/747)

### CODE REVIEW

**Comment by nsthorat** [comment]
Hi @ManrajGrover, it looks like all these files are important :)

website/ is where we develop the website, .gitignore can't be ignored (or we will never check it in), yarn.lock should be checked in, and the other files we want to be able to work on.

**Comment by ManrajGrover** [comment]
Hi @nsthorat, :)

I believe these files should not be sent to user when they install our package. Hence, I've updated the `npmignore` file and not `gitignore`

**Comment by nsthorat** [comment]
Ah, apologies! Pre-coffee :)

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/747#-:-L5_6D982Uagf7648vyv:b-jbsf8z)*

**Pull request merged**
