### PR TITLE
add math.gather

### PR DESCRIPTION
**Pull request by reiinakano**
Resubmission #327 

Sorry for the late resubmission, I just moved to another country so it took a while for things to settle down.

Let me know if I missed anything, I didn't read the code too much this time around.

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/546)

### CODE REVIEW

**Comment by dsmilkov** [comment]
Really nice work! Left a few comments, the only bigger thing is to change the signature of gather to take `indices: Array1D<'int32'>` in case those indices came as a result from another math operation.

---

Reviewed 1 of 8 files at r1.
Review status: 1 of 8 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[src/math/gather_test.ts, line 33 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/546#-L2uGsF8SeaP3kgI3QuO:-L2uGsF9rOREoidrVRz5:b-ioqzne) ([raw file](https://github.com/pair-code/deeplearnjs/blob/c5c6f3655f4a9a5cabb4c2bcfdc80adac8080c2c/src/math/gather_test.ts#L33)):*
> new Float32Array

remove `getValues()` and `new Float32Array` here and elsewhere where you call test_util. We've updated the test_util so now you can write:
```ts
test_util.expectArraysClose(t2, [1, 3, 1, 2]);
```

---

*[src/math/gather_test.ts, line 35 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/546#-L2uHDV3opwS4unVbUGI:-L2uHDV4V8w5HwzdRZgD:b7stbk1) ([raw file](https://github.com/pair-code/deeplearnjs/blob/c5c6f3655f4a9a5cabb4c2bcfdc80adac8080c2c/src/math/gather_test.ts#L35)):*
> ```XML
>         new Float32Array([1, 3, 1, 2]));
> 
>       t.dispose();
> ```

Remove all calls to `.dispose()`. Now that we have global tracking, all arrays are disposed automatically at the end of each test.

---

*[src/math/gather_test.ts, line 75 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/546#-L2uIG81GJOzYUnRpLA1:-L2uIG81GJOzYUnRpLA2:bxd3m85) ([raw file](https://github.com/pair-code/deeplearnjs/blob/c5c6f3655f4a9a5cabb4c2bcfdc80adac8080c2c/src/math/gather_test.ts#L75)):*
> uint

replace `uint` with `int32`

---

*[src/math/math.ts, line 1102 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/546#-L2uITShvRyKBYVf1Ic0:-L2uITShvRyKBYVf1Ic1:b1ta4c7) ([raw file](https://github.com/pair-code/deeplearnjs/blob/c5c6f3655f4a9a5cabb4c2bcfdc80adac8080c2c/src/math/math.ts#L1102)):*
> ```XML
>  * @param x The array to transpose.
>  * @param indices The indices of the values to extract.
>  * @param axis Optional. The axis over which to select values.
> ```

append in the jsdoc: `Defaults to 0.`

---

*[src/math/math.ts, line 1105 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/546#-L2uIZfJUBsrxHfcLrKD:-L2uIZfJUBsrxHfcLrKE:bijutcm) ([raw file](https://github.com/pair-code/deeplearnjs/blob/c5c6f3655f4a9a5cabb4c2bcfdc80adac8080c2c/src/math/math.ts#L1105)):*
> ```XML
>  */
>   gather<D extends DataType, T extends NDArray<D>>(
>       x: T, indices: number[], axis?: number): T {
> ```

you can default to 0 here directly: `..., axis = 0): T { ...`

---

*[src/math/math.ts, line 1105 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/546#-L2uKY6PyJlM7bg4mZ55:-L2uKY6PyJlM7bg4mZ56:ba95qjv) ([raw file](https://github.com/pair-code/deeplearnjs/blob/c5c6f3655f4a9a5cabb4c2bcfdc80adac8080c2c/src/math/math.ts#L1105)):*
> indices: number[]

change to `indices: Array1D<'int32'>`. This way you allow indices to be the result of another GPU operation, without having the user to download to cpu.

---

*[src/math/backends/backend_cpu.ts, line 1211 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/546#-L2uJ_sDdA4mnp_gmKIe:-L2uJ_sDdA4mnp_gmKIf:b-pkgqoy) ([raw file](https://github.com/pair-code/deeplearnjs/blob/c5c6f3655f4a9a5cabb4c2bcfdc80adac8080c2c/src/math/backends/backend_cpu.ts#L1211)):*
> ```XML
>     }
>     const resultValues = new dtype(util.sizeFromShape(newShape));
>     const result = NDArray.make(newShape, {values: resultValues}, x.dtype) as T;
> ```

you can avoid the dtype if/switch logic, if you do:
```ts
const result = NDArray.zeros(newShape, x.dtype);
const resultValues = result.dataSync(); // getValues is deprecated
```

---

*[src/math/backends/backend_webgl.ts, line 436 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/546#-L2uKE-7gN6NBsOGsjjt:-L2uKE-7gN6NBsOGsjju:b71m38e) ([raw file](https://github.com/pair-code/deeplearnjs/blob/c5c6f3655f4a9a5cabb4c2bcfdc80adac8080c2c/src/math/backends/backend_webgl.ts#L436)):*
> ```XML
>   gather<D extends DataType, T extends NDArray<D>>(
>       x: T, indices: number[], axis: number): T {
>     const indicesArray = Array1D.new(indices, 'int32');
> ```

Note that we never create arrays in `backend_webgl.ts`, other than the resulting array where we store the output of the program.

This is so that we don't force the user to provide cpu values, especially if those values were the result of a previous gpu operation. Change the signature of `gather` in `backend.ts` and `math.ts` to take `indices: Array1D<'int32'>`

---

*[src/math/backends/webgl/gather_gpu.ts, line 47 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/546#-L2uLPf2yPOuunEQGQJ2:-L2uLPf2yPOuunEQGQJ3:b-kinnhj) ([raw file](https://github.com/pair-code/deeplearnjs/blob/c5c6f3655f4a9a5cabb4c2bcfdc80adac8080c2c/src/math/backends/webgl/gather_gpu.ts#L47)):*
> Tile

did you mean `Gather` instead of `Tile`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/546#-:-L2uLUOf56QijOiq6Vnb:bzebvc6)*

**Comment by reiinakano** [comment]
Comments addressed. Let me know if I did the kernel thing right.

**Comment by dsmilkov** [comment]
Just one more comment and we are good to go! See below

---

Reviewed 2 of 9 files at r3.
Review status: 2 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/math/backends/backend_webgl.ts, line 436 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/546#-L2zxRTJCOd3MUkQYWAZ:-L2zxRTJCOd3MUkQYWA_:b453b41) ([raw file](https://github.com/pair-code/deeplearnjs/blob/2479bd62dae7f65b3a98afcc0158bb58fc1b5043/src/math/backends/backend_webgl.ts#L436)):*
> ```XML
>   gather<D extends DataType, T extends NDArray<D>>(
>       x: T, indices: Array1D<'int32'>, axis: number): T {
>     const program = new GatherProgram(x.shape, indices.dataSync().length, axis);
> ```

`indices.dataSync().length` would cause a gpu download (readpixels) which degrades perf. You can get the length directly using `indices.size`.

We want to avoid any `data()/dataSync()` calls when in `backend_webgl.ts`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/546#-:-L2zxdx9jfA6WzjwyaBP:b-e0k1dj)*

**Comment by reiinakano** [comment]
Done

**Comment by dsmilkov** [comment]
:lgtm_strong:

---

Review status: 2 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/546#-:-L34h9lIG3NWXNu80TO4:b-jbsf8z)*

**Pull request merged**
