### PR TITLE
Comparison Operators: Adds greater comparison operator

### PR DESCRIPTION
**Pull request by ManrajGrover**
This PR adds greater operator for NDArrays which can be used as `math.greater(a, b)`.

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/547)

### CODE REVIEW

**Comment by dsmilkov** [comment]
:lgtm_strong: Nice work. No comments. I'll let you merge with master (you'll have conflict with #542) . Reply when done, and I'll merge!

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/547#-:-L2pSprrZS7Od-FOjuVn:b-oah80p)*

**Comment by dsmilkov** [comment]
Merged the other one!

**Comment by dsmilkov** [comment]
:lgtm_strong:

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/547#-:-L2pnP7KS57_GNstGbP2:b-jbsf8z)*

**Comment by ManrajGrover** [comment]
@dsmilkov Should we add `Strict` versions of comparison operators, like `greaterStrict`?

**Comment by dsmilkov** [comment]
Yes, that would be great for consistency. Feel free to add all the missing strict in one PR.

**Pull request merged**
