### PR TITLE
Do not check window object for URL parameters if window is not defined

### PR DESCRIPTION
**Pull request by arthurjdam**
Otherwise it will error and break when running a NodeJS environment

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/155)

### CODE REVIEW

**Comment by arthurjdam** [comment]
Updated e-mail address! That should do the trick

**Comment by arthurjdam** [comment]
@googlebot done

**Comment by nsthorat** [comment]
Thanks for this contribution! One small style comment and I will merge :)

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/environment.ts, line 142 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/155#-Kv2v22ZU2hwISdKhAAn:-Kv2v22ZU2hwISdKhAAo:b85s7k4) ([raw file](https://github.com/pair-code/deeplearnjs/blob/7c76d27a9d4cffd4ab5cdcb5f617d34448d783ea/src/environment.ts#L142)):*
> ```XML
>   const features: Features = {};
> 
>   if(typeof window === 'undefined') return features;
> ```

Could you format it like this:

`
if (typeof window === 'undefined') {
  return features;
}
`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/155#-:-Kv2vBizurXYkZcFifeM:br1usai)*

**Comment by nsthorat** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/environment.ts, line 142 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/155#-Kv2v22ZU2hwISdKhAAn:-Kv2vFskC3563g6vaFd1:b-h9t6pw) ([raw file](https://github.com/pair-code/deeplearnjs/blob/7c76d27a9d4cffd4ab5cdcb5f617d34448d783ea/src/environment.ts#L142)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

Could you format it like this:

`
if (typeof window === 'undefined') {
  return features;
}
`
</blockquote></details>

Oops, markdown doesn't like me. Make sure "return features" is on its own line, indented.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/155)*

**Comment by arthurjdam** [comment]
Good call!

**Comment by nsthorat** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/environment.ts, line 142 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/155#-Kv2v22ZU2hwISdKhAAn:-Kv3kPt7Ks-c8p_5nTpV:bjq2vw6) ([raw file](https://github.com/pair-code/deeplearnjs/blob/e3989b1c22c47fd5989fd51de01a0959f63e28e9/src/environment.ts#L142)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

Oops, markdown doesn't like me. Make sure "return features" is on its own line, indented.
</blockquote></details>

Linter CI will fail because of the trailing two spaces after the "}". I'll merge after that! 

Sorry to be picky :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/155)*

**Comment by arthurjdam** [comment]
*[src/environment.ts, line 142 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/155#-Kv2v22ZU2hwISdKhAAn:-Kv3tJHjnGSHT2Fu74tZ:bsnvgdx) ([raw file](https://github.com/pair-code/deeplearnjs/blob/e3989b1c22c47fd5989fd51de01a0959f63e28e9/src/environment.ts#L142)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

Linter CI will fail because of the trailing two spaces after the "}". I'll merge after that! 

Sorry to be picky :)
</blockquote></details>

Fair enough! :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/155)*

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/155#-:-KvJYcj2hbs-4UwE57Le:b-jbsf8z)*

**Pull request merged**
