### PR TITLE
Add the logicalOr() operator

### PR DESCRIPTION
**Pull request by nkreeger**
Support vectorized logicalOr() op in deeplearnjs. Should match the TF API: https://www.tensorflow.org/api_docs/python/tf/logical_or

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/539)

### CODE REVIEW

**Comment by dsmilkov** [comment]
Review status: 0 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/math/logical_ops_test.ts, line 52 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/539#-L2bfpbZRK3a0uotfALc:-L2bfpbZRK3a0uotfALd:b-hg1u2e) ([raw file](https://github.com/pair-code/deeplearnjs/blob/fcfcea98e2e847a1efd3d63cd0cd11b471217fe6/src/math/logical_ops_test.ts#L52)):*
> ```XML
>     });
>     it('Should handle mismatched Array1D types', math => {
>       const a = Array1D.new([1, 0, 0], 'int32');
> ```

looks like tf.bool forces both inputs to be dtype of `bool`. Let's follow that.

---

*[src/math/math.ts, line 763 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/539#-L2bfKcJjryFwuIhgyhv:-L2bfKcJjryFwuIhgyhw:bow7cny) ([raw file](https://github.com/pair-code/deeplearnjs/blob/fcfcea98e2e847a1efd3d63cd0cd11b471217fe6/src/math/math.ts#L763)):*
> ```XML
>    * Returns the truth value of a OR b element-wise. Supports broadcasting.
>    *
>    * @param a The first input `NDArray`.
> ```

append '... of type `bool`' at the end of @param a and @param b

---

*[src/math/math.ts, line 764 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/539#-L2bfSt-82vIkX1pmHvr:-L2bfSt-82vIkX1pmHvs:byy2lfb) ([raw file](https://github.com/pair-code/deeplearnjs/blob/fcfcea98e2e847a1efd3d63cd0cd11b471217fe6/src/math/math.ts#L764)):*
> Must have the same dtype as `a`

no need to say this

---

*[src/math/math.ts, line 766 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/539#-L2bfWEMBdLiTKSAn-B8:-L2bfWEMBdLiTKSAn-B9:brpx9vs) ([raw file](https://github.com/pair-code/deeplearnjs/blob/fcfcea98e2e847a1efd3d63cd0cd11b471217fe6/src/math/math.ts#L766)):*
> ```XML
>    * @param b The second input `NDArray`. Must have the same dtype as `a`.
>    */
>   logicalOr(a: NDArray, b: NDArray): NDArray<'bool'> {
> ```

type it as `a: NDArray<'bool'>` , same for `b`, to follow tf.logical_or

---

*[src/math/math.ts, line 767 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/539#-L2bfcQ6gYbUngobCmEn:-L2bfcQ6gYbUngobCmEo:b39jwey) ([raw file](https://github.com/pair-code/deeplearnjs/blob/fcfcea98e2e847a1efd3d63cd0cd11b471217fe6/src/math/math.ts#L767)):*
> ```XML
>    */
>   logicalOr(a: NDArray, b: NDArray): NDArray<'bool'> {
>     util.assertTypesMatch(a, b);
> ```

assert that dtype is exactly `bool`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/539)*

**Comment by nkreeger** [comment]
Review status: 0 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/math/logical_ops_test.ts, line 52 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/539#-L2bfpbZRK3a0uotfALc:-L2cI_L_x0dkJul_VS5S:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/fcfcea98e2e847a1efd3d63cd0cd11b471217fe6/src/math/logical_ops_test.ts#L52)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

looks like tf.bool forces both inputs to be dtype of `bool`. Let's follow that.
</blockquote></details>

Done.

---

*[src/math/math.ts, line 763 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/539#-L2bfKcJjryFwuIhgyhv:-L2cIIS6KdV8qdFF5fjU:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/fcfcea98e2e847a1efd3d63cd0cd11b471217fe6/src/math/math.ts#L763)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

append '... of type `bool`' at the end of @param a and @param b
</blockquote></details>

Done.

---

*[src/math/math.ts, line 764 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/539#-L2bfSt-82vIkX1pmHvr:-L2cIJRuPQQFPqTdK4MV:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/fcfcea98e2e847a1efd3d63cd0cd11b471217fe6/src/math/math.ts#L764)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

> Must have the same dtype as `a`

no need to say this
</blockquote></details>

Done.

---

*[src/math/math.ts, line 766 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/539#-L2bfWEMBdLiTKSAn-B8:-L2cIN2pCd6QQNwTwD5U:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/fcfcea98e2e847a1efd3d63cd0cd11b471217fe6/src/math/math.ts#L766)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

type it as `a: NDArray<'bool'>` , same for `b`, to follow tf.logical_or
</blockquote></details>

Done.

---

*[src/math/math.ts, line 767 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/539#-L2bfcQ6gYbUngobCmEn:-L2cIZ0Rqsi3nCwMfvLV:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/fcfcea98e2e847a1efd3d63cd0cd11b471217fe6/src/math/math.ts#L767)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

assert that dtype is exactly `bool`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/539)*

**Comment by nkreeger** [comment]
Addressed all comments - PTAL.

---

Review status: 0 of 8 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/539#-:-L2cKfDu_pEb92OzzQC6:bsi9dgx)*

**Comment by dsmilkov** [comment]
:lgtm_strong: Nice work. Couple minor comments. Feel free to submit

---

Reviewed 2 of 9 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/math/logical_ops_test.ts, line 30 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/539#-L2ceTjzWrVUpXww2Bh8:-L2ceTjzWrVUpXww2Bh9:b-np2ogk) ([raw file](https://github.com/pair-code/deeplearnjs/blob/f1cb1ffa90e0933a3e4e650d9582139335ca7055/src/math/logical_ops_test.ts#L30)):*
> Should handle

optional: remove `should handle` from each test name since it's not necessary

---

*[src/math/math.ts, line 767 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/539#-L2cfFPR8BZBcGVRBaP9:-L2cfFPR8BZBcGVRBaPA:btig99f) ([raw file](https://github.com/pair-code/deeplearnjs/blob/f1cb1ffa90e0933a3e4e650d9582139335ca7055/src/math/math.ts#L767)):*
> ```XML
>    */
>   logicalOr(a: NDArray<'bool'>, b: NDArray<'bool'>): NDArray<'bool'> {
>     util.assert(a.dtype === 'bool', 'Error Array must be of type bool.');
> ```

check for b.dtype === bool too

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/539#-:-L2cf6ktFO5pM61BoK9P:b-3tn6j)*

**Comment by nkreeger** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/math/logical_ops_test.ts, line 30 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/539#-L2ceTjzWrVUpXww2Bh8:-L2ci9aT0S7F9DHw2XQD:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/f1cb1ffa90e0933a3e4e650d9582139335ca7055/src/math/logical_ops_test.ts#L30)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

> Should handle

optional: remove `should handle` from each test name since it's not necessary
</blockquote></details>

Done.

---

*[src/math/math.ts, line 767 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/539#-L2cfFPR8BZBcGVRBaP9:-L2ciABV66_HM8KHbvU2:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/f1cb1ffa90e0933a3e4e650d9582139335ca7055/src/math/math.ts#L767)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

check for b.dtype === bool too
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/539)*

**Pull request merged**
