### PR TITLE
Add fashion MNIST dataset to the model builder!

### PR DESCRIPTION
**Pull request by nsthorat**
Cancel setTimeouts for inference in the graph runner, a race condition can cause two simultaneous loops.

Fix double-normalization bug in model-builder (unnormalize when switching datasets if the dataset is normalized).

Fashion MNIST:
https://github.com/zalandoresearch/fashion-mnist

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/77)

### CODE REVIEW

**Comment by dsmilkov** [comment]
:lgtm_strong:

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[demos/model-builder/model-builder-datasets-config.json, line 33 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/77#-KsexbhPS5DyLYJv4Fqv:-KsexbhPS5DyLYJv4Fqw:b5d4oac) ([raw file](https://github.com/pair-code/deeplearnjs/blob/ee32accd64922b7ed78141aaabba1c2efa7c62f4/demos/model-builder/model-builder-datasets-config.json#L33)):*
> [10]

So cool! So Fashion MNIST also has 10 possible labels?

---

*[demos/model-builder/model-builder.ts, line 418 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/77#-KsexjG3ggbf5atLlwi_:-KsexjG3ggbf5atLlwia:bg4oigd) ([raw file](https://github.com/pair-code/deeplearnjs/blob/ee32accd64922b7ed78141aaabba1c2efa7c62f4/demos/model-builder/model-builder.ts#L418)):*
> ·····

remove trailing space at the end (I'm assuming that's what those red dots are)

---

*[demos/model-builder/model-builder.ts, line 509 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/77#-Ksexsys5DhO_vL9W7zY:-Ksexsys5DhO_vL9W7zZ:bwx5sbj) ([raw file](https://github.com/pair-code/deeplearnjs/blob/ee32accd64922b7ed78141aaabba1c2efa7c62f4/demos/model-builder/model-builder.ts#L509)):*
> ····

same here trailing space

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/77#-:-Ksey0JUti3VvWhiVf9J:b-jbsf8z)*

**Comment by nsthorat** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[demos/model-builder/model-builder-datasets-config.json, line 33 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/77#-KsexbhPS5DyLYJv4Fqv:-KseyjrItwp8dlx1GiPV:bu58prg) ([raw file](https://github.com/pair-code/deeplearnjs/blob/ee32accd64922b7ed78141aaabba1c2efa7c62f4/demos/model-builder/model-builder-datasets-config.json#L33)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

> [10]

So cool! So Fashion MNIST also has 10 possible labels?
</blockquote></details>

Yup, it's supposed to be just a drop in replacement. Lot of chatter about it since MNIST is too easy.

---

*[demos/model-builder/model-builder.ts, line 418 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/77#-KsexjG3ggbf5atLlwi_:-Kseyt9KqUg3mJswBezq:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/ee32accd64922b7ed78141aaabba1c2efa7c62f4/demos/model-builder/model-builder.ts#L418)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

> ·····

remove trailing space at the end (I'm assuming that's what those red dots are)
</blockquote></details>

Done.

---

*[demos/model-builder/model-builder.ts, line 509 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/77#-Ksexsys5DhO_vL9W7zY:-Kseyx08GBhXPXt6gAal:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/ee32accd64922b7ed78141aaabba1c2efa7c62f4/demos/model-builder/model-builder.ts#L509)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

> ····

same here trailing space
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/77)*

**Comment by hanxiao** [comment]
:bowing_man: Many thanks to include fashion-mnist in deeplearn.js. I added a link to readme to your demo: https://github.com/zalandoresearch/fashion-mnist#misc

**Comment by nsthorat** [comment]
No problem, and thanks for adding it to your README! :)

**Pull request merged**
