### PR TITLE
Add the high level norm op

### PR DESCRIPTION
**Pull request by pyu10055**
The norm op is modeled after https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.norm.html,
except that we don't support the any norm that is greater than 2, due to the fact
or pow only supports int32.

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/442)

### CODE REVIEW

**Comment by nsthorat** [comment]
Review status: 0 of 2 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[src/math/math.ts, line 2189 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0Pq4MvhDRjdgMmnJMd:-L0Pq4MvhDRjdgMmnJMe:bmgrurb) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2189)):*
> ```XML
> 
>   /**
>    * Computes the norm of vectors, matrices, and tensors.
> ```

It looks like we dont actually support arbitrary dimensionality

---

*[src/math/math.ts, line 2196 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0PnAsEs3mta9vEDDow:-L0PnAsEs3mta9vEDDox:behpxrk) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2196)):*
> ```XML
>    * @param x The input array.
>    * @param ord Optional. Order of the norm. Supported values are following:
>    *     ord	       norm for matrices	        norm for vectors
> ```

this row is not an argument

---

*[src/math/math.ts, line 2197 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0PnD7nyUNxl86EngqG:-L0PnD7nyUNxl86EngqH:b-dkgrc6) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2197)):*
> ```XML
>    * @param ord Optional. Order of the norm. Supported values are following:
>    *     ord	       norm for matrices	        norm for vectors
>    *     'euclidean' Frobenius norm             2-norm
> ```

can you remove the tabs here and below?

---

*[src/math/math.ts, line 2206 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0PqTuIMQZFydfZVPN2:-L0PqTuIMQZFydfZVPN3:b-gkiq7i) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2206)):*
> ```XML
>    * @param axis Optional. If axis is None (the default), the input is
>    * considered a vector and a single vector norm is computed over the entire
>    * set of values in the NDArray, i.e. norm(NDArray, ord=ord) is equivalent
> ```

norm(x, ord)

typescript doesnt have named params

---

*[src/math/math.ts, line 2207 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0Pq_0ZJDDK9ffTQPsE:-L0Pq_0ZJDDK9ffTQPsF:b-67g4jo) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2207)):*
> ```XML
>    * considered a vector and a single vector norm is computed over the entire
>    * set of values in the NDArray, i.e. norm(NDArray, ord=ord) is equivalent
>    * to norm(reshape(NDArray, [-1]), ord=ord). If axis is a integer, the input
> ```

norm(reshape(x, [-1]), ord)

---

*[src/math/math.ts, line 2216 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0PnDmM6uOlGGzP4TUL:-L0PnDmM6uOlGGzP4TUM:b-98jlb7) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2216)):*
> ```XML
>    */
>   norm<G extends keyof DataTypes>(
>       x: NDArray<G>, ord: number|string = 'euclidean',
> ```

make order a string enum

ord: number|'euclidian'|'fro'

---

*[src/math/math.ts, line 2240 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0Pps95Ey_XI9d81bF1:-L0Pps95Ey_XI9d81bF2:bhfsi7s) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2240)):*
> ```XML
>    * @returns {number} Returns the norm
>    */
>   private normInternal<G extends keyof DataTypes>(
> ```

I dont think we need this "internal" method, let's merge.

---

*[src/math/math.ts, line 2250 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0PrjIJ3AYxPMUJL3Hf:-L0PrjIJ3AYxPMUJL3Hg:b4ve2jc) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2250)):*
> ```XML
>     // vector
>     if (x.rank === 1 || typeof axis === 'number' ||
>         axis instanceof Array && axis.length === 1) {
> ```

should we be checking axis here? I think we're going to error out if we pass no axis params when taking the norm of a vector:

math.norm(x)

---

*[src/math/math.ts, line 2251 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0PngtzzrRSFaeoSh1Z:-L0PngtzzrRSFaeoSh1_:b7bkq2x) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2251)):*
> ```XML
>     if (x.rank === 1 || typeof axis === 'number' ||
>         axis instanceof Array && axis.length === 1) {
>       if (p === 'inf') {
> ```

in numpy it looks like this isn't a string, this is is the -inf and inf python variables.

Maybe this should also take Infinity and -Infinity

---

*[src/math/math.ts, line 2267 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0Pru8qIbD9UhDwSdqF:-L0Pru8qIbD9UhDwSdqG:b-cp449k) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2267)):*
> ```XML
> 
>     // matrix
>     if (x.rank === 2 || axis instanceof Array && axis.length === 2) {
> ```

Same here - should we be checking axis here? I think we're going to error out if we pass no axis params when taking the norm of a matrix:

math.norm(matrix)

---

*[src/math/math.ts, line 2286 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0Pqvaf1yuHC4ItpL_w:-L0Pqvaf1yuHC4ItpL_x:bkjpkfq) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2286)):*
> ```XML
>     }
> 
>     throw new Error(
> ```

If we only support 0 => 2, let's type the input as such.

x: Scalar | Array1D | Array2D

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442)*

**Comment by dsmilkov** [comment]
Wohoo. This is a great start! Left a few comments, but nothing major. We can be stricter for v0 and generalize math.norm later.

---

Review status: 0 of 2 files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---

*[src/math/math.ts, line 2220 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0Q76d1bVxlU4nDyg20:-L0Q76d1bVxlU4nDyg21:b-mqd547) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2220)):*
> axis

why not pass `axes` here instead of `axis`. `axes` are normalized and always number[]. This will simplify a lot of the logic for checking the value of `axis` in the other method.

---

*[src/math/math.ts, line 2233 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0Q5EfBc68QWZSuwzE4:-L0Q5EfBc68QWZSuwzE5:b27ni1a) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2233)):*
> ```XML
>    *
>    * @param {NDArray} x
>    * @param {number | string} p
> ```

No need to describe the types in a jsdoc since we have them in the method signature.

---

*[src/math/math.ts, line 2267 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0Q8VJ3lY6NuOMjtn7-:-L0Q8VJ3lY6NuOMjtn70:b-l67s1r) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2267)):*
> ```XML
> 
>     // matrix
>     if (x.rank === 2 || axis instanceof Array && axis.length === 2) {
> ```

If not too complicated, can you merge the logic for each rank ? That is, have same code logic for both rank 1 and rank 2, and potentially any rank.

---

*[src/math/math.ts, line 2277 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0Q8Gc_AosofYMwi_27:-L0Q8Gc_AosofYMwi_28:bxt5mtc) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2277)):*
> ```XML
>         return this.min(this.sum(this.abs(x), axis ? axis[1] : 1, keepDims));
>       }
>       if (p === 'fro' || p === 'euclidean') {
> ```

missing `|| p === 2`

---

*[src/math/reduction_ops_test.ts, line 724 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0Q5xWddSzsbre24dsY:-L0Q5xWddSzsbre24dsZ:bj0d86t) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/reduction_ops_test.ts#L724)):*
> ```XML
>   };
> 
>   test_util.describeMathCPU('mean', [tests]);
> ```

Looks like this rename was not intentional: s/'mean'/'moments'/ 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-:-L0Q8yhcc9sfLu2OVSU7:b-gw3ap0)*

**Comment by pyu10055** [comment]
Review status: 0 of 2 files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---

*[src/math/math.ts, line 2189 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0Pq4MvhDRjdgMmnJMd:-L0QUWBQWzP601PuVRr4:b-g7dp7t) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2189)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

It looks like we dont actually support arbitrary dimensionality
</blockquote></details>

updated text.

---

*[src/math/math.ts, line 2196 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0PnAsEs3mta9vEDDow:-L0QUjvMcKwOex6QNeEz:b-x1139b) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2196)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

this row is not an argument
</blockquote></details>

move the table up in the method description.

---

*[src/math/math.ts, line 2197 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0PnD7nyUNxl86EngqG:-L0QUphtrEGB2l3pUDhI:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2197)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

can you remove the tabs here and below?
</blockquote></details>

Done.

---

*[src/math/math.ts, line 2206 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0PqTuIMQZFydfZVPN2:-L0QUrlrDJaBiomDk49b:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2206)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

norm(x, ord)

typescript doesnt have named params
</blockquote></details>

Done.

---

*[src/math/math.ts, line 2207 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0Pq_0ZJDDK9ffTQPsE:-L0QUsWcq68Gb8u0_JiN:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2207)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

norm(reshape(x, [-1]), ord)
</blockquote></details>

Done.

---

*[src/math/math.ts, line 2216 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0PnDmM6uOlGGzP4TUL:-L0QUtTyyhQ6hSpPYYeq:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2216)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

make order a string enum

ord: number|'euclidian'|'fro'


</blockquote></details>

Done.

---

*[src/math/math.ts, line 2220 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0Q76d1bVxlU4nDyg20:-L0QVSNBpJtlwYtHOHgZ:b-ewe8ys) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2220)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

> axis

why not pass `axes` here instead of `axis`. `axes` are normalized and always number[]. This will simplify a lot of the logic for checking the value of `axis` in the other method.
</blockquote></details>

I am not sure if I got the concept of axis correctly here. My understanding is that, if the input is null, it means any input turns into vector.
if the input is number or [x], it is calculating vector norm for collection of vectors along the specified axis.
if the input is [x, y], it is calculating the matrix norm for collection of matrices along the specified axes.

---

*[src/math/math.ts, line 2233 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0Q5EfBc68QWZSuwzE4:-L0QZRtsacUbLOKW-a__:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2233)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

No need to describe the types in a jsdoc since we have them in the method signature.
</blockquote></details>

Done.

---

*[src/math/math.ts, line 2240 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0Pps95Ey_XI9d81bF1:-L0QVZig8wuLUO8qVjLV:b-xe26e2) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2240)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

I dont think we need this "internal" method, let's merge.
</blockquote></details>

I find the internal method useful in helping to decouple the reshape operation and norm calculation.

---

*[src/math/math.ts, line 2250 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0PrjIJ3AYxPMUJL3Hf:-L0QVsPI6uPN2ko2Qsem:b-5e6vtj) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2250)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

should we be checking axis here? I think we're going to error out if we pass no axis params when taking the norm of a vector:

math.norm(x)
</blockquote></details>

changed the logic, now if the axis is null, it will reshape the input to vector. 
and the axis is to identify how many dimensions are used for calculating the norms.

---

*[src/math/math.ts, line 2251 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0PngtzzrRSFaeoSh1Z:-L0QW8yS6GGSmdiBeSn9:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2251)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

in numpy it looks like this isn't a string, this is is the -inf and inf python variables.

Maybe this should also take Infinity and -Infinity
</blockquote></details>

Done.

---

*[src/math/math.ts, line 2267 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0Q8VJ3lY6NuOMjtn7-:-L0QYju2neRKYPr2REhx:bu1h8ye) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2267)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

If not too complicated, can you merge the logic for each rank ? That is, have same code logic for both rank 1 and rank 2, and potentially any rank.
</blockquote></details>

updated the logic, now any rank is treated the same way, it mostly depends on the axis specified. I will defer this change, once we agree on the understanding of the impact of axis param.

---

*[src/math/math.ts, line 2267 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0Pru8qIbD9UhDwSdqF:-L0QZ5KeGPkHsJqt2Z_q:b-gz1am4) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2267)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

Same here - should we be checking axis here? I think we're going to error out if we pass no axis params when taking the norm of a matrix:

math.norm(matrix)
</blockquote></details>

same as the answers above.

---

*[src/math/math.ts, line 2277 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0Q8Gc_AosofYMwi_27:-L0QZF5xNyU1Xy3Bzxr3:b3z079c) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2277)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

missing `|| p === 2`
</blockquote></details>

2-norm is not defined for matrix.

---

*[src/math/math.ts, line 2286 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0Pqvaf1yuHC4ItpL_w:-L0QWJzSqe1SfOzM-QHV:bdpna7i) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2286)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

If we only support 0 => 2, let's type the input as such.

x: Scalar | Array1D | Array2D
</blockquote></details>

it can only calculate norm for scalar/vector/matrix, but it does support higher dimension NDArray, it will check the axis to determine the input for the norm calculation. 

---

*[src/math/reduction_ops_test.ts, line 724 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0Q5xWddSzsbre24dsY:-L0QZJPUKJTMamx3ly4w:b-2koddg) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/reduction_ops_test.ts#L724)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

Looks like this rename was not intentional: s/'mean'/'moments'/ 
</blockquote></details>

Done. thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442)*

**Comment by nsthorat** [comment]
Review status: 0 of 3 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[src/math/math.ts, line 2196 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0PnAsEs3mta9vEDDow:-L0W47wkifnHv7q8yzpI:bczsfxl) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2196)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

move the table up in the method description.
</blockquote></details>

this is still a little confusing, maybe a better way to show this is putting it under the argument tsdoc for "ord"

---

*[src/math/math.ts, line 2197 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0PnD7nyUNxl86EngqG:-L0W443bnWUqBsiXRlFv:bpud2mm) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2197)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I still see ">>" in reviewable

---

*[src/math/math.ts, line 2286 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0Pqvaf1yuHC4ItpL_w:-L0kh-sUpKgieiaCW97u:b-3uymwm) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2286)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

it can only calculate norm for scalar/vector/matrix, but it does support higher dimension NDArray, it will check the axis to determine the input for the norm calculation. 
</blockquote></details>

It supports higher dimensional NDArrays? If so, it's not just computing norms for scalar/vector/matrix. Are you saying that an axis reduction of a higher dimensional array could be a matrix?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442)*

**Comment by pyu10055** [comment]
Review status: 0 of 3 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[src/math/math.ts, line 2196 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0PnAsEs3mta9vEDDow:-L0krAuoh5ZehsVfFDsf:b3jk45q) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2196)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

this is still a little confusing, maybe a better way to show this is putting it under the argument tsdoc for "ord"
</blockquote></details>

Looked at the typedoc example, I am not sure where this type of information should be. is it better to be a comment line inside the method?

---

*[src/math/math.ts, line 2197 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0PnD7nyUNxl86EngqG:-L0kpEj36Pm2WM7NsF8p:bxbhld6) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2197)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

I still see ">>" in reviewable
</blockquote></details>

sorry they are removed.

---

*[src/math/math.ts, line 2286 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0Pqvaf1yuHC4ItpL_w:-L0koZ5JWfILAuBIu4tD:b7wyvpv) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2286)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

It supports higher dimensional NDArrays? If so, it's not just computing norms for scalar/vector/matrix. Are you saying that an axis reduction of a higher dimensional array could be a matrix?
</blockquote></details>

that is correct, the axis reduction of a high dimensional array into a matrix or a vector.
My understanding is that, if the axis is null, it means any input turns into vector.
if the axis is number or [x], it is calculating vector norm for collection of vectors along the specified axis.
if the axis is [x, y], it is calculating the matrix norm for collection of matrices along the specified axes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442)*

**Comment by nsthorat** [comment]
Resolving my comments. Wait for Daniel's LGTM and all is good! :)

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-:-L0kupPWooaeWQPmG1eu:baveu72)*

**Comment by dsmilkov** [comment]
:lgtm_strong:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/math/math.ts, line 2220 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-L0Q76d1bVxlU4nDyg20:-L0kgcBHHep4QL-lPaft:b38li1u) ([raw file](https://github.com/pair-code/deeplearnjs/blob/6d77ff6118833cbb179cca528d7210aeb5fbbc43/src/math/math.ts#L2220)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

I am not sure if I got the concept of axis correctly here. My understanding is that, if the input is null, it means any input turns into vector.
if the input is number or [x], it is calculating vector norm for collection of vectors along the specified axis.
if the input is [x, y], it is calculating the matrix norm for collection of matrices along the specified axes.
</blockquote></details>

Oh, you are right! I assumed `np.norm` treats the `axis` parameter as any other operation that takes `axis`, but in this case, looks like `np.norm` is not an element-wise norm, and treats axes differently than other operations (due to matrix norm vs vector norm complications)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-:-L0kvNJ7Khw9L60K8wK6:b-jbsf8z)*

**Comment by pyu10055** [comment]
thanks.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/442#-:-L0lThdLivm4UTKyJ9BX:bd5l6n4)*

**Pull request merged**
