### PR TITLE
implement sigmoid gradient in unary_ops

### PR DESCRIPTION
**Pull request by gena**
... does this make any sense? I'm just trying to understand how it works.

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/603)

### CODE REVIEW

**Comment by gena** [comment]
Oops, ci seems to break even everythin works locally ... investigating ...

**Comment by gena** [comment]
Adds `sigmoid` for issue #561

**Comment by nsthorat** [comment]
Looks great! Thanks for the contribution. 2 minor comments then I will merge.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/math/unary_ops.ts, line 209 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/603#-L3yJ2Ktn1iQBGfdvLdJ:-L3yJ2Ktn1iQBGfdvLdK:b-m5u18z) ([raw file](https://github.com/pair-code/deeplearnjs/blob/b25a63429eff7875eeead7346a51f7bd7c382292/src/math/unary_ops.ts#L209)):*
> ```XML
>     return ENV.engine.executeKernel(
>       'Sigmoid', {inputs: {x}}, (dy: NDArray, y: NDArray) => {
>           return {x: () => y.toFloat().mul(Scalar.new(1).sub(y)).mul(dy)};
> ```

no need to do toFloat() here as y will always be a float.

This looks great though!

---

*[src/math/unary_ops_test.ts, line 295 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/603#-L3yKMlJEQHxZ8PjSuHD:-L3yKMlJEQHxZ8PjSuHE:b-ix3g3n) ([raw file](https://github.com/pair-code/deeplearnjs/blob/b25a63429eff7875eeead7346a51f7bd7c382292/src/math/unary_ops_test.ts#L295)):*
> ```XML
>       const expected = [];
>       for (let i = 0; i < a.size; i++) {
>         const e = Math.exp(-a.get(i));
> ```

Can you compute a "y" here and use the standard format of the gradient here for clarity:

dy * y * (1 - y)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/603#-:-L3yKYQX4d5nEeSe93FZ:bzapb5l)*

**Comment by gena** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/math/unary_ops.ts, line 209 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/603#-L3yJ2Ktn1iQBGfdvLdJ:-L3ycCzPidANbJiKKlwa:b-txxcky) ([raw file](https://github.com/pair-code/deeplearnjs/blob/b25a63429eff7875eeead7346a51f7bd7c382292/src/math/unary_ops.ts#L209)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

no need to do toFloat() here as y will always be a float.

This looks great though!
</blockquote></details>

Thanks! ... learning ... :). Probably copy/pasted from somewhere else.

---

*[src/math/unary_ops_test.ts, line 295 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/603#-L3yKMlJEQHxZ8PjSuHD:-L3yco8nF8tV2CjRHha8:bygtg6h) ([raw file](https://github.com/pair-code/deeplearnjs/blob/b25a63429eff7875eeead7346a51f7bd7c382292/src/math/unary_ops_test.ts#L295)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

Can you compute a "y" here and use the standard format of the gradient here for clarity:

dy * y * (1 - y)
</blockquote></details>

Sure, makes sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/603)*

**Comment by nsthorat** [comment]
Last thing I missed in the last set of comments, then I will merge. Good work!

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/math/unary_ops.ts, line 209 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/603#-L3yJ2Ktn1iQBGfdvLdJ:-L3ykigRQWeuPrRc1kXg:bplwyt) ([raw file](https://github.com/pair-code/deeplearnjs/blob/b25a63429eff7875eeead7346a51f7bd7c382292/src/math/unary_ops.ts#L209)):*
<details><summary><i>Previously, gena wrote…</i></summary><blockquote>

Thanks! ... learning ... :). Probably copy/pasted from somewhere else.
</blockquote></details>

Awesome! One more thing I missed, the signature of the gradient should be:

`(dy: T, y: T) => ...`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/603#-:-L3ykqjCWATlsPtxhYFa:b9y535z)*

**Comment by gena** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/math/unary_ops.ts, line 209 at r2](https://reviewable.io:443/reviews/pair-code/deeplearnjs/603#-L3yJ2Ktn1iQBGfdvLdJ:-L3ymccoyy0IX4sjIJUs:b-9vhyet) ([raw file](https://github.com/pair-code/deeplearnjs/blob/b25a63429eff7875eeead7346a51f7bd7c382292/src/math/unary_ops.ts#L209)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

Awesome! One more thing I missed, the signature of the gradient should be:

`(dy: T, y: T) => ...`
</blockquote></details>

Indeed, fixed!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/603)*

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/603#-:-L3yp7FV6Yu2BFZWUgHX:b-jbsf8z)*

**Pull request merged**
