### PR TITLE
Add math.clamp

### PR DESCRIPTION
**Pull request by reiinakano**
Adds `math.clamp()`

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/199)

### CODE REVIEW

**Comment by nsthorat** [comment]
This is excellent, thank you for the contribution!

One high level comment:

- Can we call this `clip` to mirror numpy and tensorflow?
https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.clip.html
https://www.tensorflow.org/api_docs/python/tf/clip_by_value

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/math/webgl/clamp_gpu.ts, line 28 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/199#-Kw5jiMMbsB3jBPcixcZ:-Kw5jiMMbsB3jBPcixc_:b-beve4) ([raw file](https://github.com/pair-code/deeplearnjs/blob/fa1f6e98b4f4adb4d174ee7fece23bf307d6faad/src/math/webgl/clamp_gpu.ts#L28)):*
> ```XML
>   constructor(aShape: number[], min: number, max: number) {
>     this.outputShape = aShape;
>     this.params = [min, max];
> ```

minor suggestion: use the minFixed and maxFixed as params (these are the cache keys to the program)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/199#-:-Kw5j73XJwUuGQsa21M-:b-e5qj7c)*

**Comment by reiinakano** [comment]
Done!

By the way, what's the correct way to run only specific tests with the new math test format? I tried 
changing

```ts
it('propagates NaNs', math => {
      ...
    });
```

to 

```ts
fit('propagates NaNs', math => {
      ...
    });
```

but that doesn't work.

**Comment by nsthorat** [comment]
Oh ha! I didn't know about fit() or fdescribe(), I'll have to add some wiring to punch that through to our custom tester.

One way to only run the tests you care about right now is to run:

`./node_modules/karma/bin/karma run -- --grep="math.clip"`

in another terminal, while the other `npm run test` is running. This will focus karma on tests that match this.

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/199#-:-Kw6-4QFiPvHHpoUBwJ3:b-16jyl6)*

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/199#-:-Kw6-Ue8YmhrYFMkksc0:b-jbsf8z)*

**Pull request merged**
