### PR TITLE
Switch shader indexing from float to int

### PR DESCRIPTION
**Pull request by dsmilkov**
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/93)

### CODE REVIEW

**Comment by dsmilkov** [comment]
Also tested model-builder and ran benchmark (no perf degrade, actually shaders run slightly faster ~2%)

**Comment by dsmilkov** [comment]
Same PR includes profiling functionality in the console when `math.enableDebugMode()` is called.

screen shot 2017-09-04 at 7 56 25 pm

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Reviewed 23 of 23 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/math/math.ts, line 231 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/93#-KtIgwtn5fqZdFYgACQU:-KtIgwtn5fqZdFYgACQV:bl4dazf) ([raw file](https://github.com/pair-code/deeplearnjs/blob/11d9ad4622dae5564601c6c30dcf3d4b92bb4ecc/src/math/math.ts#L231)):*
> ```XML
>     let start: number;
>     if (this.debugMode) {
>       start = Date.now();
> ```

use performance.now()

---

*[src/math/webgl/gpgpu_context_test.ts, line 48 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/93#-KtHk5QzxSbYRqxscimT:-KtHk5QzxSbYRqxscimU:b-gcqz0p) ([raw file](https://github.com/pair-code/deeplearnjs/blob/11d9ad4622dae5564601c6c30dcf3d4b92bb4ecc/src/math/webgl/gpgpu_context_test.ts#L48)):*
> ```XML
>     const result = gpgpu.downloadMatrixFromTexture(texture, 1, 1);
>     expect(result[0]).toBeCloseTo(1.234);
>   });
> ```

add the same test here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/93#-:-KtIjKc9WaEwutaKlhoQ:b-jbsf8z)*

**Comment by dsmilkov** [comment]
Review status: 21 of 23 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[src/math/math.ts, line 231 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/93#-KtIgwtn5fqZdFYgACQU:-KtK-_wg0kMsoDYX8a20:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/11d9ad4622dae5564601c6c30dcf3d4b92bb4ecc/src/math/math.ts#L231)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

use performance.now()
</blockquote></details>

Done.

---

*[src/math/webgl/gpgpu_context_test.ts, line 48 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/93#-KtHk5QzxSbYRqxscimT:-KtK-uMrBbOmE1GIj9gb:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/11d9ad4622dae5564601c6c30dcf3d4b92bb4ecc/src/math/webgl/gpgpu_context_test.ts#L48)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

add the same test here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/93)*

**Pull request merged**
