### PR TITLE
Parallelize reduction ops on GPU (min/max/sum/argMax/argMin/logSumExp)

### PR DESCRIPTION
**Pull request by dsmilkov**
Optimize reduction on GPU by having several shader passes with a window.
This results in **speedup > 200X** for large values.

### BEFORE
before

### AFTER
after

Other changes:

- Fix small bug regarding `keepDims` in sum/min/max.
- Simplify shader compiler by removing batching as a special param
- remove `logsumexp_gpu` shader which is now obsolete
- Add `argMax` and `argMin` to benchmarks demo

This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/338)

### CODE REVIEW

**Comment by nsthorat** [comment]
:lgtm_strong:

Damn Daniel, back at it again with the awesome PR!

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[.gitignore, line 13 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/338#-KygGqoFJJZxawDLSiy6:-KygGqoFJJZxawDLSiy7:bn3vhy1) ([raw file](https://github.com/pair-code/deeplearnjs/blob/a25584c1b15c2454cc2d51925759de4f7235cd9a/.gitignore#L13)):*
> ```
> dist/
> .idea/
> package-lock.json
> ```

this is already here, see a few lines above (I added it in the previous PR).

---

*[src/math/math_gpu.ts, line 269 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/338#-KygLy7fyyTxSaW6XMV0:-KygLy7fyyTxSaW6XMV1:b-ckab16) ([raw file](https://github.com/pair-code/deeplearnjs/blob/a25584c1b15c2454cc2d51925759de4f7235cd9a/src/math/math_gpu.ts#L269)):*
> ```XML
>         this.makeOutputArray(program.outputShape, 'int32').as2D(rows, cols);
>     const inputs = [a];
>     if (bestA != null) {
> ```

it took me a little while to understand why you needed "bestA", can you call this "bestIndicesA" or something?

---

*[src/math/reduce_util.ts, line 28 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/338#-KygHNvmKhJhhyQoZHpq:-KygHNvmKhJhhyQoZHpr:bmupnuk) ([raw file](https://github.com/pair-code/deeplearnjs/blob/a25584c1b15c2454cc2d51925759de4f7235cd9a/src/math/reduce_util.ts#L28)):*
> ```XML
>  * shader programs.
>  */
> export const PARALLELIZE_THRESHOLD = 30;
> ```

move this to top of the file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/338#-:-KygMrXK8SBq_cZtwMcW:bn0b54i)*

**Comment by nsthorat** [comment]
@reiinakano FYI, this speeds up your style transfer demo by a *lot*. I hacked a version the other day that does live webcam transfer (I had to downscale everything for it to be live), with this it will be more reasonable!

**Comment by reiinakano** [comment]
Oh wow awesome! Must be from the math.moments speedup.

**Comment by dsmilkov** [comment]
Review status: 12 of 16 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[.gitignore, line 13 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/338#-KygGqoFJJZxawDLSiy6:-KyhR-fb155kJOwgWPTm:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/a25584c1b15c2454cc2d51925759de4f7235cd9a/.gitignore#L13)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

this is already here, see a few lines above (I added it in the previous PR).
</blockquote></details>

Done.

---

*[src/math/math_gpu.ts, line 269 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/338#-KygLy7fyyTxSaW6XMV0:-KyhRQxvzCb9GbigZ4Ly:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/a25584c1b15c2454cc2d51925759de4f7235cd9a/src/math/math_gpu.ts#L269)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

it took me a little while to understand why you needed "bestA", can you call this "bestIndicesA" or something?
</blockquote></details>

Done.

---

*[src/math/reduce_util.ts, line 28 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/338#-KygHNvmKhJhhyQoZHpq:-KyhR9Hit9Pa-nCSjGCt:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/a25584c1b15c2454cc2d51925759de4f7235cd9a/src/math/reduce_util.ts#L28)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

move this to top of the file
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/338)*

**Pull request merged**
