### PR TITLE
Sgd+ momentum optimizer added

### PR DESCRIPTION
**Pull request by mnottheone**
Created a simple SGD+Momentum optimizer and have tested in session_test.ts for initial commit to get familiar. If this goes well, will start working on other optimizers.

---
This change is [Reviewable](https://reviewable.io/reviews/pair-code/deeplearnjs/62)

### CODE REVIEW

**Comment by mnottheone** [comment]
I have signed cla. Let me know if something else is needed. :)

**Comment by nsthorat** [comment]
Thank you so much for this contribution!

Most of the comments I have are stylistic nits (to adhere to Google style guides), with only one major suggestion which should reduce the amount of code and be pretty straightforward to implement.

Since this is pretty much strictly better than SGD, do you want to go ahead and check in the model-builder change to use the new optimizer?

If you have any questions about the comments don't hesitate to ask.

Reminder to run `npm run lint` and `npm run tests`!

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---

*[src/momentumOptimizer.ts, line 21 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62#-KsCE160K-lfd_WV4E3k:-KsCE160K-lfd_WV4E3l:b7bxl3l) ([raw file](https://github.com/pair-code/deeplearnjs/blob/90c0ca36aa82f7a2aeb483348eabc44889814422/src/momentumOptimizer.ts#L21)):*
> ```XML
> import {TensorArrayMap} from './tensor_array_map';
> 
> export class MomentumOptimizer extends Optimizer {
> ```

MomentumOptimizer is very similar to SGD, the only difference is the afterBatch method. Can you make this class extend SGDOptimizer, and then just override the `afterBatch` method?

---

*[src/momentumOptimizer.ts, line 23 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62#-KsCCg3VNA2UuW9xpyiE:-KsCCg3VNA2UuW9xpyiF:bw5rk8c) ([raw file](https://github.com/pair-code/deeplearnjs/blob/90c0ca36aa82f7a2aeb483348eabc44889814422/src/momentumOptimizer.ts#L23)):*
> ```XML
> export class MomentumOptimizer extends Optimizer {
>   constructor(private learningRate: number, private momentum: 
>       number, specifiedVariableList?: Node[]) {
> ```

if number doesn't fit on the previous line, move `private momentum:` to the next line before `:number`.

---

*[src/momentumOptimizer.ts, line 25 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62#-KsCBTGXbCZIk7a_DxkR:-KsCBTGXbCZIk7a_DxkS:b-4llf5e) ([raw file](https://github.com/pair-code/deeplearnjs/blob/90c0ca36aa82f7a2aeb483348eabc44889814422/src/momentumOptimizer.ts#L25)):*
> ```XML
>       number, specifiedVariableList?: Node[]) {
>     super(specifiedVariableList);
>     if(specifiedVariableList == null)
> ```

Ahh, maybe this should be renamed. specifiedVariableList is only used to specify a subset of variables to optimizer (freezing a subset of the graph). If it's null, that means optimize all variables. That means your constructor should simply be the super call (remove these lines)

---

*[src/momentumOptimizer.ts, line 31 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62#-KsCEIgjmXo03G-_iHS2:-KsCEIgjmXo03G-_iHS3:blsznxe) ([raw file](https://github.com/pair-code/deeplearnjs/blob/90c0ca36aa82f7a2aeb483348eabc44889814422/src/momentumOptimizer.ts#L31)):*
> ```XML
>   }
> 
>   beforeBatch(
> ```

once you extend SGDOptimizer this method is just the super call, the `this.m`, the `variableVelocities` setup.

---

*[src/momentumOptimizer.ts, line 43 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62#-KsCES2xTl8TXFekH2lO:-KsCCnqu6Oco3C7WScjW:b-sftl44) ([raw file](https://github.com/pair-code/deeplearnjs/blob/90c0ca36aa82f7a2aeb483348eabc44889814422/src/momentumOptimizer.ts#L43)):*
> ```XML
>       
>     }
>     if (this.variableVelocities == null){
> ```

space between `)` and `{`

---

*[src/momentumOptimizer.ts, line 46 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62#-KsCCn7DDxXh4jZoe2op:-KsCCn7Ee32SdMNPBWVe:bx20ub) ([raw file](https://github.com/pair-code/deeplearnjs/blob/90c0ca36aa82f7a2aeb483348eabc44889814422/src/momentumOptimizer.ts#L46)):*
> ```XML
>     this.variableVelocities = new TensorArrayMap();
>     this.variableNodes.forEach(
>         node => {          
> ```

remove extra spaces, and move `node => {` to the previous line. Then you can unindent the contents of the foreach block (part of google style guide)

---

*[src/momentumOptimizer.ts, line 53 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62#-KsCEXrFPfmwDh9zZHQm:-KsCEXrFPfmwDh9zZHQn:bqcdko9) ([raw file](https://github.com/pair-code/deeplearnjs/blob/90c0ca36aa82f7a2aeb483348eabc44889814422/src/momentumOptimizer.ts#L53)):*
> ```XML
> 
> 
>     this.variableNodes.forEach(
> ```

this will go away since it's in the super

---

*[src/momentumOptimizer.ts, line 60 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62#-KsCEcA9M_DzpRQwJyjb:-KsCEcA9M_DzpRQwJyjc:bsau0mt) ([raw file](https://github.com/pair-code/deeplearnjs/blob/90c0ca36aa82f7a2aeb483348eabc44889814422/src/momentumOptimizer.ts#L60)):*
> ```XML
>   }
> 
>   afterExample(
> ```

this will go away

---

*[src/momentumOptimizer.ts, line 79 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62#-KsCEdO2Z5kpT0dSplrL:-KsCEdO2Z5kpT0dSplrM:b2btlqg) ([raw file](https://github.com/pair-code/deeplearnjs/blob/90c0ca36aa82f7a2aeb483348eabc44889814422/src/momentumOptimizer.ts#L79)):*
> ```XML
>       activationArrayMap: TensorArrayMap, gradientArrayMap: TensorArrayMap) {
>     math.scope((keep) => {
>       this.variableNodes!.forEach(node => {
> ```

remove the `!`, we're using a non-strict ts-compiler now

---

*[src/momentumOptimizer.ts, line 83 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62#-KsCEinIw4E7dmuIRgi-:-KsCEinIw4E7dmuIRgi0:b8oz7l1) ([raw file](https://github.com/pair-code/deeplearnjs/blob/90c0ca36aa82f7a2aeb483348eabc44889814422/src/momentumOptimizer.ts#L83)):*
> ```XML
>         const gradient = this.variableGradients.get(node.output);
>         const oldVelocity = this.variableVelocities.get(node.output);
>         const velocity = math.scaledArrayAdd(this.m!,
> ```

you should be able to remove `!`, and below on the `this.one!`.

---

*[src/momentumOptimizer.ts, line 111 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62#-KsCGMlS1JXDEvNqKnTA:-KsCGMlS1JXDEvNqKnTB:bt522be) ([raw file](https://github.com/pair-code/deeplearnjs/blob/90c0ca36aa82f7a2aeb483348eabc44889814422/src/momentumOptimizer.ts#L111)):*
> ```XML
>   }
> 
>   setLearningRate(learningRate: number) {
> ```

this will go away once you extend the SGD base clasee

---

*[src/momentumOptimizer.ts, line 120 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62#-KsCH6fWFVHRZP1jbMwI:-KsCH6fWFVHRZP1jbMwJ:b-hh8e2f) ([raw file](https://github.com/pair-code/deeplearnjs/blob/90c0ca36aa82f7a2aeb483348eabc44889814422/src/momentumOptimizer.ts#L120)):*
> ```XML
> 
>   private variableGradients = new TensorArrayMap();
>   private variableVelocities = new TensorArrayMap();
> ```

no need to initialize this since you do it in the beforeBatch, just set the type:

`private variableVelocities: TensorArrayMap;`

---

*[src/session_test.ts, line 300 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62#-KsCGe4pQ5fxgKsHJ2h-:-KsCGe4pQ5fxgKsHJ2h0:b-79p75y) ([raw file](https://github.com/pair-code/deeplearnjs/blob/90c0ca36aa82f7a2aeb483348eabc44889814422/src/session_test.ts#L300)):*
> ```XML
> 
>     const safeMode = true;
>     const optimizer = new MomentumOptimizer(0.1,0.5);
> ```

space after the ,

---

*[src/session_test.ts, line 305 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62#-KsCGbN_a4KtRAC7wCrN:-KsCGbN_a4KtRAC7wCrO:bordsuo) ([raw file](https://github.com/pair-code/deeplearnjs/blob/90c0ca36aa82f7a2aeb483348eabc44889814422/src/session_test.ts#L305)):*
> ```XML
>     const inputProvider: InputProvider = {
>       getNextCopy() {
>         return Array1D.new([2, 4 ]);
> ```

remove space after the 4

---

*[src/session_test.ts, line 315 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62#-KsCGkTnVkLzNZrthOHS:-KsCGkTnVkLzNZrthOHT:b-wxrfkh) ([raw file](https://github.com/pair-code/deeplearnjs/blob/90c0ca36aa82f7a2aeb483348eabc44889814422/src/session_test.ts#L315)):*
> ```XML
>       //                momentum* old_vel_w2 + x_2] = [2,4]
>       // w = [ w_old - lr*vel_w1, w_old - lr*vel_w2] = [-0.2, -0.4]
>       session.train(y, [{tensor: x, data: inputProvider}], 1, optimizer);
> ```

can you assert the intermittent values here as well?

---

*[src/session_test.ts, line 321 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62#-KsCG_4Kk_fUItmeZONW:-KsCG_4Kk_fUItmeZONX:b345e03) ([raw file](https://github.com/pair-code/deeplearnjs/blob/90c0ca36aa82f7a2aeb483348eabc44889814422/src/session_test.ts#L321)):*
> ```XML
>       session.train(y, [{tensor: x, data: inputProvider}], 1, optimizer);
>       const dydw = session.activationArrayMap.get(w).getValues();
>       test_util.expectArraysClose(dydw, new Float32Array([-.5,-1.0]), 2e-5);
> ```

space after the comma

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62#-:-KsCHE0lqZvTxi2zxzE1:b-rh5afi)*

**Comment by mnottheone** [comment]
Hi ! 

Thanks for the feedback. I am new to javascript/typescript , so a good feedback is really helpful. I have made the changes as suggested and tried to use it in model-builder. It was working when I tried demo locally. Also, linting and testing done. :) 

Please have a look and let me know if anything else should be done.

**Comment by nsthorat** [comment]
No problem!

If you use reviewable.io, when each of the comments I made have been fixed, you can acknowledge them so that the comments go away as you finish. For now, I did that for you.

Looking better, still a couple comments :)

Let me know if you have questions.

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/momentumOptimizer.ts, line 31 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62#-KsCEIgjmXo03G-_iHS2:-KsJeKjJ9ILb9fZ1SQdf:b-3qf1y6) ([raw file](https://github.com/pair-code/deeplearnjs/blob/90c0ca36aa82f7a2aeb483348eabc44889814422/src/momentumOptimizer.ts#L31)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

once you extend SGDOptimizer this method is just the super call, the `this.m`, the `variableVelocities` setup.
</blockquote></details>

You can call the super since a lot of the code is in common!

---

*[src/momentumOptimizer.ts, line 46 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62#-KsCCn7DDxXh4jZoe2op:-KsJePh9WQX1lbyNycAP:b-frl2fp) ([raw file](https://github.com/pair-code/deeplearnjs/blob/90c0ca36aa82f7a2aeb483348eabc44889814422/src/momentumOptimizer.ts#L46)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

remove extra spaces, and move `node => {` to the previous line. Then you can unindent the contents of the foreach block (part of google style guide)
</blockquote></details>

still trailing spaces after {

---

*[src/momentumOptimizer.ts, line 53 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62#-KsCEXrFPfmwDh9zZHQm:-KsJeSb-FHkZpu4M2Hbu:bwhty30) ([raw file](https://github.com/pair-code/deeplearnjs/blob/90c0ca36aa82f7a2aeb483348eabc44889814422/src/momentumOptimizer.ts#L53)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

this will go away since it's in the super
</blockquote></details>

This can still go away since it's in the super!

---

*[src/momentumOptimizer.ts, line 120 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62#-KsCH6fWFVHRZP1jbMwI:-KsJecyWSLFFynBSkxpe:bme2q30) ([raw file](https://github.com/pair-code/deeplearnjs/blob/90c0ca36aa82f7a2aeb483348eabc44889814422/src/momentumOptimizer.ts#L120)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

no need to initialize this since you do it in the beforeBatch, just set the type:

`private variableVelocities: TensorArrayMap;`
</blockquote></details>

This still shouldn't be initialized here

---

*[src/session_test.ts, line 305 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62#-KsCGbN_a4KtRAC7wCrN:-KsJel6wU1ELgfN2d4C_:b-9683ye) ([raw file](https://github.com/pair-code/deeplearnjs/blob/90c0ca36aa82f7a2aeb483348eabc44889814422/src/session_test.ts#L305)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

remove space after the 4
</blockquote></details>

Still need to remove the space after the 4.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62#-:-KsJdtExSqc9L-f962Qt:bqe35g5)*

**Comment by mnottheone** [comment]
Hi ! 

About declaring variableVelocities outside beforeBatch, I did so that I can check it's size and decide whether it's first batch and I need to intialize velocities by zero.  Without doing that I won't be able to call size() function. 

Let me know if I am wrong somewhere or it can be done better way.

Other changes done.

**Comment by mnottheone** [comment]
*[src/momentumOptimizer.ts, line 120 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62#-KsCH6fWFVHRZP1jbMwI:-KsKVkERXUu0d9_Mh_gv:bguwjri) ([raw file](https://github.com/pair-code/deeplearnjs/blob/90c0ca36aa82f7a2aeb483348eabc44889814422/src/momentumOptimizer.ts#L120)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

This still shouldn't be initialized here
</blockquote></details>

I did so that I can check it's size and decide whether it's first batch and I need to initialize velocities by zero.  Without doing that I won't be able to call size() function. I will remove the this.variableVelocities = new TensorArrayMap() from beforeBatch(). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62)*

**Comment by nsthorat** [comment]
Okay, that's fine. Can you run `npm run lint` and just make sure there are no problems (some of the tiny style problems came back - by the way, if you use vscode we have settings for this project could will be helpful).

Just a couple minor things then I will merge this!

Thank you for the contribution!

---

Reviewed 1 of 2 files at r3.
Review status: 4 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/momentumOptimizer.ts, line 120 at r1](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62#-KsCH6fWFVHRZP1jbMwI:-KsMey62b5Ymzhq3AYwS:boszgop) ([raw file](https://github.com/pair-code/deeplearnjs/blob/90c0ca36aa82f7a2aeb483348eabc44889814422/src/momentumOptimizer.ts#L120)):*
<details><summary><i>Previously, mnottheone (Aman Kumar Singh) wrote…</i></summary><blockquote>

I did so that I can check it's size and decide whether it's first batch and I need to initialize velocities by zero.  Without doing that I won't be able to call size() function. I will remove the this.variableVelocities = new TensorArrayMap() from beforeBatch(). 
</blockquote></details>

Okay got it, this is fine!

---

*[src/momentumOptimizer.ts, line 30 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62#-KsMe2EqXxdtH6fO-piL:-KsMe2EqXxdtH6fO-piM:b3lqllm) ([raw file](https://github.com/pair-code/deeplearnjs/blob/55cb3fd679e27ad0902e0a953e0f8a55420a078a/src/momentumOptimizer.ts#L30)):*
> ```XML
>     activationArrayMap: TensorArrayMap, gradientArrayMap: TensorArrayMap) {
>     super.beforeBatch(math, batchSize, runtime,
>     	activationArrayMap, gradientArrayMap);
> ```

spaces instead of tabs here :)

---

*[src/momentumOptimizer.ts, line 33 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62#-KsMekFJuZFYabgO5DBu:-KsMeMzx2rk8a7nlDWm1:bsy33k5) ([raw file](https://github.com/pair-code/deeplearnjs/blob/55cb3fd679e27ad0902e0a953e0f8a55420a078a/src/momentumOptimizer.ts#L33)):*
> ```XML
> 
>     this.m = Scalar.new(this.momentum);
>     if (this.variableVelocities.size() === 0){
> ```

deleted that space here haha :), `npm run lint` should pick these up I think 

you have tabs below here too, should be spaces

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62#-:-KsMf6OZiaHI8k9CrL59:b5zsdm9)*

**Comment by nsthorat** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62)*

**Comment by mnottheone** [comment]
*[src/momentumOptimizer.ts, line 30 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62#-KsMe2EqXxdtH6fO-piL:-KsMj81XDeRKV1ditFzI:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/55cb3fd679e27ad0902e0a953e0f8a55420a078a/src/momentumOptimizer.ts#L30)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

spaces instead of tabs here :)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62)*

**Comment by mnottheone** [comment]
*[src/momentumOptimizer.ts, line 33 at r3](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62#-KsMekFJuZFYabgO5DBu:-KsMjM6I3vKdWwECKe8W:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/55cb3fd679e27ad0902e0a953e0f8a55420a078a/src/momentumOptimizer.ts#L33)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

deleted that space here haha :), `npm run lint` should pick these up I think 

you have tabs below here too, should be spaces
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62)*

**Comment by nsthorat** [comment]
Sorry for being picky, one last quick style thing :)

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/momentumOptimizer.ts, line 36 at r4](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62#-KsMjMNI56TDXuzNXGYP:-KsMjMNI56TDXuzNXGYQ:bn8c0l7) ([raw file](https://github.com/pair-code/deeplearnjs/blob/c4487761d7a9ef7345641230c826949171d775ef/src/momentumOptimizer.ts#L36)):*
> ```XML
>       this.variableNodes.forEach(node => {
>         this.variableVelocities.set(node.output,
>         NDArray.zeros(node.output.shape));
> ```

sorry for being nitpicky here, can you indent this 4 over?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62#-:-KsMk6jlg4X-fMfkVExx:b-kobbt)*

**Comment by mnottheone** [comment]
*[src/momentumOptimizer.ts, line 36 at r4](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62#-KsMjMNI56TDXuzNXGYP:-KsMlay4uLeSOTbRZr1W:b-896fix) ([raw file](https://github.com/pair-code/deeplearnjs/blob/c4487761d7a9ef7345641230c826949171d775ef/src/momentumOptimizer.ts#L36)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

sorry for being nitpicky here, can you indent this 4 over?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62)*

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pair-code/deeplearnjs/62#-:-KsOYTH9XmRUkkzDr9YH:b-jbsf8z)*

**Comment by mnottheone** [comment]
Thanks for merging it :) 
I have started using vsc as an editor, hopefully, in future styling won't take time. 

Also, working on RMSprop and Adagrad, will keep using this [this issue](https://github.com/PAIR-code/deeplearnjs/issues/58) for all the doubts :)

**Comment by nsthorat** [comment]
Thank you for the contribution! We're also about to add an auto-formatter to vscode so every time you save it will fix those minor things (sorry I'm pedantic, Google style guide makes you that way :P)

Sounds great, that issues is perfect for tracking this! Looking forward to the next optimizers!

**Pull request merged**
